### ISSUE TITLE
No distribution found 

### ISSUE THREAD

**Issue by AlishahMughal123** [maurosoria/dirsearch#1001]
![image](https://user-images.githubusercontent.com/52525188/145670674-2432906d-5293-4862-ac77-119c3e9cfcc7.png)

pip3 not working

**Comment by shelld3v** [comment]
You can try:
```
pip3 install --upgrade pip
pip3 install dirsearch
```
Or
```
curl https://bootstrap.pypa.io/get-pip.py | python3
pip3 install dirsearch
```

**Comment by AlishahMughal123** [comment]
Not working at all, You can check by yourself

**Comment by shelld3v** [comment]
I can't check it because it's not reproducible on my side, I just searched the solution on the Internet. This is not an issue with the tool. Can you give me the output of `curl https://bootstrap.pypa.io/get-pip.py | python3`?

**Comment by shelld3v** [comment]
Closed because it was not an issue with dirsearch itself
