### ISSUE TITLE
error to execute the file

### ISSUE THREAD

**Issue by cruizer468** [maurosoria/dirsearch#1004]
Why Is Not Working ?
i have the dirsearch command and the code not working
here's my screenshot
![why](https://user-images.githubusercontent.com/36890086/146076383-4ece7027-54fa-426c-b8e2-c39ae8e97cfe.JPG)

please tell me whats wrong
Thankyou

way.

**Comment by Ivan0x17** [comment]
> Why Is Not Working ?
> 
> i have the dirsearch command and the code not working
> 
> here's my screenshot
> 
> ![why](https://user-images.githubusercontent.com/36890086/146076383-4ece7027-54fa-426c-b8e2-c39ae8e97cfe.JPG)
> 
> 
> 
> please tell me whats wrong
> 
> Thankyou
> 
> 
> 
> way.

I the problem reguard the module Chardet
For resolve the problem install it using a command 
pip install chardet
Or
Pip3 install chardet

**Comment by cruizer468** [comment]
i have already install chardet
----
Requirement already satisfied: chardet in c:\users\wahyu\appdata\local\programs\python\python310\lib\site-packages (4.0.0)
thankyou for the answer but not worked

**Comment by shelld3v** [comment]
Hi @cruizer468, I can see that you installed `chardet` package in another drive (`C:/`) from the one you saved dirsearch (`D:/`), that maybe the cause of this issue

**Comment by shelld3v** [comment]
Closing as it has been inactive for a while and I have shown the solution, feel free to ask for reopening
