### ISSUE TITLE
在-l urls.txt批量扫描过程中报错导致扫描中断

### ISSUE THREAD

**Issue by Scivous** [maurosoria/dirsearch#1006]
在-l urls.txt批量扫描过程中报错导致扫描中断
执行的命令为：
python3 dirsearch.py -l urls.txt --format csv -o xxx.com.csv
前几个都执行的没问题。后面会报错，导致进程终止，无法扫描全部urls。
![Snipaste_2021-12-22_00-06-10](https://user-images.githubusercontent.com/66907785/146961497-a92546c8-ae64-4336-8716-885c27f0f053.png)

**Comment by Scivous** [comment]
单独运行该url也会报错，希望在批量扫描过程中，出现报错继续下一个，不要中断扫描进程。
![Snipaste_2021-12-22_00-09-31](https://user-images.githubusercontent.com/66907785/146962102-fb1f2ff7-958a-4cf4-8e7c-61fcaa1f1e7b.png)
When an error occurs, I hope to continue scanning the next one. Instead of directly interrupting the scanning process.

**Comment by shelld3v** [comment]
Hi this issue has been fixed already, please delete and then re-install your dirsearch with git: `git clone https://github.com/maurosoria/dirsearch`
