### ISSUE TITLE
batch process will use so many cpu and memory , the computer is stuck. can optimize the performance ,gobuster scan is use a litttle cpu and memory

### ISSUE THREAD

**Issue by fayewong00** [maurosoria/dirsearch#1007]
batch process will use so many cpu and memory , the computer is stuck. can optimize the performance ,gobuster scan is use a litttle cpu and memory.gobuster is use golang.

**Comment by shelld3v** [comment]
You can reduce the threads

**Comment by fayewong00** [comment]
> You can reduce the threads

so many webs penetration testing ,batch

**Comment by shelld3v** [comment]
I don't understand what do you mean

**Comment by fayewong00** [comment]
> I don't understand what do you mean

With a small amount of testing, the tool is fine. But batch testing will consume a lot of computer resources, causing the computer to freeze. Usually batch testing is very much。

**Comment by shelld3v** [comment]
I will try to figure out how to improve dirsearch performance, but this seems to be a long-term issue, might take a lot of time and can not be fully fixed

**Comment by fayewong00** [comment]
> I will try to figure out how to improve dirsearch performance, but this seems to be a long-term issue, might take a lot of time and can not be fully fixed

Thank you very much! Found in batch test process, occupy computer resources too much, so make a suggestion! I also know that this is a long and arduous task. If you have time, you can try to improve the performance. If you don't have time, you can do it temporarily. Multithreaded coroutine concurrency, occupying resources, Golang language shows natural superiority! Python is also great, but less performance wise!

**Comment by guendouzaimed** [comment]
try this tool it doesn't use many cpu and run faster [https://github.com/guendouzaimed/dirforce](url)

**Comment by zrquan** [comment]
Dirsearch can now enable asynchronous mode with `--async`, which should help improve this issue. Feel free to try it and provide feedback!
