### ISSUE TITLE
please

### ISSUE THREAD

**Issue by samuel823** [maurosoria/dirsearch#102]
can this tools run with a list of url , so that i dont need to like run a url one by one

**Comment by riramar** [comment]
#!/bin/bash
input="/path/to/txt/file"
while IFS= read -r var
do
  dirsearch.py -u "$var" -e asp,jsp,php
done < "$input"

**Comment by samuel823** [comment]
can i see ur bin/bash like how u create that , pls i really need this

**Comment by nrrpinto** [comment]
@samuel823 , you are really making noise all over the github, please don't do that, and don't be "unpolite" like you were with @drego85, he is right, you should study bash script, what you ask is very easy. 
Anyway, here it is a step by step how to get what you want( # means the bash command line of linux):

1. On the same folder where is dirsearch.py, create a file, for example: 
# touch dirsearch_various_url.sh

2. # chmod 700 dirsearch_various_url.sh

3. # vi dirsearch_various_url.sh

4. select "i" to enter insert mode inside vi and then paste the following code:
#!/bin/bash
# use dirsearch with various URLS
for url in $(cat $1); do
	./dirsearch.py -u $url -e php,jsp,asp
done

5. "esc", "wq" and "enter" -> this sequence of characters in "vi" makes you exit edit mode, save file and exit

6. create a file and add URLS:
# touch url_list.txt
# echo "www.google.pt" >> url_list.txt
# echo "www.bing.pt" >> url_list.txt

7. execute:
./dirsearch_various_url.sh url_list.txt

**Comment by maurosoria** [comment]
samuel823 reported for answering bad. Thanks nrrpinto for your detailed response. Issue closed.
