### ISSUE TITLE
how to exclude 35KB response

### ISSUE THREAD

**Issue by Teicu** [maurosoria/dirsearch#1037]
Hello, 

Often on some sites most responses is 35KB, can anyone tell me how to exclude this from scanning? 

Thank you very much 
 
<img width="581" alt="Screenshot 2022-01-27 at 16 32 29" src="https://user-images.githubusercontent.com/1572822/151379605-32405427-5646-4a69-a909-f40b198d675a.png">

**Comment by shelld3v** [comment]
You can try `--exclude-sizes 35KB`

**Comment by shelld3v** [comment]
@Teicu Did this only happen to paths start with `_` or any path?

**Comment by Teicu** [comment]
to any paths, but it seems that --exclude-sizes 35KB works perfectly, thank you very much for your answer
