### ISSUE TITLE
dirsearch install

### ISSUE THREAD

**Issue by kirtiso** [maurosoria/dirsearch#104]
hello sir,

what is command installof dirsearch on windows7??

**Comment by kirtiso** [comment]
how to use dirsearch on windows7??

**Comment by nrrpinto** [comment]
@kirtiso "dirsearch" is a python script to be used in command line. You just have to have python 3.x installed in your windows system and then execute it like any other python script. A simple example:

> python dirsearch -u \<address\> -e \<extension(s)\>

You can find all the parameters using the following:

> python dirsearch -h

**Comment by kirtiso** [comment]
hello sir,

i already installed python3.6(32 bit) and use script but still not working.

D:\dirsearch-master>python dirsearch -h
python: can't open file 'dirsearch': [Errno 2] No such file or directory

D:\dirsearch-master>python dirsearch -u <address> -e <extension(s)>
The syntax of the command is incorrect.

D:\dirsearch-master>

**Comment by drego85** [comment]
Please try with this command:

python3 dirsearch.py

**Comment by drego85** [comment]
Ok, sorry but I don't use Windows  for a long time.

Try:

python dirsearch.py -h

**Comment by kirtiso** [comment]
it's okay, but using python3 and python give error

D:\dirsearch-master>python dirsearch.py -h
Sorry, dirsearch requires Python 3.x

**Comment by drego85** [comment]
Ok, you have then started Dirsearch with python2 and not python3.

As you understood, I have no experience with Windows, but you could try:

python3.6 dirsearch.py -h

or

python36 dirsearch.py -h

If it still does not work, try looking at this guide (in the chapter "How to Install Python 3"): https://www.howtogeek.com/197947/how-to-install-python-on-windows/

**Comment by nrrpinto** [comment]
@kirtiso you should identify the location(path/folder) of your python3 installation and add it to the environment variables so it can be run across all the system.
@drego85 , i just check my windows and it is "python3"

**Comment by drego85** [comment]
Thanks @nrrpinto ;)

**Comment by kirtiso** [comment]
Thank you
Nuno Pinto

**Comment by kirtiso** [comment]
Thank you  
@nrrpinto 
@drego85 

can u tell me what is command to finding files??

python3 dirsearch.py -h   it's working but for url when i use     python3 dirsearch.py -u test.com 
it give error and what is command for json file.Please help me

**Comment by drego85** [comment]
python3 dirsearch.py -e php -u http://example.com

**Comment by nrrpinto** [comment]
@kirtiso, @drego85 just gave you a good example how to make it work.
Have in mind that you always need at least two parameters to make it work: **-u**, to define the URL of the webpage, and **-e** to define the extension of files you want to find.
If you want to find json files you should use:
`python3 dirsearch -e json -u http://example.com`
You can find diferent extension files with the following example:
`python3 dirsearch -e json,php,html,asp,aspx -u http://example.com`

**Comment by kirtiso** [comment]
Thank you sir
@nrrpinto 
@drego85

**Comment by MatiasMontanna** [comment]
I don't have this clear. But I would want a step by step explanation about how use dirsearch. I have Python 3.6. So I need to execute the code, executing dirsearch.py? I executed dirsearch.py, and a console appears but 1 second later disappers. What I can do, and, how I can use dirsearch? Explain me, step by step the use of dirsearch.

Thanks.

**Comment by maurosoria** [comment]
The command should be something like C:\Python36\python.exe dirsearch.py --help

**Comment by shelld3v** [comment]
`dirsearch.py -h` only, remove the `python3`:

```cmd
C:\Users\Shelld3v>dirsearch.py -h
Usage: dirsearch.py [-u|--url] target [-e|--extensions] extensions [options]

Options:
  -h, --help            show this help message and exit

  Mandatory:
    -u URL, --url=URL   URL target
    -L URLLIST, --url-list=URLLIST
                        URL list target
    -e EXTENSIONS, --extensions=EXTENSIONS
                        Extension list separated by comma (Example: php,asp)
    -E, --extensions-list
                        Use predefined list of common extensions

  Dictionary Settings:
    -w WORDLIST, --wordlist=WORDLIST
                        Customize wordlist (separated by comma)
    -l, --lowercase
    -f, --force-extensions
                        Force extensions for every wordlist entry (like in
                        DirBuster)

  General Settings:
    -s DELAY, --delay=DELAY
                        Delay between requests (float number)
    -r, --recursive     Bruteforce recursively
    -R RECURSIVE_LEVEL_MAX, --recursive-level-max=RECURSIVE_LEVEL_MAX
                        Max recursion level (subdirs) (Default: 1 [only
                        rootdir + 1 dir])
    --suppress-empty, --suppress-empty
    --scan-subdir=SCANSUBDIRS, --scan-subdirs=SCANSUBDIRS
                        Scan subdirectories of the given -u|--url (separated
                        by comma)
    --exclude-subdir=EXCLUDESUBDIRS, --exclude-subdirs=EXCLUDESUBDIRS
                        Exclude the following subdirectories during recursive
                        scan (separated by comma)
    -t THREADSCOUNT, --threads=THREADSCOUNT
                        Number of Threads
    -x EXCLUDESTATUSCODES, --exclude-status=EXCLUDESTATUSCODES
                        Exclude status code, separated by comma (example: 301,
                        500)
    --exclude-texts=EXCLUDETEXTS
                        Exclude responses by texts, separated by comma
                        (example: "Not found", "Error")
    --exclude-regexps=EXCLUDEREGEXPS
                        Exclude responses by regexps, separated by comma
                        (example: "Not foun[a-z]{1}", "^Error$")
    -c COOKIE, --cookie=COOKIE
    --ua=USERAGENT, --user-agent=USERAGENT
    -F, --follow-redirects
    -H HEADERS, --header=HEADERS
                        Headers to add (example: --header "Referer:
                        example.com" --header "User-Agent: IE"
    --random-agents, --random-user-agents

  Connection Settings:
    --timeout=TIMEOUT   Connection timeout
    --ip=IP             Resolve name to IP address
    --proxy=HTTPPROXY, --http-proxy=HTTPPROXY
                        Http Proxy (example: localhost:8080
    --http-method=HTTPMETHOD
                        Method to use, default: GET, possible also: HEAD;POST
    --max-retries=MAXRETRIES
    -b, --request-by-hostname
                        By default dirsearch will request by IP for speed.
                        This forces requests by hostname

  Reports:
    --simple-report=SIMPLEOUTPUTFILE
                        Only found paths
    --plain-text-report=PLAINTEXTOUTPUTFILE
                        Found paths with status codes
    --json-report=JSONOUTPUTFILE

C:\Users\Shelld3v>
```
