### ISSUE TITLE
Problem with the -L flag

### ISSUE THREAD

**Issue by neutrinoguy** [maurosoria/dirsearch#105]
Hello,

In the Latest Dirsearch version, their is a problem when using a list argument (-L) flag. Though there are valid domains in the list which resolves. Dirsearch ends showing **"Couldn't resolve DNS"** 

**Things tried**

- Tried adding "http" before the domain names and also without it. 
- cloned the repository from scratch 

**Problem on**
- macOS

Note: Dirsearch works perfectly fine on single domain (-u) flag. 

Let me know if any more information is needed.

Thanks

**Comment by IbrahimGithub** [comment]
face Same problem

**Comment by CulebraTI** [comment]
try to remove blanks at the beginning of each line

**Comment by shelld3v** [comment]
Can you retry now?
