### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by B4RD4k** [maurosoria/dirsearch#1052]
Hello Team,
I'm using the current latest version of Dirsearch on a Win10 machine,
I have the AttributeError: 'NoneType' object has no attribute 'strip' error when trying to scan some endpoint using this command.

python dirsearch.py -u "http://IP" --full-url -i 200

pyhon == python3.8

Please Help

**Comment by shelld3v** [comment]
Please provide the full traceback

**Comment by shelld3v** [comment]
Duplicate of #1023
