### ISSUE TITLE
Do not install dependencies automatically

### ISSUE THREAD

**Issue by exploide** [maurosoria/dirsearch#1060]
### What is the current behavior?

Suddenly, dirsearch automatically installs the dependencies from `requirements.txt` via pip.

### What is the expected behavior?

This is unexpected behavior. Tools usually don't do this. And there is a reason for that. Administrators and users might want to handle software dependencies in an opinionated way.

Concerning the case here, people might want to install the dependencies via Linux distribution's package management instead. Or within a virtualenv.

In the end it should be left to the user, so I kindly ask to revert this behavior.

#### Checker:
 - [x] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
@exploide If the user installs it via Linux distribution's package, the dependencies will get installed automatically in the installation process. The virtualenv seems to be a legit case, maybe check if we can find `requirements.txt` first, ff not then asks the user for manual installation?

**Comment by maurosoria** [comment]
@shelld3v what @exploide is saying is true. Can we at least ask for confirmation to install the requirements?

**Comment by maurosoria** [comment]
@exploide how you doing?

@shelld3v submitted a patch for asking before installing the dependencies.

Can you check it ?

**Comment by exploide** [comment]
I tested the patch and I think the approach is fine for me. :+1:

However, I discovered a bug with this. See the following output, where I say yes to dirsearch's automatic installation but nothing is installed via pip and the message comes again:

```console
> pip list --user

> dirsearch.py
Missing required dependencies to run.
Do you want dirsearch to automatically install them? [Y/n] Y

> pip list --user

> dirsearch.py
Missing required dependencies to run.
Do you want dirsearch to automatically install them? [Y/n] 

```

This happens if I already have all Python dependencies installed (system-wide) but in an unsuitable version.

In my example I have `python3-pyparsing-2.4.7` and `python3-markupsafe-2.0.0` installed but according to the `requirements.txt`, dirsearch needs `pyparsing>=3.0.6` and `markupsafe>=2.0.1`.

If I explicitly run `pip install -r requirements.txt` instead of dirsearch's mechanism, it installs the two dependencies in a suitable version.

So there are two points here:

1. `requirements.txt` should only list the lowest version numbers compatible with dirsearch, in case someone has a slightly lower version already installed.
2. If a higher version really needs to be installed, dirsearch's mechanism should be able to do this, instead of failing silently.

I don't know how complicated that would be. If it isn't worth the effort, maybe drop the auto install functionality and let users take care of `requirements.txt` manually, like most other projects do.

**Comment by byesec** [comment]
I also had the problem of autoinstall not responding.

`root@VM-20-17-ubuntu:~/pentest/dirsearch# pip3 install -r requirements.txt 
Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
Requirement already satisfied: PySocks>=1.7.1 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 1)) (1.7.1)
Requirement already satisfied: Jinja2>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (3.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2019.11.28)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (1.25.8)
Requirement already satisfied: cryptography>=2.8 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (2.8)
Requirement already satisfied: cffi>=1.14.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 6)) (1.15.0)
Requirement already satisfied: defusedxml>=0.7.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 7)) (0.7.1)
Requirement already satisfied: markupsafe>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 8)) (2.1.0)
Requirement already satisfied: pyopenssl>=21.0.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 9)) (22.0.0)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 10)) (2.8)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 11)) (3.0.4)
Requirement already satisfied: charset_normalizer~=2.0.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 12)) (2.0.12)
Requirement already satisfied: requests>=2.27.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 13)) (2.27.1)
Requirement already satisfied: requests_ntlm>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 14)) (1.1.0)
Requirement already satisfied: colorama>=0.4.4 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 15)) (0.4.4)
Requirement already satisfied: ntlm_auth>=1.5.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 16)) (1.5.0)
Requirement already satisfied: pyparsing>=3.0.6 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 17)) (3.0.7)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.14.0->-r requirements.txt (line 6)) (2.21)
root@VM-20-17-ubuntu:~/pentest/dirsearch# python3 dirsearch.py -h
Missing required dependencies to run.
Do you want dirsearch to automatically install them? [Y/n] y
root@VM-20-17-ubuntu:~/pentest/dirsearch# python3 dirsearch.py -h
Missing required dependencies to run.
Do you want dirsearch to automatically install them? [Y/n] y
root@VM-20-17-ubuntu:~/pentest/dirsearch# `

maybe you can check the problem。
