### ISSUE TITLE
DNS cache includes port information

### ISSUE THREAD

**Issue by mb-syss** [maurosoria/dirsearch#1065]
https://github.com/maurosoria/dirsearch/blob/24b7bc375a196de7e709edb0d16ed06fe198ef2e/lib/connection/dns.py#L25

will actually cache the port number specified (65535) and the connection will be made using that:

```
strace  -e connect ./venv/bin/python dirsearch.py -q -u https://catchall401:443/t/ --no-color -e php,aspx,jsp,html,js   --ip=172.16.50.3
connect(3, {sa_family=AF_INET, sin_port=***htons(65535)***, sin_addr=inet_addr("172.16.50.3")}, 16) = -1 EINPROGRESS (Operation now in progress)
```

I suppose that will also cause issues if connections to multiple ports on one host should be made, as the cache is keyed by hostname only.

**Comment by shelld3v** [comment]
Thanks, it's really useful
