### ISSUE TITLE
Report written after each hit

### ISSUE THREAD

**Issue by mb-syss** [maurosoria/dirsearch#1066]
### What is the current behavior?

https://github.com/maurosoria/dirsearch/blob/24b7bc375a196de7e709edb0d16ed06fe198ef2e/lib/controller/controller.py#L431

triggers a write of the report file after each hit. On hosts with a lot of hits (typically some undetected wildcard condition) this becomes **very** expensive quickly.

### What is the expected behavior?

Report will be written only once, or even better: streaming output to avoid memory usage.

### Any additional information?

OS, python version, screenshots, dirsearch command, console output, ...?

#### Checker:
 - [X] I tested in the latest version of dirsearch

May not cover all situations, but this patch appears to work as intended for me:
```diff
diff --git a/lib/controller/controller.py b/lib/controller/controller.py
index a475b0d..3dda730 100755
--- a/lib/controller/controller.py
+++ b/lib/controller/controller.py
@@ -291,6 +291,7 @@ class Controller(object):
             exit(0)
 
         finally:
+            self.report_manager.write_report()
             self.error_log.close()
 
         self.output.warning("\nTask Completed")
diff --git a/lib/core/report_manager.py b/lib/core/report_manager.py
index 8c8f101..459e418 100755
--- a/lib/core/report_manager.py
+++ b/lib/core/report_manager.py
@@ -68,7 +68,6 @@ class ReportManager(object):
     def update_report(self, report):
         if report not in self.reports:
             self.reports.append(report)
-        self.write_report()
 
     def write_report(self):
         if self.report_obj is None:
```

**Comment by shelld3v** [comment]
Hi, the purpose of the mentioned behavior is to allow users to have the report despite interrupting in the middle of the scan. The streaming idea has been thought about already but I haven't had time to do it yet

**Comment by shelld3v** [comment]
Actually I can implement a save in both the end of a scan and the case people interrupt the scan
