### ISSUE TITLE
I'm Noob But Is that Error is common ?

### ISSUE THREAD

**Issue by qutaibam0** [maurosoria/dirsearch#1068]
I'm trying to attack THM Machine and I keep getiing this error
- How can I solve it ?
┌──(kali㉿kali)-[~]
└─$ sudo dirsearch -u 10.10.131.204 -w /usr/share/wordlists/dirbuster/directory-list-lowercase-2.3-medium.txt

/usr/local/lib/python3.9/dist-packages/dirsearch-0.4.2-py3.9.egg/dirsearch/reports is a file, should be a directory

**Comment by shelld3v** [comment]
@qutaibam0 Hi please try another install option, you can find it from [here](https://github.com/maurosoria/dirsearch#installation--usage)

**Comment by shelld3v** [comment]
@qutaibam0 Can you give me the output of `cat /usr/local/lib/python3.9/dist-packages/dirsearch-0.4.2-py3.9.egg/dirsearch/reports`?

**Comment by maurosoria** [comment]
I close this issue for lack of activity.
