### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by brucelsone** [maurosoria/dirsearch#1069]
### What is the question?

对部分网站进行目录扫描直接报错，无法进行扫描。
### Any additional information?

- macOS Big Sur
- dirsearch v0.4.2
- python 3.9.9
- cmd: dirsearch -u http://www.site.com
- screenshot:
![image](https://user-images.githubusercontent.com/101378596/158336015-d825d501-285e-4535-b069-dd9c823d8ceb.png)

#### Checker:
 - [x] I read the documentation (README)

**Comment by shelld3v** [comment]
It's the issue with the servers, not dirsearch. Try replacing `http` with `https`, it might work

**Comment by brucelsone** [comment]
I've tried use the `https` to replace `http`, but still not working with my situation. 
![image](https://user-images.githubusercontent.com/101378596/161889972-c158fa09-2865-4dc1-a01e-b7c7e4c42863.png)

**Comment by shelld3v** [comment]
Then the server is probably taken down
