### ISSUE TITLE
socks5

### ISSUE THREAD

**Issue by Teicu** [maurosoria/dirsearch#1075]
Hello,  

any idea why it doesn't works socks 5?  I use _**--proxy=socks5://localhost:8085**_
 
I get always _**There was a problem in the request to: https://site.com/**_ 

Thank you

**Comment by shelld3v** [comment]
Can you give me your dirsearch version?

**Comment by Teicu** [comment]
yes, of course: 

 _~ % cd dirsearch
dirsearch % ./dirsearch.py --version
dirsearch v0.4.2.1_ 

Thanks

**Comment by shelld3v** [comment]
Please update your tool
