### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by duyu-duyu** [maurosoria/dirsearch#1077]
![image](https://user-images.githubusercontent.com/64543263/160529491-d94bad63-8954-41aa-bff6-6e328d442e0a.png)

smoething happened 

but i don't know

**Comment by shelld3v** [comment]
Try `./dirsearch.py -u http://192.168.31.253/admin --log dirsearch.log` and check the full error message inside `dirsearch.log`

**Comment by p3stR** [comment]
I have the same error. It started without any obvious reason. I downloaded separately the latest version and I am still getting the same error. 
On the logs I see that the url target cannot be parsed.

`[22-04-15 10:16:54][ERROR] GET http://127.0.0.1/
    Failed to parse: http://127.0.0.1/
`

**Comment by shelld3v** [comment]
Hi @p3stR, what is your command?

**Comment by p3stR** [comment]
> Hi @p3stR, what is your command?

I tried several arguments without luck.

Even this simple commands has the same error:

`╰─○ dirsearch --version
dirsearch v0.4.2

╰─○ dirsearch -u http://127.0.0.1
Target: http://127.0.0.1/
Invalid URL: http://127.0.0.1:80/

╰─○ python3 /opt/GITs/dirsearch/dirsearch.py --version          
dirsearch v0.4.2.4

╰─○ python3 /opt/GITs/dirsearch/dirsearch.py -u http://127.0.0.1 --log dirsearch.log
Target: http://127.0.0.1/
There was a problem in the request to: http://127.0.0.1/

╰─○ cat dirsearch.log        
[22-04-15 11:28:30][ERROR] GET http://127.0.0.1/
    Failed to parse: http://127.0.0.1/`

**Comment by shelld3v** [comment]
@p3stR Can you try `python3 -m pip install --upgrade urllib3` ?

**Comment by p3stR** [comment]
@shelld3v Sorry for the late reply. It seems that I already have the latest urllib3 version.

` python3 -m pip install --upgrade urllib3     
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (1.26.9)
`

**Comment by shelld3v** [comment]
@p3stR Can you try `sudo python3 -m pip install --upgrade urllib3`? Also, how did you install dirsearch?

**Comment by p3stR** [comment]
@shelld3v I tried with sudo too but the requirement is the same and already satisfied so nothing changed.
I have two installations, one from the kali repository (v0.4.2) and one with git clone (v0.4.2.4)

**Comment by shelld3v** [comment]
Hello @p3stR, have you been able to fix this yet?

**Comment by shelld3v** [comment]
I think the only thing that can cause this issue is an invalid **invisible** character. You should try to type it manually instead of copying it from somewhere else (if you did)

**Comment by p3stR** [comment]
Hi @shelld3v, I was getting the same error even if I was typing it manually. I have installed a new kali VM and I don't face the issue now but I was not able to fix it or find a workaround in the previous installation.

**Comment by Prady18** [comment]
Restar and full installation okay
