### ISSUE TITLE
Detect if IP is specified in URL

### ISSUE THREAD

**Issue by mrschyte** [maurosoria/dirsearch#108]
dirsearch doesn't like urls that have an IP instead of the hostname specified, e.g.: http://88.88.88.88/

Enumeration can be forced with the -b flag in this case, but it would be nice if dirsearch could detect that it doesn't need to resolve the hostname.

**Comment by sheriffsparks** [comment]
I am trying to find the issue, from what I can tell dirsearch already supports this. See relevant code in lib/connection/Requester.py:
```
# resolve DNS to decrease overhead
        if ip is not None:
            self.ip = ip
        else:
            try:
                self.ip = socket.gethostbyname(self.host)
            except socket.gaierror:
                raise RequestException({'message': "Couldn't resolve DNS"})
```

Is there something I am not understanding about this?

**Comment by mrschyte** [comment]
Thanks for looking into this. I've downloaded the latest version and I'm no longer experiencing the issue. When I've tried before, dirsearch would try to resolve the IP address as a hostname using DNS which would fail.
