### ISSUE TITLE
False positive url packs - help

### ISSUE THREAD

**Issue by DonatoReis** [maurosoria/dirsearch#1086]
### What is the question?

Hi

I'm having a hard time running dirsearch in several subdomains in my script, it appears this error below in the image.

but it also appears a lot of false positives in the urls
example: status code 301 => redirect

Please if anyone can help me solve the issue, I'm very urgent

### Any additional information?

--version Dirsearch 
v0.4.2.4
--version Python                
3.9.12

command=xargs -L1 python3 /usr/local/dirsearch/dirsearch.py -q -e php,asp,aspx,jsp,html,zip,jar -x 404-499,500-599 -w "$dicc" -t 50 --timeout 3 -o "$logfile" -u < <(httpx -silent <<< "$domain")'

--output=
<div>
<a href="https://ibb.co/BfshSxS"><img src="https://i.ibb.co/Cw0jTZT/unknown.png" alt="unknown" border="0"></a>
<a href="https://ibb.co/hY7JDdN"><img src="https://i.ibb.co/5KMgBj3/Sem-t-tulo.png" alt="Sem-t-tulo" border="0"></a>
</div>

#### Checker:
 - [ ] I read the documentation (README)

**Comment by DonatoReis** [comment]
can i test it now?  @shelld3v

**Comment by shelld3v** [comment]
The fix hasn't been merged yet, please test it when your issue is closed

**Comment by DonatoReis** [comment]
it's still giving me an error when running @shelld3v @maurosoria 

<a href="https://ibb.co/92LZKYX"><img src="https://i.ibb.co/P4nDXCp/Sem-t-tulo.png" alt="Sem-t-tulo" border="0"></a>
<a href="https://ibb.co/jD1SdSG"><img src="https://i.ibb.co/M73mbmp/reporterr.png" alt="reporterr" border="0"></a>

**Comment by shelld3v** [comment]
Hi @DonatoReis, try reducing the threads number, you might have been blocked for sending too many requests

**Comment by DonatoReis** [comment]
is there any way to increase the speed without being blocked? @shelld3v

**Comment by shelld3v** [comment]
> is there any way to increase the speed without being blocked? @shelld3v

Actually, there is a way, you can use multiple proxies to send requests (`--proxy-list`), but I don't advise you to do that because if the server doesn't want to receive too many requests it usually means the server can't handle too many requests, do it might just break the server
