### ISSUE TITLE
When starting dirsearch it print warning. How to disable it 

### ISSUE THREAD

**Issue by cyberindia1** [maurosoria/dirsearch#1087]
### What is the question?

When running dirsearch it shows me warning. 

### Any additional information?
 Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

#### Checker:
 - [ ] I read the documentation (README)

**Comment by shelld3v** [comment]
Can you run `./dirsearch.py --version` and give me the result?

**Comment by cyberindia1** [comment]
┌──(kali㉿kali)-[~/dirsearch]
└─$ ./dirsearch.py --version 
dirsearch v0.4.2.4

**Comment by shelld3v** [comment]
Can I know the command you ran? I can't reproduce your issue with the same host

**Comment by cyberindia1** [comment]
python3 diresearch.py -u https://www.example.com -e php,html, -i 200

**Comment by cyberindia1** [comment]
please delete website name contractor.de

**Comment by shelld3v** [comment]
Sorry, I have deleted it now, tho I'm still unable to reproduce the issue, do you know any host you can disclose that has the same behavior?

**Comment by cyberindia1** [comment]
└─$ python3 dirsearch.py -u https://cyberindia.co/ -i 200 -e php,html,js

  _|. _ _  _  _  _ _|_    v0.4.2.4
 (_||| _) (/_(_|| (_| )

Extensions: php, html, js | HTTP method: GET | Threads: 25 | Wordlist size: 10293

Output File: /home/kali/dirsearch/reports/cyberindia.co/__22-04-13_10-51-44.txt

Target: https://cyberindia.co/
/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cyberindia.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[10:51:47] Starting: 
/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cyberindia.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cyberindia.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cyberindia.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cyberindia.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cyberindia.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cyberindia.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/kali/.local/lib/python3.9/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'cyberindia.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

**Comment by shelld3v** [comment]
On my machine it's different

```
$ python3 dirsearch.py -u https://cyberindia.co/ -i 200 -e php,html,js

  _|. _ _  _  _  _ _|_    v0.4.2.4
 (_||| _) (/_(_|| (_| )

Extensions: php, html, js | HTTP method: GET | Threads: 25 | Wordlist size: 10293

Output File: /tmp/ds/reports/cyberindia.co/__22-04-13_21-55-26.txt

Target: https://cyberindia.co/

[21:55:28] Starting:
[                    ]  2%    223/10293         5/s       job:1/1  errors:0
```

I'm investigating more

**Comment by shelld3v** [comment]
Hi @cyberindia1, what tool did you use to run dirsearch? The one that generated your HTML report

**Comment by cyberindia1** [comment]
I am not using any other tools It's default output that dirsearch provide. I am using dirasearch for content discovery

**Comment by shelld3v** [comment]
@cyberindia1 Can you try again now? Have you fixed it?

**Comment by shelld3v** [comment]
@cyberindia1 Can you give me the output of `pip show requests` and `pip show urllib3`?

**Comment by cyberindia1** [comment]
It's fixed now

**Comment by shelld3v** [comment]
How did you fix it?
