### ISSUE TITLE
Difference between binary ??

### ISSUE THREAD

**Issue by DonatoReis** [maurosoria/dirsearch#1096]
### What is the question?

What is the difference between dirsearch from the binary and dirsearch.py from inside the folder?

### Any additional information?

Because I have issues with the binary, like a lot of shell overflow

#### Verifier:
     - [ ] Read the documentation (README)

@maurosoria @shelld3v

**Comment by shelld3v** [comment]
Can you explain more about "dirsearch from the binary"?
