### ISSUE TITLE
bash: warning: shell level (1000) too large, resetting to 1

### ISSUE THREAD

**Issue by DonatoReis** [maurosoria/dirsearch#1097]
### What is the current behavior?

shell error: too large shell warning

### What is the expected behavior?

the behavior should be informative but I can't even see the version

### Any additional information?

<a href="https://imgbb.com/"><img src="https://i.ibb.co/2qY9MPC/Sem-t-tulo.png" alt="Sem-t-tulo" border="0"></a>

#### Verifier:
   - [ ] tested on latest version of dirsearch
@maurosoria  @shelld3v

**Comment by shelld3v** [comment]
Hi I think it's not a problem with dirsearch, I can't reproduce it, you should look up on google first

**Comment by shelld3v** [comment]
You might check your "dirsearch" alias command
