### ISSUE TITLE
扫描https站点的时候无法进行，是什么原因？

### ISSUE THREAD

**Issue by TAKAHASHI7** [maurosoria/dirsearch#1098]
### What is the question?
扫描https站点的时候无法进行，是什么原因？
What do you like to ask about?
![image](https://user-images.githubusercontent.com/67530991/165424410-b70ff1aa-6131-4908-937b-8e7b794f04ff.png)

### Any additional information?

OS, dirsearch version, python version, screenshots, dirsearch command, console output, ...?

#### Checker:
 - [ ] I read the documentation (README)

**Comment by shelld3v** [comment]
It's either the server was down or you used an old version of dirsearch

**Comment by shelld3v** [comment]
要么是服务器已关闭，要么您使用的是旧版本的 dirsearch
