### ISSUE TITLE
Added to the queue: xxx/  error

### ISSUE THREAD

**Issue by kaking4** [maurosoria/dirsearch#1105]
What actually happens?
when i use     -r    ,it can make some wrong dir .One character is missing when recursively scanning
![image](https://user-images.githubusercontent.com/64488830/167297130-c0a9b54b-2e30-4d66-9461-eeefd7633442.png)

OS, python version, screenshots, dirsearch command, console output, ...?
dirsearch v0.4.2.4

**Comment by shelld3v** [comment]
What is your command?

**Comment by kaking4** [comment]
> What is your command?

python3 dirsearch.py -u https://xxxx.com -r
