### ISSUE TITLE
System wide http_proxy dirsearch fails with no finding

### ISSUE THREAD

**Issue by zsahi** [maurosoria/dirsearch#111]
I am not sure if this is an issue or a feature to be added in future.
How to reproduce issue?
mysite.com/page.php // test page to find with dirsearch
Kali linux host for dirsearch, adding system wide proxy.
vim /etc/environment
http_proxy="user:pass@IP:Port"
reboot 
and run ./dirsearch -u http://mysite.com/ -w db/mydict.txt -e php -t 1
where mydict.txt contain on 15 words, including "page","page.php"
I see no output.

System wide proxy is working fine with curl, wget

**Comment by shelld3v** [comment]
@zsahi maybe because all of them returned 404?
