### ISSUE TITLE
The output is null

### ISSUE THREAD

**Issue by mrknow001** [maurosoria/dirsearch#1110]
When -l and -o are used together, there is a certain probability that the output file will be empty.

**Comment by shelld3v** [comment]
> there is a certain probability

Do you know the required condition for that? So I can reproduce and fix it

**Comment by mrknow001** [comment]
I have tested using two urls and this problem also happened, it seems to be random, if you want to fix this bug you can only use DEBUG, sorry I can't provide more information.

**Comment by anasbousselham** [comment]
I have the same issue with -o flag and  --format=json

**Comment by shelld3v** [comment]
Can you re-try now? I made a refactor for reporting function so don't know if it still exists

**Comment by mrknow001** [comment]
![图片](https://user-images.githubusercontent.com/46807619/173352093-42f8b166-b180-4e3f-95ed-2a8841852e2a.png)

**Comment by shelld3v** [comment]
@mrknow001 Thank you for the screenshot, I have recognized the issue, will work on it right now
