### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by akashrpatil** [maurosoria/dirsearch#1111]
Getting this error while runing the dirsearch:

```Traceback (most recent call last):
  File "/root/recon/dirsearch/thirdparty/oset/pyoset.py", line 8, in <module>
    from collections import MutableSet
ImportError: cannot import name 'MutableSet' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/recon/dirsearch/dirsearch.py", line 27, in <module>
    from lib.core import ArgumentParser
  File "/root/recon/dirsearch/lib/core/__init__.py", line 1, in <module>
    from .argument_parser import *  # noqa: F401
  File "/root/recon/dirsearch/lib/core/argument_parser.py", line 29, in <module>
    from thirdparty.oset import oset
  File "/root/recon/dirsearch/thirdparty/oset/__init__.py", line 3, in <module>
    from .pyoset import oset
  File "/root/recon/dirsearch/thirdparty/oset/pyoset.py", line 11, in <module>
    from ._abc import MutableSet
  File "/root/recon/dirsearch/thirdparty/oset/_abc.py", line 11, in <module>
    raise ImportError("Use native ABC classes istead of this one.")
ImportError: Use native ABC classes istead of this one.
```

**Comment by shelld3v** [comment]
Please update your dirsearch to the latest version

**Comment by akashrpatil** [comment]
I have updated the dirsearch to the latest version but still showing the same error.

**Comment by shelld3v** [comment]
What installation method did you use? The latest version of dirsearch doesn't have `thirdparty/` folder anymore

**Comment by irshadshalu** [comment]
@shelld3v  I have the same issue. 

the installation method used is through PyPi, the version with the error is 0.4.2 (which also seems to be the latest in "releases").

**Comment by shelld3v** [comment]
Can you try to install with git? It's the best option, I will update the PyPi package soon

**Comment by irshadshalu** [comment]
@shelld3v  I was trying to use it as a module as part of another script

**Comment by irshadshalu** [comment]
@shelld3v 

I have ownership of the script. The problem here is that the latest version in Pypi is more than a year old and a new version with the latest changes on Git needs to be released.

It is ok now as I have moved on to use git installation.
