### ISSUE TITLE
how to fix "Missing required dependencies to run."?

### ISSUE THREAD

**Issue by saamnguyen** [maurosoria/dirsearch#1117]
Missing required dependencies to run.
Do you want dirsearch to automatically install them? [Y/n] y
Installing required dependencies...
Failed to install dirsearch dependencies, try doing it manually.

**Comment by zhibx** [comment]
Solution：python pip install -r requirements.txt

If you use python3.7.0 get this error【cannot import name 'cached_property' from 'functools'】.

can try to use python3.8.* fix it.

**Comment by shelld3v** [comment]
Thanks @zhibx

**Comment by Teicu** [comment]
Hi, still not works 

_Missing required dependencies to run.
Do you want dirsearch to automatically install them? [Y/n] y
Installing required dependencies...
Failed to install dirsearch dependencies, try doing it manually.
xd@Pentest dirsearch % git pull
Already up to date._

pip3 install -r requirements.txt 


_Installing collected packages: urllib3, soupsieve, PySocks, pyparsing, pycparser, ntlm_auth, markupsafe, idna, defusedxml, colorama, chardet, certifi, requests, Jinja2, cffi, beautifulsoup4, cryptography, requests_ntlm, pyopenssl
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
raider 0.1.3 requires importlib-metadata<5.0.0,>=4.6.1, which is not installed.
Successfully installed Jinja2-3.1.2 PySocks-1.7.1 beautifulsoup4-4.11.1 certifi-2022.6.15 cffi-1.15.1 chardet-5.0.0 colorama-0.4.5 cryptography-37.0.4 defusedxml-0.7.1 idna-3.3 markupsafe-2.1.1 ntlm_auth-1.5.0 pycparser-2.21 pyopenssl-22.0.0 pyparsing-3.0.9 requests-2.28.1 requests_ntlm-1.1.0 soupsieve-2.3.2.post1 urllib3-1.26.11_

**Comment by shelld3v** [comment]
Enter `n`

**Comment by nitzicuile** [comment]
1. Install dirsearch, git example:
`$ git clone https://github.com/maurosoria/dirsearch.git --depth 1`

2. Create [virtual environment](https://docs.python.org/3/tutorial/venv.html) and activate it:
`$ python3 -m venv environment_name`
`$ source environment_name/bin/activate`
_to deactivate: $ deactivate_

3. Install requeriments (dependencies)
`$ pip install -r requeriments.txt`

4. Try dirsearch.py
`$ python3 dirsearch.py -u URL`

**Comment by Kohwceng** [comment]
is it still work ? i try it and stuck at "failed to install dirsearch dependencies, try doing it manually."

**Comment by aaryaa-bydh** [comment]
As @nitzicuile said you have to first create a virtual environment and then activate it... but there is a correction... @nitzicuile wrote the requirements spelling wrong if you notice...

The Right command will be 

`pip install -r requirements.txt`
