### ISSUE TITLE
cannot run dirsearch, error with "AttributeError"

### ISSUE THREAD

**Issue by nikkolee** [maurosoria/dirsearch#1120]
The error shows in below when I run dirsearch

nikkolee@SHAOFFLAP358:/usr/local/bin$ dirsearch
Traceback (most recent call last):
  File "/usr/local/bin/dirsearch", line 33, in <module>
    sys.exit(load_entry_point('dirsearch==0.4.2.4', 'console_scripts', 'dirsearch')())
  File "/usr/local/bin/dirsearch", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 173, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'dirsearch.dirsearch' has no attribute 'Program'

All requirements have been installed. May I know what is the root cause?

### Any additional information?

Ubuntu 18.04
python 3.10.4
dirsearch 0.4.2.4

**Comment by shelld3v** [comment]
Hi, can you try to install dirsearch with git instead of kali repo? It will give you the latest version

**Comment by shelld3v** [comment]
Old bug, please re-pull the repo, closing now

**Comment by shelld3v** [comment]
UPDATE: it's not an old bug, but it was fixed
