### ISSUE TITLE
The last result is not included in the output

### ISSUE THREAD

**Issue by Arne-He** [maurosoria/dirsearch#1123]
### What is the current behavior?

When running python3 dirsearch.py --url=\<url\> the endmost search result is missing in the output file. However, on the command line the output is correct.

### What is the expected behavior?

All search results should be included in the output file. The results in the output file should be equal with the command line results.

#### Checker:
 - [ x] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
Hi @Arne-He, thank you for your report, can you give me your dirsearch command?

**Comment by Arne-He** [comment]
For testing purposes I am running a local webserver. in its root directory I created the files `0.html`, `1.html` and `2.html `.
My wordlist contains the following content:

```
0.html
1.html
2.html
```

When running

`dirsearch.py --format plain -o out.txt -w wordlist.txt -u localhost`

a random one of these html files is missing in the output file.
