### ISSUE TITLE
The latest released version is almost a year old.

### ISSUE THREAD

**Issue by irshadshalu** [maurosoria/dirsearch#1125]
### What is the current behavior?

The version of libsearch on PyPi is at least an year old which is missing a lot of recent bug fixes and improvements from last 1 year.

### What is the expected behavior?

The latest stable code should be released in PyPi

### Any additional information?

This is throwing an error when used with Python 3.10

#### Checker:
 - [x] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
It's not a bug, I will update it when dirsearch makes a new release
