### ISSUE TITLE
AttributeError: module 'dirsearch.dirsearch' has no attribute 'Program'

### ISSUE THREAD

**Issue by 866666** [maurosoria/dirsearch#1130]
Traceback (most recent call last):
  File "C:\Users\shang\anaconda3\envs\py38\Scripts\dirsearch-script.py", line 33, in <module>
    sys.exit(load_entry_point('dirsearch==0.4.2.6', 'console_scripts', 'dirsearch')())
  File "C:\Users\shang\anaconda3\envs\py38\Scripts\dirsearch-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\shang\anaconda3\envs\py38\lib\importlib\metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'dirsearch.dirsearch' has no attribute 'Program'
windows 11；
python 3.8；
git clone

**Comment by 189169** [comment]
in python 3.8
pip3 install dirsearch
sucess

**Comment by shelld3v** [comment]
It seems like an old issue, can you try uninstalling dirsearch with pip and re-installing it with git or zip file?

**Comment by deargle** [comment]
It's coming from here: https://github.com/maurosoria/dirsearch/blob/master/setup.py#L30

Happens when trying to run from the easy_install-created entry-script

**Comment by shelld3v** [comment]
@deargle do you know how to fix it?

**Comment by deargle** [comment]
Negative, I was just adding crumbs. I would have to dig into easy_install probably.

**Comment by shelld3v** [comment]
Duplicate of #1120
