### ISSUE TITLE
Unable to install rust

### ISSUE THREAD

**Issue by kishu62000-H** [maurosoria/dirsearch#1131]
Could not find a version that satisfies the requirement Rust>=1.41.0 (from versions: 0.1.0, 0.1.1)
ERROR: No matching distribution found for Rust>=1.41.0
![Screenshot_2022-06-24-22-01-42-553_com termux](https://user-images.githubusercontent.com/107880439/175581167-b8b9211f-1230-4fd1-a43d-21a134032739.jpg)

**Comment by shelld3v** [comment]
Hi, it's not an issue with dirsearch, please consider running the tool from a computer
