### ISSUE TITLE
Flashback occurs after using dirsearch

### ISSUE THREAD

**Issue by JeakinsCheung** [maurosoria/dirsearch#1134]
What is the reason for the error when using dirseach

The cmd window will flash back after starting the scan
![image](https://user-images.githubusercontent.com/57223351/177755144-09965605-2f55-4b9b-86ec-a2d1f7a8132b.png)

**Comment by shelld3v** [comment]
The error message is in chinese, so it's not a dirsearch error neither I can understand it
