### ISSUE TITLE
Not validating installed dependencies though installed

### ISSUE THREAD

**Issue by hsagnik** [maurosoria/dirsearch#1135]
### What is the current behavior?
Suddenly, dirsearch automatically installs the dependencies from `requirements.txt` via pip.

### What is the expected behavior?
Though the previous https://github.com/maurosoria/dirsearch/pull/1063 fix is good but not enough because it still asks to install the dependencies even after installing once again. The tool is not validating the installed dependencies however it should.

In the end the user should not be asked once the dependencies are installed.

#### Checker:
 - [X] I tested in the latest version of dirsearch

**Comment by maurosoria** [comment]
I've experienced the same issue. @shelld3v any clue?

**Comment by maurosoria** [comment]
BTW, @hsagnik  I recommend you use the docker build instead of installing it manually. At least for the moment, until Python 3.9 implementation gets mainstream in linux distros.

**Comment by shelld3v** [comment]
@hsagnik Sorry I'm trying to understand your statement here. So the problem here is that you had installed the dependencies but dirsearch reported it as missing, right? I might need some info about your system and environment if you don't mind

**Comment by hsagnik** [comment]
Absolutely @shelld3v moreover it is asking again and again for the same even the dependencies are installed already. Sure, I am happy to help you further.

**Comment by shelld3v** [comment]
Thank you for your information @hsagnik. I'm thinking about 2 solutions: improving the dependencies check or allowing users to run dirsearch with missing dependencies (save the option in the future). I'm approaching the first one, so I will need your system and environment information, later if we fail, I will have to do the second option

**Comment by hsagnik** [comment]
Here is the information on the systems I tested:

- [X] Ubuntu 22.04 LTS x86_64
- [X] Ubuntu 20.04 LTS x86_64
- [X] Kubuntu 22.04 LTS x86_64

The installed version of python:
- 3.10.4
- 3.8.5
- 3.10.4

**Comment by maurosoria** [comment]
Was this issue resolved?

**Comment by hsagnik** [comment]
Yes @maurosoria the issue is resolved. Thanks to @shelld3v for helping :)
