### ISSUE TITLE
Permission error for output file.

### ISSUE THREAD

**Issue by diego23123** [maurosoria/dirsearch#1149]
### Why am I getting permission issue for output file while running under a user?

I tried to run dirsearch under a user and tried to store the output in a file, but it says permission denied, may I know how to fix that?

When I run it using sudo it works fine.

Versions: linux, dirsearch v0.4.2

### Command:
dirsearch -u 192.168.1.171 -e php -o dirsearch1.txt 

#### Checker:
 - [x] I read the documentation (README)

**Comment by shelld3v** [comment]
Try `sudo chmod 775 '[your output directory]'`
