### ISSUE TITLE
PlainTextReport output using -L only reports last target

### ISSUE THREAD

**Issue by jr-johnson** [maurosoria/dirsearch#115]
I'm using dirsearch with a list of URLs and the -L flag. I'm attempting to output results using:
--plain-text-report=/root/Desktop/dirsearch-allurls-out.txt

After everything runs properly and finishes, the output file only contains information for the last target in a list of ~20.

**Comment by maurosoria** [comment]
The location where batch reports are located is generated when the tool starts (there is a label where the path is).

If you want to specify report types in combination with batch reports through command line, you can use the "default.conf" configuration file.
