### ISSUE TITLE
“--suffixes” seems doesn't work.

### ISSUE THREAD

**Issue by 7Mitu** [maurosoria/dirsearch#1161]
![bugdir](https://user-images.githubusercontent.com/30004765/182062873-7db85294-7645-438d-babb-f77e73bd4316.png)

**Comment by shelld3v** [comment]
That's not how `--suffixes` works, `--suffixes` just helps you append the suffixes to the end of entries in your wordlist. Do those paths exist or not? In this case, no, it has nothing to do with the feature itself. Please read carefully the README!

**Comment by 7Mitu** [comment]
I thought it was overwriting.My fault.
If I want to scan only changed entries, what should I do?
Pls tell me ,thx.

**Comment by shelld3v** [comment]
I think the behavior has been changed in my recent updates, try updating your tool!
