### ISSUE TITLE
-e aspx

### ISSUE THREAD

**Issue by nrrpinto** [maurosoria/dirsearch#117]
Hi,

I was following an write-up to hack a machine, and this write up uses another tools like dirsearch. In the write up, a file "transfer.aspx" is found. 
But when i use dirsearch exactly with the same word list, it didn't found the file.
The command I executed is:
> dirsearch -u 10.10.10.93 -e aspx -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -t 30

The list I am using has the word "transfer", but dirsearch doesn't find the file...

**Comment by maurosoria** [comment]
Try appending the -f switch.

dirsearch -u 10.10.10.93 -e aspx -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -t 30 **-f**

**Comment by nrrpinto** [comment]
Hi @maurosoria ,

I was not aware of this parameter, I though that it always try all the extensions.
I just try it and it does work correctly now.

Thanks.
