### ISSUE TITLE
exclude_status_codes not work

### ISSUE THREAD

**Issue by HyWell** [maurosoria/dirsearch#1173]
### What is the current behavior?
exclude_status_codes not work
What actually happens?
exclude_status_codes not work
### What is the expected behavior?
exclude_status_codes work
What it should be instead?
exclude_status_codes work
### Any additional information?
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/21263451/186054770-73eec458-6fbc-42d7-8588-ae1ba5a5dca9.png">

OS, python version, screenshots, dirsearch command, console output, ...?

#### Checker:
 - [ ] I tested in the latest version of dirsearch

**Comment by maurosoria** [comment]
Hello @HyWell , I've merge a @shelld3v's fix. Can you update and tell us how it works?

**Comment by HyWell** [comment]
not work
<img width="466" alt="image" src="https://user-images.githubusercontent.com/21263451/186796989-90507bda-9579-4d5b-bebe-7da45573f1f9.png">
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/21263451/186797092-b4047104-73ea-4061-8f72-7e08debd7ec6.png">

`
dirsearch/lib/core/fuzzer.py", line 203, in is_excluded
resp.status in self.blacklists
AttributeError: 'Fuzzer' object has no attribute 'blacklists'`

**Comment by shelld3v** [comment]
Thanks for reporting, that's another issue, I opened #1183 for it
