### ISSUE TITLE
a bug about recursive

### ISSUE THREAD

**Issue by turn1tup** [maurosoria/dirsearch#118]
Hello,I find a bug.

if my wordlist is:
/admin/
test.php

And I use -r options to do a recurisve scan,It will have a error。
because of this
>>> from urllib import parse
>>> parse.urljoin("http://192.168.237.136","//admin/")
'http://admin/'

so I recommend add code before line 127 " url = urllib.parse.urljoin(url, self.basePath)"  of https://github.com/maurosoria/dirsearch/blob/master/lib/connection/Requester.py

                while True:
                    path_tmp = self.basePath.replace('//', '/')
                    if path_tmp == self.basePath:
                        break
                    self.basePath = path_tmp

thank you !

**Comment by hakluke** [comment]
I am not able to reproduce this error. Could you please provide a screenshot @turn1tup ?

```
$ echo "/admin/
> test.php" > /tmp/test.txt
$ dirsearch -w /tmp/test.txt -e txt -u google.com

 _|. _ _  _  _  _ _|_    v0.3.8
(_||| _) (/_(_|| (_| )

Extensions: txt | Threads: 10 | Wordlist size: 2

Error Log: /home/luke/Public/tools/dirsearch/logs/errors-19-05-29_12-57-42.log

Target: google.com

[12:57:43] Starting: 

Task Completed
```

**Comment by shelld3v** [comment]
@turn1tup Did you really receive that error or you just guest that from the code?
