### ISSUE TITLE
AttributeError: 'Fuzzer' object has no attribute 'blacklists'

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#1183]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/21263451/186796989-90507bda-9579-4d5b-bebe-7da45573f1f9.png">
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/21263451/186797092-b4047104-73ea-4061-8f72-7e08debd7ec6.png">

```
  dirsearch/lib/core/fuzzer.py", line 203, in is_excluded
    resp.status in self.blacklists
AttributeError: 'Fuzzer' object has no attribute 'blacklists'
```

_Originally posted by @HyWell in https://github.com/maurosoria/dirsearch/issues/1173#issuecomment-1227915938_

**Comment by kpomeroy1979** [comment]
I'm experiencing the exact same issue. When I use dirsearch.py with the --proxy option.

**Comment by B4RD4k** [comment]
Also happening at my end

Please fix it

**Comment by kpomeroy1979** [comment]
I put the exact command you should run to apply the temporary fix.

**Comment by qianque** [comment]
i have this error too,please fix it

**Comment by shelld3v** [comment]
> Also happening at my end
> 
> Please fix it

The fix is waiting for approval, you can check out @kpomeroy1979 suggestion for an immediate fix
