### ISSUE TITLE
Keyboard interruption doesn't stop threads that were caused by crawling

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#1187]
### What is the current behavior?

In `/lib/core/fuzzer.py`, [new crawls (`Fuzzer.scan` session) are started in `Fuzzer.scan`](https://github.com/maurosoria/dirsearch/blob/a0c5f5dc2c2116a24178aa98e8d55602f47754ff/lib/core/fuzzer.py#L186), but [`play_event` is only checked in `Fuzzer.thread_proc`](https://github.com/maurosoria/dirsearch/blob/a0c5f5dc2c2116a24178aa98e8d55602f47754ff/lib/core/fuzzer.py#L249); therefore, dirsearch will keep starting new crawls for pages even if the user interrupts it

### What is the expected behavior?

Move `play_event` check to `Fuzzer.scan`

#### Checker:
 - [x] I tested in the latest version of dirsearch

**Comment by maurosoria** [comment]
What about this? We want to fix that or is aleady fixed?

**Comment by shelld3v** [comment]
> What about this? We want to fix that or is aleady fixed?

I don't remember fixing this, probably not fixed yet

**Comment by maurosoria** [comment]
IMO we should start by separating the Crawl function to another module of the application. Also I like to have the possibility of differen crawl implementations. Then we should feed the Crawler with discovered endpoints, create a thread, and there manage the keyboard input output.
