### ISSUE TITLE
求教为什么我更新到最新版本后，扫描时无任何回显，所有网站都一样

### ISSUE THREAD

**Issue by SaltNego** [maurosoria/dirsearch#1192]
### What is the question?
求教为什么我更新到最新版本后，扫描时无任何回显，所有网站都一样
What do you like to ask about?
![image](https://user-images.githubusercontent.com/19511250/188528858-156bd944-44f6-4a8d-940e-d0aee757b1ac.png)

**Comment by shelld3v** [comment]
Duplicate of #1190
