### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.core'

### ISSUE THREAD

**Issue by Peter128** [maurosoria/dirsearch#1198]
下载dirsearsch后解压针对 requirements.txt里面的包进行安装后。执行python dirsearch.py 报错：
![image](https://user-images.githubusercontent.com/12481595/189790827-31b91cb0-e25f-48ca-849f-05a5a66e9856.png)
网上找了很多方法试了都没有用。是那里还需要设定么？python版本：3.10.6

**Comment by shelld3v** [comment]
Try: `pip uninstall lib`

**Comment by Peter128** [comment]
> 尝试：`pip uninstall lib`

卸载之后又报错：'ModuleNotFoundError: No module named 'lib'

**Comment by 4b3j** [comment]
For `pip3 install lib` or `pip install lib`

**Comment by shelld3v** [comment]
> For `pip3 install lib` or `pip install lib`

That won't fix the issue, instead it will cause another issue

**Comment by 4b3j** [comment]
What issue is caused when you install the `lib` library

**Comment by 4b3j** [comment]
If the issue keep happening, you can try uninstalling python and all packages. Then do a reinstall, what os are you running on? 
Did you run `pip install -r requirements.txt`

**Comment by shelld3v** [comment]
Doesn't seem to be an issue with dirsearch, closing this
