### ISSUE TITLE
[Feature] Add capability to resume

### ISSUE THREAD

**Issue by Hritik14** [maurosoria/dirsearch#120]
It'd be really nice if the script could be terminated and resumed at a later time.

**Comment by BitTheByte** [comment]
You can resume it actually. 
During your scan press `CTRL+C` this will pause the scanning and later you can resume it
![](https://i.ibb.co/WGzttgK/Capture.png)

**Comment by Hritik14** [comment]
What I meant is, something like pause. Shutdown PC. Resume later.

**Comment by rudrasingh99** [comment]
Hi @maurosoria , How are you planning to achieve this?
