### ISSUE TITLE
There was a problem in the requests to : http://……

### ISSUE THREAD

**Issue by soldierbro** [maurosoria/dirsearch#1202]
### What is the current behavior?

v0.4.2.8版本，有的url不能扫描，提示There was a problem in the requests to : http://……
同一个url在v0.3.9可以正常扫描

![微信图片_20220923090022](https://user-images.githubusercontent.com/26686160/191875590-a2772f92-ef5c-4167-a3fd-d458f7529666.png)
![微信图片_20220923090311](https://user-images.githubusercontent.com/26686160/191875594-5bb670bc-e4a9-4f2d-8a38-f7a90460bdb9.png)

**Comment by shelld3v** [comment]
您可以尝试运行相同的命令，但使用 `--log debug.log` 并检查 `debug.log`？

**Comment by crazyMarky** [comment]
我遇到了相同的问题，请问已经有解决方案了吗？

**Comment by shelld3v** [comment]
> 我遇到了相同的问题，请问已经有解决方案了吗？

如果你能把 URL 发给我测试会很有用

**Comment by crazyMarky** [comment]
> > 我遇到了相同的问题，请问已经有解决方案了吗？
> 
> 如果你能把 URL 发给我测试会很有用
https://pipeline8.com 有CDN

**Comment by crazyMarky** [comment]
> > 我遇到了相同的问题，请问已经有解决方案了吗？
> 
> 如果你能把 URL 发给我测试会很有用

dirsearch v0.4.3

**Comment by crazyMarky** [comment]
大佬，这个问题有解决办法了吗？

**Comment by shelld3v** [comment]
对不起，我目前正在休息（农历新年），我会尽快查看

**Comment by YangYongbinF** [comment]
临时缓解措施：
修改dirsearch-master\lib\connection\response.py 49行
response.encoding or DEFAULT_ENCODING, errors="ignore"
为
"utf-8", errors="ignore"

**Comment by kksty** [comment]
查看你是否挂了代理

**Comment by tonmonkey** [comment]
![image](https://github.com/maurosoria/dirsearch/assets/84943423/b0e7dc22-1470-4cce-ae84-6483e808b6c5)
you有解决办法了吗~~

**Comment by xk-mt** [comment]
> ![图像](https://private-user-images.githubusercontent.com/84943423/320752008-b0e7dc22-1470-4cce-ae84-6483e808b6c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDY3NzEsIm5iZiI6MTcxMjY0NjQ3MSwicGF0aCI6Ii84NDk0MzQyMy8zMjA3NTIwMDgtYjBlN2RjMjItMTQ3MC00Y2NlLWFlODQtNjQ4M2U4MDhiNmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA3MDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MzgwZTkxYWVmYzFkYTdjOTQ0ZmJlYTQxZWVhZTJmMjY0ZTM3Y2IzNTBlNzkxZGY0MTAyM2NjNWIzOTc1ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HzJCzAjgGaVQU5Zzz3ulcR-kJDXVvIwE5FKOMAbw0Ok) 你有解决办法了吗~~

no,我没解决

**Comment by tonmonkey** [comment]
我换了一个ip重新跑了一下，正常运行，应该是之前的ip被waf封了…………

**Comment by LiQlqlqlq** [comment]
挂代理可以解决

**Comment by Blaco26** [comment]
您好burp代理可以将的详细一些吗，因为扫描路径不是通过浏览器访问，不是很明白应该怎么操作
