### ISSUE TITLE
Recursively scan directories that were found via web crawling

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#1209]
### What is the feature?

We should add directories/sub-directories that are contained in paths, found via crawling to the recursion queue no matter whether those paths are wildcard or not. Maybe an optional argument?

### What is the use case?

Sometimes we find files (paths to files) in the response that are no longer there, maybe they were deleted, but the folders/directories still exist and might contain something interesting

**Comment by Prady18** [comment]
Okay just try 👽👽
