### ISSUE TITLE
Wordlist size increment

### ISSUE THREAD

**Issue by Shadow1221a** [maurosoria/dirsearch#1214]
Word list size increment to fetch more hidden files using path traversal

**Comment by shelld3v** [comment]
Can you give me example?

**Comment by Shadow1221a** [comment]
CONSUMER_KEY
CONSUMER_SECRET
plugins
filesystem


i used this consumer_key in my recon process it helped me

**Comment by shelld3v** [comment]
@Shadow1221a You want to add those words to the wordlist or what?

**Comment by Shadow1221a** [comment]
@shelld3v yes

**Comment by shelld3v** [comment]
You can always open a PR for it (edit `db/dicc.txt`, that's the default wordlist, make sure you keep it sorted)
