### ISSUE TITLE
Couldn't create report folder at reports/

### ISSUE THREAD

**Issue by Studentz80** [maurosoria/dirsearch#1215]
Hi, I ran dirsearch and this error pops out

![image](https://user-images.githubusercontent.com/76755784/195240405-7c5bbe8c-af1f-4cab-baba-e075ae18e920.png)

The reports folder does exist btw

Is there any way we can resolve this? Any help is appreaciated. Thanks

**Comment by shelld3v** [comment]
It doesn't seem to be an issue from dirsearch. Try creating `reports/` manually

**Comment by hosainxade** [comment]
This is work:
1. rm -rf reports
2. dirsearch -u yoursite
:)))

**Comment by Dyst0rti0n** [comment]
I believe this means you don't have privileges such as using dirsearch within root folder, or alternatively you could run ~ sudo dirsearch.
