### ISSUE TITLE
Skip HTTPS certificate validation

### ISSUE THREAD

**Issue by cl0se2U** [maurosoria/dirsearch#1225]
Hoped that the next version can be implemented to skip https certificate verification function

**Comment by shelld3v** [comment]
Can you give me an example? Cause dirsearch always skips HTTPS certificate validation

**Comment by cl0se2U** [comment]
Sometimes we need to scan for sites with the expired ssl, but a direct request will return a certificate error, in which case we may need to skip the authentication.Just like this:







醉月居士
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "maurosoria/dirsearch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月25日(星期二) 晚上10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [maurosoria/dirsearch] Skip HTTPS certificate validation (Issue #1225)





 
Can you give me an example? Cause dirsearch always skips HTTPS certificate validation

**Comment by cl0se2U** [comment]
> 

The pictrue is lost....

**Comment by shelld3v** [comment]
@cl0se2U Can you resend the image? I can't see anything

**Comment by cl0se2U** [comment]
![image](https://user-images.githubusercontent.com/83335402/198025475-431e5ebb-6330-4dd9-9c98-9779562f007a.png)

**Comment by shelld3v** [comment]
I believe we have already done that, can you give me an example target?

**Comment by cl0se2U** [comment]
> I believe we have already done that, can you give me an example target?

All right, I try to reinstall the libs and it fixed. But sometimes I scaned some sites with the ssl missed, dirsearch will return the error, maybe i will try to reinstall the lib to fix it next time.
