### ISSUE TITLE
Start time in output file is incorrect

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#1233]
### What is the current behavior?

When generating the report template, we run `time.ctime()` to get the start time; however, we re-generate the template every time we receive a new result, therefore the information about the start time is refreshed continuously and inaccurate

### What is the expected behavior?

Save the start time in a variable and keep reusing it, or maybe refactor the reporting approach?

**Comment by maurosoria** [comment]
What about this ?

**Comment by shelld3v** [comment]
I have a local work of a PR that will fix this so don't worry
