### ISSUE TITLE
安装依赖库时报错

### ISSUE THREAD

**Issue by jinzezhi** [maurosoria/dirsearch#1235]
![image](https://user-images.githubusercontent.com/93123422/199879336-f771871a-3419-46bd-88b9-6255aff1c0d0.png)
安装依赖库时报这个错误，然后再使用pip就不能用了 一直报错如下图
![image](https://user-images.githubusercontent.com/93123422/199879425-9ada9bdf-95f2-41cb-8137-44837e8657f6.png)

**Comment by shelld3v** [comment]
Check this: https://github.com/pyca/pyopenssl/issues/1154

This comment recommended a solution: https://github.com/pyca/pyopenssl/issues/1154#issuecomment-1269882738
