### ISSUE TITLE
recursive scan does not work with custom wordlists

### ISSUE THREAD

**Issue by Splint3r7** [maurosoria/dirsearch#124]
Hello,

I think this issue doesn't report before, recursive scan with switch -r doesn't seems to work with the custom wordlist and throws error `Fatal error during site scanning: CONNECTION TIMEOUT: There was a problem in the request to nns5Oe0wd41c`, I have already tried --request-by-hostname switch  (-b) still it does not work and on the default wordlists it works fine.

```
root@redacted:~/tools/dirsearch# python3 dirsearch.py -e php -r -u http://redacted.com --threads 30 -w /root/tools/dirsearch/wordlists/common.txt

 _|. _ _  _  _  _ _|_    v0.3.8
(_||| _) (/_(_|| (_| )

Extensions: php | Threads: 30 | Wordlist size: 4595
Target: http://redacted.com
[00:43:17] Starting: 
[00:43:22] 200 -    3KB - /staging/
[00:43:22] 200 -    3KB - /testing/
[00:43:53] 200 -  214B  - /crossdomain.xml
[00:44:04] 200 -    1KB - /favicon.ico
[00:44:50] 200 -   25B  - /robots.txt
[00:44:59] 200 -    3KB - /staging
[00:45:00] 200 -   81B  - /status
[00:45:05] 200 -    3KB - /testing
[00:45:21] Starting: /staging/
Fatal error during site scanning: CONNECTION TIMEOUT: There was a problem in the request to: nns5Oe0wd41c
```

Please let me know If I am doing any mistake or is there any way to fix this,

**Comment by maurosoria** [comment]
Are you using the "release" version or the latest github commit?

**Comment by Splint3r7** [comment]
I have cloned the latest GitHub commit from `https://github.com/maurosoria/dirsearch`!

**Comment by manasmbellani** [comment]
Hi, 
I have come across this issue too. In my case, I have used both the latest cloned repo code and the the released version - in both cases, if a custom wordlist is specified, then recursive does not work. Here is an example command I have run which can be used to replicate the issue:

```
./dirsearch.py -u https://<target> -x 401,403 --random-agents -r -R4 -F -E -w /usr/share/dirb/wordlists/small.txt --plain-text-report=out-http-dirsearch-paths.txt
```
After the first round, the output just shows `Task completed` and does not go through the second round.

**Comment by shelld3v** [comment]
Hi, for the problem what @Splint3r7 faced, it caused not because of the recursion function, it's because of the server (Connection timeout). About @manasmbellani, the recursion won't work if you set the `-F` (follow redirect). It's also supposed to be `-R 4`, not `-R4`

**Comment by shelld3v** [comment]
Please close this!
