### ISSUE TITLE
At first, it should check whether the pip is installed or not before doing the automated installation of dirsearch dependencies

### ISSUE THREAD

**Issue by pwnb0y** [maurosoria/dirsearch#1246]
### What is the current behavior?
  The current behavior is to throw an exception if any fault is found on the install_dependencies() function

### What is the expected behavior?
 It should check whether the pip is installed or not before doing the automated installation of dirsearch dependencies.
If the pip is not installed then install the pip first or suggest the user install it.

**Comment by pwnb0y** [comment]
If it is the stuff that can be implemented in dirsearch then please let me know I want to work on it.

**Comment by shelld3v** [comment]
Great catch, and yes you can work on it if you want, I really appreciate that

**Comment by pwnb0y** [comment]
Thanks @shelld3v I will do my best 😊
