### ISSUE TITLE
Directory /home/kaliuser/dirsearch is not writable

### ISSUE THREAD

**Issue by Archurcl4w** [maurosoria/dirsearch#1252]
Hello I really appreciate for bringing this amazing tool dirsearch .  I don't have any issues running dirsearch so far but recently I had this issue- Directory /home/kaliuser/dirsearch is not writable . Its not possible to run it due to this issue  I am not having any idea how does it happens. so suddenly.  When I check the permissions the ownership of dirsearch directory, it is root ??? !!!! When adding sudo command it works but that is not usually done by every persons whoever use this tool. Something still not right. Even try to change ownership with sudo chown  kaliuser /home/kaliuser/dirsearch is not working.  After this can  it can run without sudo command and try to safe the output:-
Output File: /home/kaliuser/example_report.txt  
"Couldn't create the error log. Try running again with highest permission" 
Any help please.

**Comment by shelld3v** [comment]
You can disable log file via `config.ini` or change the permission of `/home/kaliuser/dirsearch`

**Comment by Archurcl4w** [comment]
Thanks . Its fixed by this command  `sudo chown -R  kaliuser /home/kaliuser/dirsearch`
Its just the first  time I came to experience such permissions issues but it should not be . It will be even great if dirsearch performance and speed improves while doing scan over a large  list of hosts or subdomains.  I close this thread.
