### ISSUE TITLE
The scan timed out and an error was reported

### ISSUE THREAD

**Issue by huan-cdm** [maurosoria/dirsearch#1253]
### What is the current behavior?
stuck

What actually happens?
Run single scan and batch scan, program stuck，An error，RecursionError: maximum recursion depth exceeded while calling a Python object。

### What is the expected behavior?
The URL is automatically discarded when a single URL or a batch URL times out, or the timeout period of a single URL is set when a batch scan is performed.

What it should be instead?

### Any additional information?

Screenshots, dirsearch log, dirsearch version, used command, ...?
![1670144259417](https://user-images.githubusercontent.com/55235301/205482542-62685e55-7e9d-4780-8ff6-020ae1406fea.jpg)

**Comment by huan-cdm** [comment]
10/5000 
Scan the URL that timed out the test：http://vogfi.hopeloveline.com/，The version is v0.4.3.

**Comment by shelld3v** [comment]
@huan-cdm Can you give me the output of `dirsearch.py --version`?

**Comment by maurosoria** [comment]
Closing this for no answers from the reporter.

**Comment by shelld3v** [comment]
@huan-cdm I think it's a bug with difflib 🤷‍♂️
