### ISSUE TITLE
not work in path

### ISSUE THREAD

**Issue by netwons** [maurosoria/dirsearch#1260]
python3 dirsearch.py -u http://roadrunner.indeed.com:8080
but not work

**Comment by shelld3v** [comment]
It's because http://roadrunner.indeed.com:8080/ is not an accessible HTTP service, you can try visiting it from your browser

**Comment by shelld3v** [comment]
The error that dirsearch faced was `Timeout error`, you can try increasing the timeout (via `--timeout` flag) to continue brute-forcing
