### ISSUE TITLE
dicc.txt repeat

### ISSUE THREAD

**Issue by jksxsdy** [maurosoria/dirsearch#1270]
new dicc.txt repeat:
line 6627 **ocp.php** & line 9521 **ocp.php**
line 9495 **xprober.php** & line 9520 **xprober.php**

**Comment by shelld3v** [comment]
Nice finding :) Would you like to submit a PR for it?

**Comment by jksxsdy** [comment]
tranks bro u can update the dicc.txt. ;-)

**Comment by shelld3v** [comment]
> tranks bro u can update the dicc.txt. ;-)

Well, okay:)
