### ISSUE TITLE
怎么才能扫描非443端口的https网站？How can I scan non-port 443 https websites?

### ISSUE THREAD

**Issue by crazyMarky** [maurosoria/dirsearch#1272]
### What is the question?

What do you like to ask about?
我的目标网站是https协议，但是端口不是443，例如8443，请问如何扫描？目前使用0.4.2都无法扫描。
My target website is https protocol, but the port is not 443, how to scan? Currently using 0.4.2 can not scan.

**Comment by Prady18** [comment]
U us in nmap command and confirm tha port

**Comment by crazyMarky** [comment]
> U us in nmap command and confirm tha port

Thanks for your response. I can confirm that the port of the target is 8443, and it can be accessed normally in the browser. The command I used is dirsearch -u https://xxxx.com:8443, but it does not work properly.

**Comment by Prady18** [comment]
Y use nmap -p (protocol name) (target ip)

**Comment by Prady18** [comment]
And if any one is not working properly then use it ok (.nmap -sV (T.I) -p 443 (only 443)

**Comment by shelld3v** [comment]
@crazyMarky Please update to dirsearch v0.4.3

**Comment by Prady18** [comment]
You can use tools like Nmap or OpenVAS to scan a target website that uses the HTTPS protocol on a port other than 443. You will need to specify the target URL and port number in the command line or configuration settings. It's important to note that security measures, such as firewalls, can prevent successful scanning and that unauthorized scanning can be illegal, so be sure to obtain permission before attempting to scan a website.

**Comment by Prady18** [comment]
@Prady18 @crazyMarky You can use tools like Nmap or OpenVAS to scan  target website that uses the HTTPS protocol on a port other than 443. You will need to specify the target URL and port number in the command line or configuration settings. It's important to note that security measures, such as firewalls, can prevent successful scanning and that unauthorized scanning can be illegal, so be sure to obtain permission before attempting to scan a website.
