### ISSUE TITLE
How to scan URLs containing IPv6 addresses without domain names？

### ISSUE THREAD

**Issue by wuzuowei** [maurosoria/dirsearch#1276]
### Example：

- https://[2409:8087:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:7777/
---
![3ac81ed3f015a030f81f9f6e4e6a75a](https://user-images.githubusercontent.com/26717790/216289123-86d79a25-3e30-49a1-9941-4182a4bacc11.png)

thank you.

**Comment by Prady18** [comment]
Scan IPv6 URL with Nmap

To scan URLs that contain IPv6 addresses, you can use a tool such as nmap. nmap is a network scanner that can be used to identify open ports and services on a target system. To scan an IPv6 URL, you can use the following syntax:

Less
Copy code
(nmap -6 [IPv6 address]:[port]. )
For example, to scan the URL in your question, you would run the following command:

ruby
Copy code
nmap -6 2409:8087:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx -p 7777

**Comment by kylincodelab** [comment]
> Scan IPv6 URL with Nmap
> 
> To scan URLs that contain IPv6 addresses, you can use a tool such as nmap. nmap is a network scanner that can be used to identify open ports and services on a target system. To scan an IPv6 URL, you can use the following syntax:
> 
> Less Copy code (nmap -6 [IPv6 address]:[port]. ) For example, to scan the URL in your question, you would run the following command:
> 
> ruby Copy code nmap -6 2409:8087:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx -p 7777

sb
