### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ROTPLinux** [maurosoria/dirsearch#128]
Can you make an option like "Skip SSL certificate verification"?, because I have problems with an analysis to a web server.

**Comment by maurosoria** [comment]
Hi ROTPLinux, there is not such verification. Some WAF and Firewalls analyze SSL handshakes detecting non-browser requests (in this case, python). A workaround I recommend is using a HTTP proxy (ZAP or BURP for example) in order to bypass those protections.

Tell me if it helped.
