### ISSUE TITLE
cannot run dirsearch on mac m1 chip

### ISSUE THREAD

**Issue by AzhariRamadhan** [maurosoria/dirsearch#1288]
version v0.4.3
python 3.11.2
Screenshots, dirsearch log, dirsearch version, used command, ...?
<img width="826" alt="Jepretan Layar 2023-03-01 pukul 18 01 02" src="https://user-images.githubusercontent.com/32870854/222121501-48eb5744-a529-416e-815c-32f09f827082.png">

**Comment by shelld3v** [comment]
Can you give me the error message

**Comment by shelld3v** [comment]
You might want to check this: https://stackoverflow.com/questions/73890417/working-on-new-version-of-psycopg-3-and-while-installing-psycopgc-it-wont-inst
