### ISSUE TITLE
Include redirect string when using -F

### ISSUE THREAD

**Issue by dwalter0** [maurosoria/dirsearch#1289]
### What is the feature?

When the -F switch to follow redirects is used, list the redirection/s like when the -F switch is not used.

### What is the use case?

When a dirsearch is run without the follow redirects switch (-F) and it encounters a redirect, it outputs the url that is being redirected to and shows a 302 or whatever. When the follow redirection switch is used, it shows the URL that was originally requested and the status code of the response to following the redirection. This hides some information about what is actually giving that response code. Further investigation is required to determine where the page redirected to, such as curling through a proxy or manually visiting the URLs. If this extra information could be added to the output it would save some time in verifying the redirection traffic.

**Comment by dwalter0** [comment]
I see this has been added in 0.4.3 in the changelog. Seems the kali apt repositories don't have the latest version. "dirsearch is already the newest version (0.4.2+ds-3)"

**Comment by shelld3v** [comment]
You should try installing via git
