### ISSUE TITLE
Disable coloring?

### ISSUE THREAD

**Issue by njfox** [maurosoria/dirsearch#129]
Is there a way to disable coloring in the dirsearch output? I'm trying to include dirsearch in various tools and save the output to a file but the color codes end up being written as well. [ropper](https://github.com/sashs/ropper) for example has a `--nocolor` option to deal with this problem.

**Comment by maurosoria** [comment]
Hi njfox, have you checked the reporting feature?

**Comment by njfox** [comment]
Thanks, I did play a bit with that, but a lot of "tool-running tools" (like [interlace](https://github.com/codingo/Interlace) and my own custom scripts) record `stdout`, which kind of breaks that workflow.

**Comment by hakluke** [comment]
Hey @njfox - as a quick dirty workaround, you can use `sed` to strip out ANSI colours. Something like this:

`python3 dirsearch.py -e php -u http://example.com | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g"`

If, like me, you use this often, you could even add an alias into `.bashrc`:
```
alias stripcolour='sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g"'
```

Then you can just go `dirsearch <options> | stripcolour`

**Comment by mzfr** [comment]
I think this can be achieved using the `--plain-text-report` argument. Even though the output is colored on stdout but the output in the file doesn't have any ANSI characters so in a way the file is free from weird characters.

The `quick hack` suggested by @hakluke is also kinda good.

If we really want to implement than the easy way to do is have a file named `Nocolor.py`(or something else) in `output/` and then we can define all the output functions like `error` or `target` or `debug` etc and make sure all of them do something as simpler as normal `print`.With this method we won't have to edit or make changes to `controller.py` but as we can see it's a dirty hack.

cc: @maurosoria

**Comment by shelld3v** [comment]
Hi, this has been done within #579, can we close this?
