### ISSUE TITLE
Update dicc.txt

### ISSUE THREAD

**Issue by pwnhxl** [maurosoria/dirsearch#1290]
sql.tgz
sql.gz
sql.7z
sql.rar
sql.tar.gz
sql.zip
index.tar.bz2
index.tgz
index.gz
index.7z
index.rar
index.tar.gz
old.tar.bz2
old.tgz
old.gz
old.7z
old.rar
old.tar.gz
old.zip
1.tar.bz2
1.tgz
1.gz
1.7z
1.rar
1.tar.gz
1.zip
a.tar.bz2
a.tgz
a.gz
a.7z
a.rar
a.tar.gz
a.zip
debug/pprof/
back.tar.bz2
vendor/composer/LICENSE
db.sql.gz
dump.sql.gz
resin-doc/viewfile/%3Fcontextpath=/&servletpath=&file=index.jsp
app.ini
database.sql.gz
conf.ini
backup.sql.gz
resin-doc/resource/tutorial/jndi-appconfig/test%3FinputFile=/etc/profile
application.ini
output.tar.gz
settings.ini
x.tar.gz
examples/servlets/servlet/SessionExample
o.tar.gz
conf/conf.zip
examples/
config/config.inc
conf.tar.gz
config/config.php
config.tar.gz
config.inc
server-status
config.php
.git/HEAD
aspxspy.aspx
db.conf
jspspy.jspx
index.bak
jspspy.jsp
key.txt
debug
.mysql_history
phpspy.php
web.config
.idea/modules.xml
tmp.txt
.git/config
temp.txt
readme.html
crossdomain.xml
resin-admin/
database.yml
index.cgi.bak
config/database.yml
.secret_key
db.inc
.key
manager/html
.secret
debug.txt
files/
.rediscli_history
data.txt
secret
.ssh/known_hosts
secret_key
test.aspx
httpd.conf
test.asp
keys
id_rsa
test.jspx
key
id_dsa
.ssh/authorized_keys
test.jsp
logs/
.ssh/id_dsa
id_rsa.pub
.idea/workspace.xml
test.php
.ssh/id_dsa.pub
source/
dama.aspx
.ssh/id_rsa.pub
dama.asp
.ssh/id_rsa
dama.jspx
dama.jsp
dama.php
ooxx.aspx
requirements.txt
ooxx.asp
.git/index
ooxx.jspx
ooxx.jsp
deploy.tar.gz
ooxx.php
build.tar.gz
a.out
x.aspx
install.tar.gz
nohup.out
.htaccess.bak
x.asp
site.tar.gz
.htaccess
create.sql
x.jspx
UPGRADE
user/login
webroot.zip
statistics.html
dump.sql
x.jsp
UPGRADE.txt
signin
tools.tar.gz
core
backup.sql
x.php
UPGRADE.md
webserver.tar.gz
admin/
WEB-INF/web.xml
%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/etc/passwd
admin.sql
MAINTAINERS
s.aspx
htdocs.tar.gz
.mysql.php.swp
../../../../../../../../../../etc/passwd
test.sql
MAINTAINERS.txt
s.asp
etc/passwd
src.tar.gz
MAINTAINERS.md
s.jspx
.db.php.swp
admin
db.sql
.bash_logout
code.tar.gz
INSTALL
.database.php.swp
login
s.jsp
database.sql
.bash_profile
.svn/entries
INSTALL.txt
login.asp
s.php
.settings.php.swp
data.sql
.zshrc
INSTALL.md
login.jsp
1.aspx
.config.php.swp
.bashrc
db.sqlite3
install.php
login.do
1.asp
config/.config.php.swp
db.sqlite
.zsh_history
install.php.txt
login.php
1.jspx
.config.inc.php.swp
solr/
install.php.md
1.jsp
.index.php.swp
.vimrc
pma/index.php
install
1.php
phpMyAdmin/index.php
config.inc.php.bak
install.txt
.bash_history
tz.php
webshell.aspx
login.html
config.json
db.php.bak
_phpmyadmin/index.php
install.md
i.php
webshell.asp
admin.asp
config.php.bak
CONTRIBUTING
phpmyadmin/index.php
info.php
webshell.jspx
admin.do
CONTRIBUTING.txt
phpinfo.php
webshell.jsp
admin.jsp
run.sh
CONTRIBUTING.md
proxy.pac
admin.php
webshell.php
test.sh
changelog
index.php.bak
zabbix/
admin.html
sync.sh
upfile.do
changelog.txt
config.php~
rsync.sh
upfile.html
changelog.md
index.php~
shell.aspx
backup.sh
upfile.aspx
CHANGELOG
cacti/
shell.asp
upfile.asp
CHANGELOG.txt
jmx-console/HtmlAdaptor
shell.jspx
CHANGELOG.md
upfile.jsp
.DS_Store
shell.jsp
LICENSE
upfile.php
setup.sh
composer.lock
shell.php
LICENSE.txt
upload.do
upload.sh
composer.json
LICENSE.md
upload.html
deploy.sh
sftp-config.json
README
upload.aspx
htpasswd.bak
install.sh
README.txt
upload.asp
memadmin/index.php
.htpasswd.bak
upload.jsp
README.md
.htpasswd
readme
upload.php
readme.txt
jenkins/script
readme.md
backup/
help/

**Comment by shelld3v** [comment]
Would you like to submit a PR? It's okay if you don't want to, I will check those entries
