### ISSUE TITLE
越更新越垃圾

### ISSUE THREAD

**Issue by SecureKaiser** [maurosoria/dirsearch#1295]
越更新越垃圾

**Comment by Prady18** [comment]
@duoduozi123 
你想说什么

**Comment by duoduozi123** [comment]
4.1版本自动递归，4.1版本+扫描巨慢 慢慢乌龟一样

**Comment by Prady18** [comment]
@duoduozi123 不知道大

**Comment by guendouzaimed** [comment]
try this tool, it's very faster than dirsearch [https://github.com/guendouzaimed/dirforce](url)

**Comment by shelld3v** [comment]
Hi @Prady18, can you contact me through discord or twitter? Thanks

**Comment by Prady18** [comment]
@shelld3v yes why not

**Comment by Prady18** [comment]
@shelld3v  tell me your twitter name

**Comment by Prady18** [comment]
@duoduozi123  它在哪里

**Comment by shelld3v** [comment]
@Prady18 https://twitter.com/shells3c_

**Comment by Prady18** [comment]
@shelld3v No one is big by this name 🤨

**Comment by Prady18** [comment]
@shelld3v Are you hacking for friendship?are you doing scam

**Comment by shelld3v** [comment]
> @shelld3v Are you hacking for friendship?are you doing scam

Wdym by "scam"? I'm just a maintainer of a Github project, what does that have anything to do with being big or not

**Comment by Prady18** [comment]
@shelld3v then why your twitter account is not opening buddy 😞

**Comment by shelld3v** [comment]
> @shelld3v then why your twitter account is not opening buddy 😞

Can you try clicking the Twitter link in my Github profile? Thanks!

**Comment by Prady18** [comment]
@shelld3v Looks like the link you sent was probably not wrong it must have become brang for some reason.!

**Comment by Prady18** [comment]
@shelld3v yes brother i have followed you

**Comment by Prady18** [comment]
@shelld3v i'm sorry we failed you

**Comment by j4vaovo** [comment]
兄弟  你应该去尝试下go写的一些目录扫描器   速度比dirsearch快三四倍吧   不过dirsearch功能全输出格式多点

**Comment by Prady18** [comment]
@j4vaovo  Ok
