### ISSUE TITLE
排除404仍然显示 | Exclusion 404 is still displayed

### ISSUE THREAD

**Issue by enomothem** [maurosoria/dirsearch#1296]
### What is the current behavior?

Exclusion 404 

### What is the expected behavior?

Exclusion 404 is still displayed

### Any additional information?

D:\>py  D:\dirsearch\dirsearch
.py  --exclude-status=300,400,401,404,500-599  -u http://xxx

![image](https://user-images.githubusercontent.com/45089051/230560831-f284678e-aa16-4882-8cf2-f0b5fd777d1b.png)

**Comment by shelld3v** [comment]
What is your dirsearch version?

**Comment by enomothem** [comment]
@shelld3v dirsearch v0.4.2.8

**Comment by Prady18** [comment]
@enomothem 
@shelld3v
To troubleshoot and find a solution, you could consider the following steps:

Double-check the syntax and parameters used in the "dirsearch" script. Make sure that the "exclude-status" parameter is correctly written as "--exclude-status" and that the values (300, 400, 401, 404, 500-599) are valid HTTP status codes.

Verify the URL (http://xxx) to ensure that it is valid and accessible. Make sure there are no typos or errors in the URL that may be causing the issue.

Check for any error messages or warnings displayed during the execution of the script. This could provide clues as to why "Exclusion 404" is not being displayed as expected.

Review the documentation or support resources for the "dirsearch" script to see if there are any known issues or limitations related to the "exclude-status" parameter or the specific use case.

Consider reaching out to the developer or community of the "dirsearch" script for assistance. They may be able to provide guidance or a solution based on their expertise with the tool.

By carefully reviewing the syntax, parameters, URL, error messages, and seeking help from relevant resources, you may be able to identify and resolve the issue with "Exclusion 404" not being displayed as expected in the "dirsearch script "
Try 👾

**Comment by enomothem** [comment]
I updated to 4.3 to fix this problem, thanks @Prady18

**Comment by Prady18** [comment]
@enomothem Tell me one thing that we told is it true
