### ISSUE TITLE
Error with the proxy: None

### ISSUE THREAD

**Issue by LanmpPython** [maurosoria/dirsearch#1299]
![image](https://user-images.githubusercontent.com/45307601/233919893-45761302-9e1f-4c3b-95f7-b852761e59b6.png)
Why would you prompt for this error

**Comment by XingXiaoWu** [comment]
same question

**Comment by shelld3v** [comment]
@LanmpPython @XingXiaoWu Can you try running with `--log file.log` and give me the `file.log` file? It will help me debug this issue. Thanks!

**Comment by maurosoria** [comment]
Hello !

Was this woukarounded?

**Comment by Kagantua** [comment]
Okay, I'm having the same problem. In my case, I'm using v2rayn to set up a global proxy, in which case dirsearch would have to use the proxy parameter to set up a local proxy port in order for it to work.

**Comment by latxz2025** [comment]
Maybe I used a system proxy, but I turned off the manual proxy in the settings of Windows 11 to solve it.

**Comment by nrathaus** [comment]
It sounds like a system proxy setting is overriding the code use by `requests.Request` to send out requests, and failing, the error returned by `dirsearch` assumes the ProxyError is from the `proxy` variable, but this is not true as it is a system proxy that is returning the error

I believe changing this:
`err_msg = f"Error with the proxy: {proxy}"`

To this:
`err_msg = f"Error with the proxy: {e}"`

Will reveal the error that the system proxy is to blame here

**Comment by shelld3v** [comment]
@nrathaus Great finding 🙏 I will submit a PR for this
