### ISSUE TITLE
Option to disable extensions when providing a wordlist that already includes them

### ISSUE THREAD

**Issue by njfox** [maurosoria/dirsearch#130]
I'm providing a wordlist to dirsearch that already includes the extensions, but dirsearch's `-e` parameter is still mandatory. Would it be feasible to make `-e` optional when providing a wordlist?

**Comment by mazen160** [comment]
Hi @njfox 

The `-e` parameter takes a value (more of a list of values), and replace it with all entries in a wordlist that contains `%EXT%`.  That should be all of what it does.

You can just pinpoint it to a default value. It should not break anything :)
