### ISSUE TITLE
--The exclude response=PATH parameter is not available and cannot filter the output directory. 

### ISSUE THREAD

**Issue by zangcc** [maurosoria/dirsearch#1304]
### --The exclude response=PATH parameter is not available and cannot filter the output directory. Even adding this parameter resulted in no output results.
![图片](https://github.com/maurosoria/dirsearch/assets/64825932/20ad70b3-46fb-4e2f-99ab-356f006f0a06)

### Normal scan results without the - exclude response parameter：

![图片](https://github.com/maurosoria/dirsearch/assets/64825932/eec498bf-6b64-4dac-8391-5947d074b8da)

**Comment by shelld3v** [comment]
I think you don't understand the purpose of `--exclude-response <PATH>`, it excludes all results that have the same HTTP response as the page of the given path. From your screen captures I can see that it worked as intended, all the paths in the second run had the same response (21B)
