### ISSUE TITLE
Host can't be resolved.

### ISSUE THREAD

**Issue by sajjadmd** [maurosoria/dirsearch#1311]
**The present behavior of dirsearch is such that when scanning a list of URLs, if one of the URLs encounters an issue where the host cannot be resolved (commonly known as DNS resolution failure), the dirsearch tool crashes.**

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dirsearch/lib/connection/requester.py", line 83, in __init__
    self.ip = socket.gethostbyname(self.host)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dirsearch/dirsearch.py", line 48, in <module>
    main = Program()
           ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dirsearch/dirsearch.py", line 44, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dirsearch/lib/controller/controller.py", line 217, in __init__
    self.requester = Requester(
                     ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dirsearch/lib/connection/requester.py", line 87, in __init__
    self.ip = socket.gethostbyname(self.host, None, socket.AF_INET6)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: gethostbyname() takes exactly 1 argument (3 given)

**Comment by Prady18** [comment]
@sajjadmd  I had the same problem yesterday

**Comment by Prady18** [comment]
@sajjadmd Here's a potential solution to handle the DNS resolution failure in dirsearch:  
1 u update this tool 🔥 okay

**Comment by Prady18** [comment]
@sajjadmd And if this problem is not solved even after doing all this, then you will tell me.

**Comment by Prady18** [comment]
@sajjadmd And if you can, then install this tool and reinstall it because I was also having the same problem, but I tried many solutions, but nothing happened. so i reinstalled this tool in my system

**Comment by sajjadmd** [comment]
@Prady18 It's working or not.

**Comment by Prady18** [comment]
@sajjadmd yes
