### ISSUE TITLE
replay proxy will stay activated once being called 

### ISSUE THREAD

**Issue by breaking153** [maurosoria/dirsearch#1315]
it use requester.request(xxx,proxy=xxxx)
however ,proxy param uses set proxy func to set session proxy,which will be used by all the request behind the callbacks 
![图片](https://github.com/maurosoria/dirsearch/assets/49428332/5c1c2477-2c8a-4ff6-9ee4-adc90bafe807)

**Comment by Prady18** [comment]
@breaking153 When you use `requester.request(xxx, proxy=xxxx) `and the tool has a callback mechanism that sets a session proxy, it means that the proxy you specify will be applied to all subsequent requests made through the same session. This helps maintain a consistent proxy configuration throughout the scanning process.

This can be useful when you want to route your requests through a proxy server for anonymity or when testing different aspects of a web application's behavior when accessed from different geographic locations or IP addresses.

If you have any `specific questions `about how this proxy mechanism works in the tool you're using or if you need guidance on setting up or `troubleshooting proxy configurations`, feel free to provide more details, and I'll be glad to assist!

**Comment by breaking153** [comment]
as i understood the replay proxy mode is being used to do something like: once the link was found, the request will be replay through the replay-proxy. but when using requester.request(xxx, proxy=xxxx),it will be replay the rest of the request,whatever it was a validate link or not .

**Comment by Prady18** [comment]
@breaking153 The replay proxy mode is a technique often used in web scraping or automation. It involves replaying requests through a proxy server to emulate a previous interaction with a website. This can be useful for various purposes, like bypassing rate limits or handling anti-bot mechanisms.

When using requester.request(xxx, proxy=xxxx) with a replay proxy, the request will go through the proxy server, which helps mimic the behavior of a previous interaction. This can be helpful when you want to ensure that the rest of the request (or subsequent requests) appears to be coming from the same source that the initial interaction did, regardless of whether it was a valid link or not.

In essence, the replay proxy mode helps maintain the context and characteristics of the original request as it continues through the session, which can be beneficial for web scraping or automated tasks that require consistent behavior.

**Comment by shelld3v** [comment]
@breaking153 Have you really tested the behavior? I believe that I tested this in the past and it worked correctly. Closing this now, I can re-open later if you want
