### ISSUE TITLE
Outdated API, although this is not a bug, it is recommended to update it

### ISSUE THREAD

**Issue by ssrsec** [maurosoria/dirsearch#1321]
dirsearch/dirsearch.py:23: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import DistributionNotFound, VersionConflict

**Comment by saltasatelites** [comment]
https://setuptools.pypa.io/en/latest/pkg_resources.html :

Attention

Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.

**Comment by Mr-7r0j4n** [comment]
is there any way to make it work, it is still not working giving same error of pkg_resources is deprecated as an API....?

**Comment by nrathaus** [comment]
An option can be to use what is seen here:
https://github.com/HansBug/hbutils/blob/main/hbutils/system/python/package.py#L202

I reached this code from here:
https://github.com/python/importlib_metadata/issues/450

**Comment by nrathaus** [comment]
If this looks like a worthwhile direction, I can work on it @shelld3v

**Comment by shelld3v** [comment]
Hi @nrathaus, are you still working on this?

**Comment by nrathaus** [comment]
No sorry

I couldn't get it to work with this library

**Comment by shelld3v** [comment]
No problem @nrathaus!

Hi @ssrsec does the error still exist in the LATEST version of pip? I expect that warning to be removed in the latest version of pip
