### ISSUE TITLE
Issue with Recursive Depth Option in Dirsearch

### ISSUE THREAD

**Issue by DevSuyashA** [maurosoria/dirsearch#1332]
### What is the current behavior?
The option of defining the recursive depth works without using the recursive search function at all.

What actually happens?
When Dirsearch (v0.4.2) is executed with the (-R) option and a specific depth (e.g., -R 3), without supplying any specific recursive option (e.g., recursive, deep-recursive, or force-recursive), it does not provide any error message or prompt to specify the type of recursion to use.

### What is the expected behavior?
Dirsearch should throw an error when the (-R) option is used without specifying a recursive type, prompting the user to choose from the available recursive options. Alternatively, it should auto-select one of the available recursive options as a fallback.

What it should be instead?
When the (-R) option is used, either Dirsearch should display an error message, forcing the user to choose a recursion type, or it should automatically use one of the recursive options as a fallback if no specific option is provided.

### Additional Information:

Screenshots or Logs:
![image](https://github.com/maurosoria/dirsearch/assets/43716948/32118a8f-5d8e-4538-8700-1468c657174f)

Dirsearch Version: v0.4.2

Command Used: dirsearch -R 3 -t 100 --wordlist=/usr/share/wordlists/dirb/big.txt -u x.x.x.x

**Comment by shelld3v** [comment]
It uses "normal recursion" by default, I don't know if it's really necessary to do this.

**Comment by shelld3v** [comment]
Decided that this feature is not necessary
