### ISSUE TITLE
为什么用最新的dirsearch扫描的这么慢，而虚拟机中却很快

### ISSUE THREAD

**Issue by soldierbro** [maurosoria/dirsearch#1334]
在我的vm虚拟机中，我是用v0.4.2扫描的非常快。
![1697682733813](https://github.com/maurosoria/dirsearch/assets/26686160/cb4477a0-a607-43a0-94a4-dc2050b92dba)

在宿主机使用v0.4.3扫描网站特别慢，我并没有使用代理，网络也没有问题
我上午刚git pull了最新的代码
![1697681594086](https://github.com/maurosoria/dirsearch/assets/26686160/f71488ea-b74b-48d8-a143-cc86e2530223)
我应该怎么排查问题。

**Comment by ST0new** [comment]
遇到了相同的问题，期待回复解决方案

**Comment by m1m1cat** [comment]
我直接退档老版本了，反正字典自己更新一些

**Comment by shelld3v** [comment]
@soldierbro In your first picture, I can see that you run with 30 threads, the last one you used 25 threads. However I agree there are performance issues with dirsearch, we will try to improve it 👍

**Comment by countingstars0099** [comment]
use "pip install --upgrade dirsearch" ,it may work
