### ISSUE TITLE
How do you exit the entire process when multiple URLs are being fuzzed?

### ISSUE THREAD

**Issue by rew1nter** [maurosoria/dirsearch#1336]
### What is the question?

Pressing ctrl+c in this situation just moves on to the next URL. How do you exit the full process instead of just pausing the current one

**Comment by xalgord** [comment]
pressing ctrl+z will suspend the script completely.

**Comment by shelld3v** [comment]
When you press Ctrl + C, it should show multiple options, including quitting the process
