### ISSUE TITLE
Resolve the pkg_resources module warning issue in the dirsearch scanning tool.

### ISSUE THREAD

**Issue by dioos886** [maurosoria/dirsearch#1337]
python 3.11
└─$ python dirsearch.py -h         
/home/XXX/XX/XXXX/dirsearch-master/dirsearch.py:23: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import DistributionNotFound, VersionConflict

Change the code on line 23 of dirsearch.py to the following.
```
try:
    from importlib import resources as pkg_resources
except ImportError:
    # Fallback for Python versions that don't have importlib.resources
    import pkg_resources
```
![image](https://github.com/maurosoria/dirsearch/assets/31064101/d920d3ae-c5c5-40e2-b0bf-8b6ce6f4965a)

**Comment by xghsyh** [comment]
thank you

**Comment by shelld3v** [comment]
@dioos886 would you like to submit a pull request?

**Comment by shelld3v** [comment]
Hi @dioos886, I don't think `importlib.resources` is the same as `pkg_resources`:

```python
>>> from importlib.resources import DistributionNotFound, VersionConflict
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'DistributionNotFound' from 'importlib.resources' (/usr/lib/python3.11/importlib/resources/__init__.py)
...
>>> from importlib.resources import require
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'require' from 'importlib.resources' (/usr/lib/python3.11/importlib/resources/__init__.py)
```

**Comment by exploide** [comment]
@shelld3v the deprecation warning is still present when running dirsearch with Python 3.12. I think this issue should not be closed.

```
dirsearch.py:23: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import DistributionNotFound, VersionConflict
```

**Comment by Jeyaraman-J** [comment]
Thank you

**Comment by nemu1k5ma** [comment]
thx!

**Comment by ndayiz** [comment]
Thank you sir

**Comment by sagisar1** [comment]
Hello, I thought of better solution for this problem, and it's to replace pkg_resources with a package that is not deprecated. is this possible?

**Comment by shelld3v** [comment]
@sagisar1 I believe updating pip should resolve this problem

**Comment by sagisar1** [comment]
I am using kali linux, and pip is not used there anymore. If I try to upgrade any package even pip itself, with the command:
`python -m pip install --upgrade pip`

I get the error:
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
```
