### ISSUE TITLE
I can't use the dirsearch, the dirsearch.py doesn't work for me

### ISSUE THREAD

**Issue by KarryDavid** [maurosoria/dirsearch#1338]
macbookpro M1 11.6, python3.12, The latest version of dirsearch.
**I have downloaded the dependency "requirements.txt", but it is still as follows:**
<img width="901" alt="iShot_2023-10-23_17 52 18" src="https://github.com/maurosoria/dirsearch/assets/148523813/d7a05ee9-261c-4af9-9a34-f501b5f0cf93">

Missing required dependencies to run.
Do you want dirsearch to automatically install them? [Y/n] y
Installing required dependencies...
Failed to install dirsearch dependencies, try doing it manually.

I follow the https://github.com/maurosoria/dirsearch/issues/1117 to solve my problem, but it still doesn't work.
I enter the "n":
<img width="744" alt="iShot_2023-10-23_17 48 56" src="https://github.com/maurosoria/dirsearch/assets/148523813/afe8de3b-f6d6-4b31-97f9-1659b4d8b453">

could you please help me?

**Comment by mathenz** [comment]
Hi. Did you create a virtual environment?

**Comment by Jazz0day** [comment]
git clone https://github.com/maurosoria/dirsearch.git
no --depth=1

**Comment by shelld3v** [comment]
@KarryDavid In the second image, it said you forgot to provide a URL (with `-u <URL>`)

**Comment by kolakal** [comment]
Hi I am trying to install dirsearch in my kali machine but I am getting below error,

"Cannot uninstall charset-normalizer 3.3.2
The package's contents are unknown: no RECORD file was found for charset-normalizer.
hint: The package was installed by debian. You should check if it can uninstall the package."
