### ISSUE TITLE
There was a problem in the request to【对的请求中出现问题】

### ISSUE THREAD

**Issue by xk-mt** [maurosoria/dirsearch#1339]
如果重新解压文件重新跑就正常，我可以提供任何数据，来帮助测试

使用过程中出现下面问题
![image](https://github.com/maurosoria/dirsearch/assets/77874955/190f9f60-378a-4c79-9e48-48e228ee2ee0)

执行：dirsearch.py -u https://网址
报错：如图上

执行：dirsearch.py --proxy 127.0.0.1:8080 -u https://网址
就可以，很奇怪挂burp就可以继续，不挂代理就报错

**Comment by shelld3v** [comment]
@xk-mt Run `dirsearch.py --proxy 127.0.0.1:8080 -u https://网址 --log file.log` and check `file.log`
