### ISSUE TITLE
"reports" folder always created

### ISSUE THREAD

**Issue by cyberaz0r** [maurosoria/dirsearch#1341]
### What is the problem?

The "reports" folder is created regardless of whether you specify a different path for the output file. Additionally you cannot set a flag for disabling output files.

### How should it be solved?

There should be a flag to disable output file and it should not create the "reports" folder on the current working directory if a different path is specified via the `-o` option.

**Comment by ajcriado** [comment]
@cyberaz0r After inspecting the code I found that this is an option that is enabled by default. You can change it by modifying your config.ini file and setting `autosave-report = True` to `autosave-report = False`

**Comment by shelld3v** [comment]
@cyberaz0r dirsearch does not create "reports" folder if you have already declared the path of the output file via `-o`, the "reports" folder probably had been created before that. Also, @ajcriado has shown how to disable the auto-reporting feature, hope that helps

**Comment by ajcriado** [comment]
@shelld3v Indeed, it does create the "reports" folder and leaves it empty. I have created [this](https://github.com/maurosoria/dirsearch/pull/1348) pull request to control that
