### ISSUE TITLE
怎么递归遍历302目录/How to recursively traverse the 302 directory

### ISSUE THREAD

**Issue by onegitting** [maurosoria/dirsearch#1344]
需求：
比如扫描一个目录名为：/aa  这个目录时存在的，里面也有子目录，但是Nginx设置，没有访问到二级目录中的应用，是不会自动跳转到二级目录中的，就直接跳转到了域名下的认证接口，dirsearch从而递归不到/aa目录中的其他系统，怎么才能这遇到302时，递归当前扫描的目录？

need:
For example, when scanning a directory named: /aa, this directory exists, and there are subdirectories in it. However, Nginx settings do not access applications in the secondary directory. It will not automatically jump to the secondary directory, so it will jump directly. After switching to the authentication interface under the domain name, dirsearch cannot recurse to other systems in the /aa directory. How can we recurse the currently scanned directory when encountering 302?

**Comment by shelld3v** [comment]
Hi @onegitting, I have some problems trying to comprehend your message, but if I got your idea right then probably the solution here is `--deep-recursive`. Assuming you find `/aa/bb/cc`, with `--deep-recursive` it will perform recursive scanning on `/aa`, `/aa/bb` and `/aa/bb/cc`. If that's not what you want, I would like to have some examples of what you are trying to achieve here. Thanks!
