### ISSUE TITLE
Dirsearch not running? 

### ISSUE THREAD

**Issue by w3b5h3ll** [maurosoria/dirsearch#1350]
### What is the question?
- I use NixOS , and virtualenv python 
- after active, install by pip install -r requirements.txt
- python ./setup.py
dirsearch not running?

└─$ dirsearch -u http://192.168.0.4 -e "*"

  _|. _ _  _  _  _ _|_    v0.4.3
 (_||| _) (/_(_|| (_| )

Extensions: php, jsp, asp, aspx, do, action, cgi, html, htm, js, tar.gz | HTTP method: GET | Threads: 25 | Wordlist size: 14999

Output: /home/w3b5h3ll/Pentest/dirsearch/reports/http_192.168.0.4/_24-01-03_02-31-10.txt

Target: http://192.168.0.4/

Task Completed

**Comment by 0xl30** [comment]
![Screenshot_2024-01-03-18-45-25_29125](https://github.com/maurosoria/dirsearch/assets/72350874/3a337f6c-febd-4b9a-b74b-c220b196abfe)
Same Issue In Arch Linux

**Comment by drego85** [comment]
Same problem here, the task finished very fast!
