### ISSUE TITLE
Broken output folder name when scheme isn't provided

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#1357]
### What is the current behavior?

When you provide a target without an URI scheme (`-u example.com`), the URI scheme will be missing in the output folder name, as below

![image](https://github.com/maurosoria/dirsearch/assets/59408894/50cbc370-2e40-4e9e-836f-b0c536da52d6)

### What is the expected behavior?

Because dirsearch detects the scheme anyway, the scheme should appear in the folder name, as below

![image](https://github.com/maurosoria/dirsearch/assets/59408894/fbe71539-6e53-478c-97f9-77e3de257cdb)

**Comment by maurosoria** [comment]
This should be easy to fix. Moreover, was the older behaviour

**Comment by shelld3v** [comment]
> This should be easy to fix. Moreover, was the older behaviour

The fix is probably performing scheme detection before the creation of the report folder, I will work on this when I have time

**Comment by nrathaus** [comment]
I believe offending code is inside `def setup_reports(self):`
