### ISSUE TITLE
Exclude 200 error page

### ISSUE THREAD

**Issue by Rvn0xsy** [maurosoria/dirsearch#136]
There are some cases that web application return error pages with 200 status code. Do we have an option to exculde these error pages?

**Comment by hakluke** [comment]
@Rvn0xsy there's no option for this, however, the error page is usually the same size, you can filter out that size using grep. For example, if the error page returns 123 bytes, you can use `python3 ./dirsearch.py -e php -u http://example.com | grep -v 123B`

**Comment by Rvn0xsy** [comment]
Okay, Thanks

**Comment by Rvn0xsy** [comment]
> @Rvn0xsy there's no option for this, however, the error page is usually the same size, you can filter out that size using grep. For example, if the error page returns 123 bytes, you can use `python3 ./dirsearch.py -e php -u http://example.com | grep -v 123B`

Okay, Thanks
