### ISSUE TITLE
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### ISSUE THREAD

**Issue by Qs2255** [maurosoria/dirsearch#1363]
### how to solve this error?

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by Prady18** [comment]
@maurosoria 
python -m pip install tea "cup >= 3.13"
You are right 👍 @Qs2255

**Comment by vprg888** [comment]
**Hello.. How to fix this?**

/usr/lib/python3/dist-packages/dirsearch/dirsearch.py:23: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import DistributionNotFound, VersionConflict

**Comment by nrathaus** [comment]
This can be closed
