### ISSUE TITLE
How to avoid to brute-force some directory recursively?

### ISSUE THREAD

**Issue by tenghaooo** [maurosoria/dirsearch#1367]
dirsearch version: v0.4.3
HI, I want to do brute-force recursively but avoid some directory.

For example:
I find three redirectable path A,B,C at FIRST ROUND.
301 https://whatever.com/A
301 https://whatever.com/B
301 https://whatever.com/C
then A,B,C will be added to the queue for next round.
But I don't want to brute-force path C.
like
https://whatever.com/C/...
How can i do it?

I tried following options but it didn't seem to work.
dirsearch -u https://whatever.com -r -R 1 -o plain --format=plain --exclude-subdirs=C
dirsearch -u https://whatever.com -r -R 1 -o plain --format=plain --exclude-subdirs C
dirsearch -u https://whatever.com -r -R 1 -o plain --format=plain --exclude-subdirs C/

**Comment by nrathaus** [comment]
I believe you should look at `--exclude-redirect` rather than `--exclude-subdirs` for your setup as you are mentioning that its a `301` that brings you to the site you don't want

**Comment by shelld3v** [comment]
Hi @tenghaooo, this is a bug, and I will work on fixing it as soon as possible
