### ISSUE TITLE
Cannot connect to xxxx

### ISSUE THREAD

**Issue by SummusFortunaeDictator** [maurosoria/dirsearch#1369]
### What is the current behavior?

What actually happens?

### What is the expected behavior?

What it should be instead?

### Any additional information?

Screenshots, dirsearch log, dirsearch version, used command, ...?

**Comment by nrathaus** [comment]
This can be closed, there is nothing here

**Comment by shelld3v** [comment]
Agree with @nrathaus 👍🏻
