### ISSUE TITLE
--exclude-status

### ISSUE THREAD

**Issue by w9w** [maurosoria/dirsearch#137]
--exclude-status or -x argument doesn't work, it's being ignored

**Comment by ebelties** [comment]
What is the command you tried? Because it should just work.

**Comment by hakluke** [comment]
I haven't had any issue with this option. @w9w are you able to provide example output or a screenshot for troubleshooting?

**Comment by mzfr** [comment]
@w9w Do you still have this issue? If yes then can you please clarify a bit.
