### ISSUE TITLE
Requirements. txt is missing the pkg_resources module

### ISSUE THREAD

**Issue by Crany-web** [maurosoria/dirsearch#1377]
1. Download the latest release compressed package
2. Unzip the compressed package
3. Enter the decompressed path and execute `python -m venv ./venv`
4. Activate the virtual environment `source venv/bin/activate`
5. Execute `pip install -r requirements.txt` (the process goes smoothly without any problems)
6. Execute `python dirsearch.py` and the terminal echoes ModuleNotFoundError: No module named 'pkg_resources'
7. After understanding that you need to use `pip  install setuptools`
8. Execute `python dirsearch.py` again and find that it can run normally
PS: I hope developers can add setuptools to requirements.txt

**Comment by ret2src** [comment]
Workaround:

```bash
pipx inject dirsearch setuptools
```

This injects the missing module into the dirsearch environment.
