### ISSUE TITLE
Headers option does not properly set header host

### ISSUE THREAD

**Issue by Hex27** [maurosoria/dirsearch#139]
Example:
dirsearch.py -u https://10.10.10.123 -H "Host: administrator1.friendzone.red" -e php
Does not actually set the Host header to what was parsed. Instead, the ip 10.10.10.123 is used.

I manually made a change to the program so host is properly set via the headers argument, but I'm unsure if I'm using the program wrongly in the first place.

**Comment by maurosoria** [comment]
Hi Hex27, you should use it this way:
dirsearch.py -u https://administrator1.friendzone.red --ip 10.10.10.123 -e php

Tell me if it worked!

**Comment by Hex27** [comment]
Yep, it works. Thanks!
