### ISSUE TITLE
Not installing 

### ISSUE THREAD

**Issue by Benojir** [maurosoria/dirsearch#1396]
### Showing these error while installing?

`Building wheel for cryptography (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cryptography (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      Running `maturin pep517 build-wheel -i /data/data/com.termux/files/usr/bin/python3.11 --compatibility off`
      📦 Including license file "/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/LICENSE"
      📦 Including license file "/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/LICENSE.APACHE"
      📦 Including license file "/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/LICENSE.BSD"
      🍹 Building a mixed python/rust project
      🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
      🐍 Not using a specific python interpreter
      📡 Using build options features, locked from pyproject.toml
         Compiling proc-macro2 v1.0.86
         Compiling target-lexicon v0.12.15
         Compiling unicode-ident v1.0.12
         Compiling cc v1.1.6
         Compiling vcpkg v0.2.15
         Compiling pkg-config v0.3.30
         Compiling once_cell v1.19.0
         Compiling libc v0.2.155
         Compiling cfg-if v1.0.0
         Compiling autocfg v1.3.0
         Compiling openssl v0.10.66
         Compiling memoffset v0.9.1
         Compiling foreign-types-shared v0.1.1
         Compiling heck v0.5.0
         Compiling foreign-types v0.3.2
         Compiling bitflags v2.6.0
         Compiling cryptography-key-parsing v0.1.0 (/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/src/rust/cryptography-key-parsing)
         Compiling pyo3-build-config v0.22.2
         Compiling indoc v2.0.5
         Compiling unindent v0.2.3
         Compiling quote v1.0.36
         Compiling cryptography-openssl v0.1.0 (/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/src/rust/cryptography-openssl)
         Compiling cryptography-rust v0.1.0 (/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/src/rust)
         Compiling syn v2.0.71
         Compiling base64 v0.22.1
         Compiling self_cell v1.0.4
         Compiling openssl-sys v0.9.103
         Compiling cryptography-cffi v0.1.0 (/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/src/rust/cryptography-cffi)
         Compiling pem v3.0.4
      error: failed to run custom build command for `cryptography-cffi v0.1.0 (/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/src/rust/cryptography-cffi)`

      Caused by:
        process didn't exit successfully: `/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/src/rust/target/release/build/cryptography-cffi-9a2d98541d7d521e/build-script-build` (exit status: 101)
        --- stdout
        cargo:rustc-check-cfg=cfg(python_implementation, values("CPython", "PyPy"))
        cargo:rerun-if-env-changed=PYO3_PYTHON
        cargo:rerun-if-changed=../../_cffi_src/
        cargo:rerun-if-changed=../../cryptography/__about__.py

        --- stderr
        thread 'main' panicked at cryptography-cffi/build.rs:39:9:
        failed to run build_openssl.py, stdout:

        stderr:
        Traceback (most recent call last):
          File "/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/src/rust/cryptography-cffi/../../_cffi_src/build_openssl.py", line 18, in <module>
            ffi = build_ffi_for_binding(
                  ^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/src/rust/cryptography-cffi/../../_cffi_src/utils.py", line 49, in build_ffi_for_binding
            return build_ffi(
                   ^^^^^^^^^^
          File "/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/src/rust/cryptography-cffi/../../_cffi_src/utils.py", line 61, in build_ffi
            ffi = FFI()
                  ^^^^^
          File "/tmp/pip-build-env-uayzoc4z/overlay/lib/python3.11/site-packages/cffi/api.py", line 48, in __init__
            import _cffi_backend as backend
        ImportError: dlopen failed: library "/tmp/pip-build-env-uayzoc4z/overlay/lib/python3.11/site-packages/_cffi_backend.cpython-311.so" needed or dlopened by "/data/data/com.termux/files/usr/lib/libpython3.11.so.1.0" is not accessible for the namespace "(default)"

        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON="/data/data/com.termux/files/usr/bin/python3.11" PYTHON_SYS_EXECUTABLE="/data/data/com.termux/files/usr/bin/python3.11" "cargo" "rustc" "--features" "pyo3/abi3-py37" "--message-format" "json-render-diagnostics" "--locked" "--manifest-path" "/tmp/pip-install-vtxhjyfq/cryptography_da8aece46bd948e8bc2723dc42d89cc2/src/rust/Cargo.toml" "--release" "--lib"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/data/data/com.termux/files/usr/bin/python3.11', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cryptography)`

**Comment by shelld3v** [comment]
This is not a "dirsearch issue"
