### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by zrquan** [maurosoria/dirsearch#1397]
Adding type hints helps improve code readability and also facilitates static type checking and code completion.

If you believe this is meaningful, I’d be happy to complete it : )

**Comment by shelld3v** [comment]
Yeah this would be great, considering the scale of the project

**Comment by Kantseep** [comment]
We are very interested

**Comment by zrquan** [comment]
Hi @Kantseep , I’m working on this, I can open a draft PR if you are interested. 😄
