### ISSUE TITLE
The output of the latest version of dirsearch is not colored

### ISSUE THREAD

**Issue by EternityYan** [maurosoria/dirsearch#1399]
The latest version of dirsearch output is not color-coded, the output is all white, and the color attribute of the configuration file is true.

![image](https://github.com/user-attachments/assets/948b04fe-81df-470b-ae06-37b7704001c2)
![image](https://github.com/user-attachments/assets/f6cbe3ae-1c69-4b10-9cc9-19451f37ff22)

environment
Operating system: win11
Python version: Python 3.11.9

Please take a look at this issue.

**Comment by zrquan** [comment]
@shelld3v This is a bug of [this commit](https://github.com/maurosoria/dirsearch/commit/bcb10a1eaf4ab6c8aaeeb33fc2fc765b21eebfce). The default value of `opt.color` is None, not True.
