### ISSUE TITLE
Option to filter by status codes.

### ISSUE THREAD

**Issue by dtnml** [maurosoria/dirsearch#140]
Hello,

Great tool. Is there or shall there be an option to look for specific status codes. Say i am only looking for 200,204,301,302,307,403 codes??

**Comment by hakluke** [comment]
@dtnml there is an option to _exclude_ status codes (`-x`), but not to only show a particular status code. The easiest way to do this might just be to use grep, for example:

```
python3 ./dirsearch.py -e php -u http://example.com | grep 200
```

**Comment by dtnml** [comment]
Thanks..
