### ISSUE TITLE
Inventory notification

### ISSUE THREAD

**Issue by noraj** [maurosoria/dirsearch#141]
Your tool/software has been inventoried on [*Rawsec's CyberSecurity Inventory*](https://inventory.rawsec.ml/).

### What is Rawsec's CyberSecurity Inventory?

An inventory of tools and resources about CyberSecurity. This inventory aims to help people to find everything related to CyberSecurity.

+ **Open source**: Every information is available and up to date. If an information is missing or deprecated, you are invited to (help us).
+ **Practical**: Content is categorized and table formatted, allowing to search, browse, sort and filter.
+ **Fast**: Using static and client side technologies resulting in fast browsing.
+ Rich tables: search, sort, browse, filter, clear
+ Fancy informational popups
+ Badges / Shields
+ Static API
+ Twitter bot

More details about features [here](https://inventory.rawsec.ml/features.html).

Note: the inventory is a FLOSS (Free, Libre and Open-Source Software) project.

### Why?

+ **Specialized websites**: Some websites are referencing tools but additional information is not available or browsable. Make additional searches take time.
+ **Curated lists**: Curated lists are not very exhaustive, up to date or browsable and are very topic related.
+ **Search engines**: Search engines sometimes does find nothing, some tools or resources are too unknown or non-referenced. These is where crowdsourcing is better than robots.

### Why should you care about being inventoried?

Mainly because this is giving visibility to your tool, more and more people are using the *Rawsec's CyberSecurity Inventory*, this helps them find what they need.

### Badges

The badge shows to your community that your are inventoried. This also shows you care about your project and want it growing, that your tool is not an abandonware.

Feel free to claim your badge here: http://inventory.rawsec.ml/features.html#badges, it looks like that [![Rawsec's CyberSecurity Inventory](https://inventory.rawsec.ml/img/badges/Rawsec-inventoried-FF5050_flat.svg)](https://inventory.rawsec.ml/), but there are several styles available.

### So what?

That's all, this message is just to notify you if you care.

**Comment by noraj** [comment]
https://inventory.rawsec.ml/tools.html#dirsearch

**Comment by maurosoria** [comment]
Big thanks!
