### ISSUE TITLE
Why dirseach.py scans slower than dirsearch.exe

### ISSUE THREAD

**Issue by EternityYan** [maurosoria/dirsearch#1419]
System: Win11
python version: 3.12.7
I used pip install dirsearch to download dirsearch.exe scanning speed is dozens or hundreds of entries per second. using python to run training dirsearch.py scanning speed is ten entries or less per second, not more than 30 entries. the threads are all 25. why is running dirseach with python code so much slower than dirsearch.exe?
Please take a look at this problem, thanks
![image](https://github.com/user-attachments/assets/6efbb8cc-5442-4312-a50a-572c9594e7ac)
![image](https://github.com/user-attachments/assets/bd9a7402-e01c-4066-8b35-daf5ea1b146a)

**Comment by EternityYan** [comment]
Thanks for your reply. i tried using the -a parameter as you said, and the scanning speed was greatly improved, hundreds or even thousands of entries per second, but the accuracy of the scanning was not enough. here are the results of my tests, one with and one without the -a parameter.
Looks better for running in linux.
![9af2eb235746b3fd7ef4f051a5515055](https://github.com/user-attachments/assets/956a7818-e2f7-435a-8b1f-758f80669153)

**Comment by shelld3v** [comment]
@zrquan What do you think? I have tested asynchronous mode before and it worked as intended 🤔 Another problem here is dirsearch gives you `/error/` result twice, one of them showed a redirection the other didn't.

@EternityYan Can you share your `config.ini`?

**Comment by shelld3v** [comment]
@zrquan Is it possible that dirsearch in asynchronous mode sent too many requests that it got messed up either on the server side or the application side?

@EternityYan Can you try to run dirsearch again in asynchronous mode but with fewer threads and `--max-rate=100`?

**Comment by zrquan** [comment]
I think this issue is probably down to 296e8162368b4bca8153e2550ec00d91982e0ae7, which got rid of a `time.sleep`. This could mean that the `process` method is using more CPU resources, which might affect performance.

**Comment by zrquan** [comment]
I haven't yet tried the asynchronous mode on Windows, so it might not work perfectly. 😰
However, it works well on Linux.

**Comment by shelld3v** [comment]
> I think this issue is probably down to [296e816](https://github.com/maurosoria/dirsearch/commit/296e8162368b4bca8153e2550ec00d91982e0ae7), which got rid of a `time.sleep`. This could mean that the `process` method is using more CPU resources, which might affect performance.

Yeah I have also noticed that and submitted a PR for it already

**Comment by EternityYan** [comment]
Thanks guys, figured it out, I'll be running more in linux from now on!😊

**Comment by EternityYan** [comment]
Hi, I used the latest version of dirseach, the scanning speed is much faster than before, the scanning speed shows a few hundred, more than a thousand entries per second, the accuracy of the scanning is also very good, thank you for letting me use such a good tool!
![image](https://github.com/user-attachments/assets/84fd02df-64f3-4005-b6f1-fdee1170b1f8)
![image](https://github.com/user-attachments/assets/7217b407-fe82-47e3-9ce3-68a8c88b3718)
