### ISSUE TITLE
Support Multiple URL's in -u

### ISSUE THREAD

**Issue by lynch-a** [maurosoria/dirsearch#142]
Hi,

I have a situation where I would like to provide multiple URL's to the dirsearch command where creating a .txt site list for use with the -L argument is not an option. Consider supporting multiple URL's passed to the -u argument similar to: "-u site1.com site2.com" (or however else you see fit)

Thanks

**Comment by hakluke** [comment]
Hey @lynch-a ! Out of interest, what is this situation? Why is putting the URLs into a file not an option?

**Comment by vay3t** [comment]
is possible with for...
```bash
for page in $(cat urls.txt): do
    dirsearch -u $page -e blablabla
done
```
but the ideal would be that the same dirsearch existed the option

**Comment by yeroc-sebrof** [comment]
You should be able to use `--url-list=` for this purpose. This issue should be closed

**Comment by lynch-a** [comment]
> You should be able to use `--url-list=` for this purpose. This issue should be closed

nmap supports multiple targets from the command line without requiring usage of `-iL=... `

it can helpful in certain automated situations

why not dirsearch?

**Comment by ManShum815** [comment]
lynch-a 
( https://github.com/ManShum815/Dirsearch-Running-Multiple-URL )

**Comment by ManShum815** [comment]
> > You should be able to use `--url-list=` for this purpose. This issue should be closed
> 
> nmap supports multiple targets from the command line without requiring usage of `-iL=... `
> 
> it can be helpful in certain automated situations to supply multiple targets to tools without creating a temporary/extra file on the storage device
> 
> why not dirsearch?

I think you should try my script 
https://github.com/ManShum815/Dirsearch-Running-Multiple-URL
