### ISSUE TITLE
Python12 cannot use dirsearch 

### ISSUE THREAD

**Issue by hunmeng123** [maurosoria/dirsearch#1431]
### What is the current behavior?
![Uploading 1730534596938.jpg…]()

### What actually happens?
Using python12 version
### What is the expected behavior?
normal use

**Comment by hunmeng123** [comment]
![Uploading 1730534491597.jpg…]()
![Uploading 1730534596938.jpg…]()

**Comment by hunmeng123** [comment]
Python11 can be used normally

**Comment by shelld3v** [comment]
Hi @hunmeng123, I can't see the attachments you sent, can you try to send them again?

**Comment by hunmeng123** [comment]
![1730534491597](https://github.com/user-attachments/assets/fb2aa8dc-c69e-4940-bf4a-bb49bf519d1b)

**Comment by shelld3v** [comment]
Make sure you have installed mysql probably: https://dev.mysql.com/doc/connector-python/en/connector-python-installation.html
