### ISSUE TITLE
Need help for PEP8

### ISSUE THREAD

**Issue by maurosoria** [maurosoria/dirsearch#144]
Hi community!

I don't have much time lately, and I'd like to start applying this convention. So, I'm opening this issue looking for people who have time to do it.

If anyone is there, and you have experience with this convention, I'd really appreciate your help.

https://www.python.org/dev/peps/pep-0008/

I started writing this tool many years ago and I was used to write using lowerCamelCase Convention (hadn't written enough python code yet and didn't know so many people would use this tool really...) but know that I see that this piece of code might have some future, I think that using a convention it's necessary for the community driven development.

Anyone there?

**Comment by Damian89** [comment]
Yeah, I can help you here - step by step, I like and need dirsearch, so expect some prs in the near future which contain just renames etc

**Comment by Damian89** [comment]
Btw. who is this "Daniel89" in the readme ? :P

**Comment by maurosoria** [comment]
Would you forgive me ? :c

**Comment by Damian89** [comment]
of course ;)

**Comment by ftk-sostupid** [comment]
Maybe we can use https://github.com/hhatto/autopep8 ?
I can help too if needed. ：）
