### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by ocervell** [maurosoria/dirsearch#1443]
There was no GitHub or PyPI releases since 2022. 

FYI the install on PyPI is broken:
```
# dirsearch --help
Traceback (most recent call last):
  File "/root/.local/bin/dirsearch", line 5, in <module>
    from dirsearch.dirsearch import main
  File "/root/.local/share/pipx/venvs/dirsearch/lib/python3.12/site-packages/dirsearch/dirsearch.py", line 23, in <module>
    from pkg_resources import DistributionNotFound, VersionConflict
ModuleNotFoundError: No module named 'pkg_resources
```

Please consider making a new release.

**Comment by di3n0** [comment]
The same.

**Comment by di3n0** [comment]
I resolved it.
File "/home/kali/.local/share/pipx/venvs/dirsearch/lib/python3.12/site-packages/dirsearch/dirsearch.py", line 23, in <module>
So that, I removed the dirsearch from the path of the pipx.
And then, I install by 'sudo apt-get install dirsearch'.

**Comment by shelld3v** [comment]
We do have plan to make a release soon

**Comment by ocervell** [comment]
@shelld3v any update ?

**Comment by ocervell** [comment]
@shelld3v why close ? Latest PyPI release is 4 years old ... Happy new year.

**Comment by ocervell** [comment]
@shelld3v please don't close or I'm afraid it won't happen... please keep track of it ! Just asking for one release every 4 years is not too much too ask, is it ?
