### ISSUE TITLE
session.pickle is not a valid session file or it's in an old format

### ISSUE THREAD

**Issue by archidote** [maurosoria/dirsearch#1446]
### What is the current behavior?  
When attempting to resume a session using the `-s` option with a previously saved session file (`session.pickle`), the scan does not resume from the saved state.  

### What is the expected behavior?  
The scan should correctly resume from the last saved state stored in the session file.  

### Any additional information?  
- **Tool Version:** dirsearch v0.4.3  
- **Operating System:** Ubuntu 24.04.1 
- **Python Version:** Python3.12.3 
- **Command Used:**  

 ```
dirsearch.py -s session.pickle
```

**Comment by shelld3v** [comment]
There are 2 posibilities:
- You are using an old version of dirsearch, which has a bug that I fixed back in October
- You used an old version of dirsearch when saving the session and then updated dirsearch before resuming the session file again (The dirsearch versions that saved the session and resumed the session must be the same)

**Comment by archidote** [comment]
@shelld3v, Indeed, it was the first option. Everything works perfectly with the latest release (commid id : 60a50464e810a49af9e87f1b29d7da5677edf256). Thank you for your insight !

**Comment by archidote** [comment]
@shelld3v, Indeed, it was the first option. Everything works perfectly with the latest release (commid id : 60a50464e810a49af9e87f1b29d7da5677edf256). Thank you for your insight !
