### ISSUE TITLE
Feature request: Ignore SSL Warnings

### ISSUE THREAD

**Issue by hakluke** [maurosoria/dirsearch#145]
Sometimes I need to scan a host with a bad SSL cert. Dirsearch throws an error and exits. It would be nice to have a way to force dirsearch to ignore SSL issues and scan anyway, like the `--insecure` flag on `curl`.

**Comment by Damian89** [comment]
Do you have an example url? (You could send it also via twitter)

**Comment by hakluke** [comment]
Now that I'm trying to test it, it's actually working fine?!
To test I am using the examples at badssl.com, dirsearch seems to not care that the certs have expired, I'm not sure what the problem was that I encountered.

I'm closing this for now!
