### ISSUE TITLE
[Feature request] --replace-extension

### ISSUE THREAD

**Issue by noraj** [maurosoria/dirsearch#149]
## Description / context

A lot of list of files are already containing extensions like `SecLists/Discovery/Web-Content/raft-medium-files-lowercase.txt`

So by doing this it will only search for files mentioned in the list where most extensions are php or html.

```
$ dirsearch -u http://10.x.x.x/path/ -e txt,pl -w ~/CTF/tools/SecLists/Discovery/Web-Content/raft-medium-files-lowercase.txt
```

`--force-extensions` can only be used on lists without extensions else it will request `.php.pl` or whatever double extension.

## Idea

Implement a `--replace-extension` that will drop the extension in the list and use the ones provided by `-e`.

**Comment by mzfr** [comment]
@noraj so in this what we want is that if the string to be tested from the file is say `admin-panel.xml` then the `.xml` should be dropped and `admin-panel.txt` or `admin-panel.pl` i.e the extensions passed in `-e` argument

Have I interpreted this right or did you meant to say something else.

**Comment by noraj** [comment]
@mzfr Yeah that's what I mean.

**Comment by shelld3v** [comment]
Hi, now it's done. You can use `-X` to replace extensions you do not want to work with. Moreover, you can combine `-e pl,txt --no-extension -f` to replace extensions in all entries (then set it again with `-f -e pl,txt`).

Close this if everything has been done

**Comment by shelld3v** [comment]
Ohh, `--only-selected` does all the things

**Comment by shelld3v** [comment]
Hi @noraj 🖐️ 

This is a really good example for feature requests that we want to look more in the feature! Feel free to submit more feature requests like this, we'd love to see that!!!
