### ISSUE TITLE
Couldn't resolve DNS on windows

### ISSUE THREAD

**Issue by SaltNego** [maurosoria/dirsearch#151]
````
C:\Users\Negoowen\dirsearch>python3 dirsearch.py -u 'http://123.206.87.240:8002/flagphp/' -e php

 _|. _ _  _  _  _ _|_    v0.3.8
(_||| _) (/_(_|| (_| )

Extensions: php | Threads: 10 | Wordlist size: 5918

Error Log: C:\Users\Negoowen\dirsearch\logs\errors-19-06-20_15-34-29.log

Target: 'http://123.206.87.240:8002/flagphp/'

Couldn't resolve DNS

Task Completed
````

**Comment by zzy2210** [comment]
yet,I have this problem too。Have you solved this problem?

**Comment by maurosoria** [comment]
Can you provide more info? Only in windows with IP:PORT format?

**Comment by DustinTheGreat** [comment]
> Can you provide more info? Only in windows with IP:PORT format?

Can confirm it works on Linux

**Comment by shelld3v** [comment]
The problem here is that in Windows, `"stuff"` will become `stuff` but `'stuff'` will still be `'stuff'`, `'` won't be removed. Try `python3 dirsearch.py -u "http://123.206.87.240:8002/flagphp/" -e php` and see the magic (close the issue too)

**Comment by shelld3v** [comment]
Again, this is not an application issue, it's a human issue! Please close this!

**Comment by Be1nna** [comment]
same problem(Linux)
