### ISSUE TITLE
Hangs on when finding a big file

### ISSUE THREAD

**Issue by koutto** [maurosoria/dirsearch#156]
Hey,
Thanks for dirsearch, it is a great tool and very fast.
I detect a problem when it detects a big file : I am scanning a website where there is a "dump.sql" file which has a 1.3 Gb size (available at https://www.site.com/dump.sql). When running dirsearch on this website, the script gets stuck and hangs on forever. I think it is trying to read the whole file, that's why it is taking too much time. 

Note: According to the code, I think it is due to the fact dirsearch retrieves the full response body to compute its length and display it, using ``len(response.body)``. Maybe in this configuration, it should be replaced by value of ``Content-length`` HTTP response header (if available).

Cheers

**Comment by shelld3v** [comment]
Hi, thank you for your help, we have updated that into our code! 
If there is any other problem, feel free to create another issue!
