### ISSUE TITLE
Multithreading problems

### ISSUE THREAD

**Issue by dgaavl** [maurosoria/dirsearch#16]
When configured for use multiple threads sometimes doesnt find resources.

It'easy to check. Just launch the program against a web server with known resources and with a medium size dictionary file.

Try it with "-t 1" and with "-t 20" several times. You'll see that "-t 20" option sometimes returns less hits.

**Comment by maurosoria** [comment]
Hi dgaavl

First, I'd like to excuse me because I did't answer before. If u're still interested, send me an email to workout this issue. I'll send you a private copy of dirsearch so you can test if the bug stills unresolved.

Thanks

**Comment by maurosoria** [comment]
check now please
