### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by exploide** [maurosoria/dirsearch#160]
I noticed that dirsearch by default stores error logs and reports in the tool's directory. Personally I don't like that and would like to disable writing files by default.

Currently, it seems the only way to achieve this is to change the `default.conf` file, also located in the tool's directory. But then, the git repository is dirty, which can potentially lead to conflicts and hinders updates via `git pull`.

If dirsearch continues to write log files per default, I would like to propose adhering to config standards like [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) so we have the option to configure dirsearch outside of the git repository.

(Besides, great work! I especially like that this project also maintains a wordlist that gets updated from time to time)

**Comment by Kr1ss-XD** [comment]
I agree with your proposal @exploide. 

A workaround for the issue with pull conflicts after altering the config _could_ be this workflow, if you're okay with some additional commands :
- edit `default.conf`, remove the "sharp" (comment sign) before `save-logs-home = True`
- before updating, do `git stash`
- update from upstream using `git pull` and
- then re-apply the config setting with `git stash pop`

Although the reports/logs are then saved in `~/.dirsearch` - which as well is not XDG compliant. On the other hand (at least for me) this is better than writing to the app folder.

Btw, if you happen to use Archlinux, there are packages in the AUR - [`dirsearch`](https://aur.archlinux.org/packages/dirsearch/) and [`dirsearch-git`](https://aur.archlinux.org/packages/dirsearch/) - which have the `save-logs-home` option enabled by default (by patching the config file at build time).

**Comment by exploide** [comment]
Thanks for your comment. I'm aware of possible workarounds but wanted to point out what I consider a clean solution. I'm willing to implement this when the maintainer agrees that this change would be appreciated. :)

But also thanks for pointing out that error logs are stored in the one or the other directory. It would be great having the option to disable log files completely.

**Comment by dkasak** [comment]
I'd like to start this off by attempting to document what needs to be done to
consider this implemented. So far, I see two things:

1. dirsearch should attempt to search for its configuration file in the
   `$XDG_CONFIG_HOME/dirsearch` directory, defaulting to `~/.config/dirsearch` if
   `$XDG_CONFIG_HOME` is unset.
2. dirsearch should save its logs under the `$XDG_CACHE_HOME/dirsearch`
   directory by default, defaulting to `~/.cache/dirsearch` if `$XDG_CACHE_HOME`
   is unset.
Is there anything else?

**Comment by Kr1ss-XD** [comment]
I'd say this would be fine, _thx_. :+1:

**Comment by shelld3v** [comment]
Hi, in the latest commit of dirsearch, you can choose wherever the reports should be saved. Is that what you wanted?

**Comment by exploide** [comment]
If I understand correctly, I can only choose that in the `default.conf` file.

That doesn't solve the issue. Because when I need to edit that file, the git repository is dirty afterwards, which can prevent updating.

If you want to keep the behavior of writing log and report files within the repository folder by default, we need a clean way to change configuration. One possibility would be if dirsearch also looks for config files in other locations, e.g. conforming to the [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) standard. We could then have a config file outside of the repository folder, e.g. in `~/.config/dirsearch.conf`.

A typical way to implement that is defining a list of possible locations in the code and searching for the config files one after another. E.g.

- `$repo/default.conf`
- `/etc/dirsearch.conf`
- `$HOME/.config/dirsearch.conf`

And more local files taking precedence over global files, i.e. `$HOME/.config/dirsearch.conf` being more important than `/etc/dirsearch.conf`.

Since the dirsearch default config file already contains a lot of options, it would be great if I wouldn't need to set them all in my personal config file. That means if the files get parsed one after another and only the options I changed override the ones from the default file. So I can keep my own file as small as possible.

**Comment by dkasak** [comment]
But please, don't just those defaults; first try the `$XDG*` variables 
and only use the default locations if those are unset.

**Comment by passgithubtest** [comment]
Hey there, can someone help me with this. 

I want to use dirsearch without any exclusion, means that it will show all possible status code like 404, 426. Basiccaly means not to exclude anything incluse everything. 

I tried with dirseach.conf file like 
# include-status = 1-999
# exclude-status = 0
# exclude-sizes = 0
# exclude-texts = 0
# exclude-regexps = 0 
# exclude-response = 0
# skip-on-status = 0

and also - i 0-999 

please help

**Comment by shelld3v** [comment]
> Hey there, can someone help me with this.
> 
> I want to use dirsearch without any exclusion, means that it will show all possible status code like 404, 426. Basiccaly means not to exclude anything incluse everything.
> 
> I tried with dirseach.conf file like
> 
> # include-status = 1-999
> # exclude-status = 0
> # exclude-sizes = 0
> # exclude-texts = 0
> # exclude-regexps = 0
> # exclude-response = 0
> # skip-on-status = 0
> and also - i 0-999
> 
> please help

This is not possible with dirsearch, if a response is regarded as "wildcard" by dirsearch, it will be excluded from the results no matter what the setting is. You should look for other tools like Burp Intruder, this tool focuses on directory discovery so doing something like you mentioned above wouldn't make sense
