### ISSUE TITLE
Not detecting directory with slash at the end

### ISSUE THREAD

**Issue by zaheer-s** [maurosoria/dirsearch#162]
Some apache servers don't respond with 404 if not searched with / at the end

Server response example
http://x.x.x.x/foldera 
Result : 404

http://x.x.x.x/foldera/
Result: 403 

 Dirsearch (and Gobuster) are not able to search directory on servers which requires a slash at the end

**Comment by shelld3v** [comment]
This the expected behavior, please add `/` into your wordlist

**Comment by shelld3v** [comment]
You can also use `--suffixes /` in your command
