### ISSUE TITLE
[enhancement] Multiple Request methods and bypass cloudflare "Under Attack loading"

### ISSUE THREAD

**Issue by 0xspade** [maurosoria/dirsearch#164]
Hi,

It seems that its only possible to set only one request method at a time using `--http-method` option. Maybe it will be cool if its possible to brute force any directory and also endpoint if we can do multiple http request methods. just like `--http-method=POST,GET,PUT,PATCH,PUT`

use an argument if a site is using cloudflare. since this is a python3 you can use `cfscrape` module

**Comment by shelld3v** [comment]
Hi, got your idea! But I am thinking that, how does the user know if the endpoint was came from GET method or POST method? There is no information about the HTTP method in the status lines and we also don't think about doing that!

```

  _|. _ _  _  _  _ _|_    v0.4.0
 (_||| _) (/_(_|| (_| )

Extensions: php, asp, aspx, jsp, html, htm, js | HTTP method: GET | Threads: 20 | Wordlist size: 39861

Error Log: /home/shelld3v/dirsearch/logs/errors-20-11-15_13-59-01.log

Target: http://example.com/

Output File: /home/shelld3v/dirsearch/reports/example.com/_20-11-15_13-59-01.txt

[13:59:01] Starting:
[13:59:10] 403 -  345B  - /.dep.inc
[13:59:10] 403 -  345B  - /.env~
[13:59:12] 403 -  345B  - /.inc
```
