### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by 687766616e** [maurosoria/dirsearch#165]
```
$ python3 dirsearch.py --plain-text-report -e php,asp,aspx,do,jsp -u "hidden.com.us"
No extension specified. You must specify at least one extension
$
```

**Comment by 687766616e** [comment]
```
$ python3 dirsearch.py --plain-text-report -u "www.hidden.com.us" -e php,asp,aspx,do,jsp
URL target is missing, try using -u <url>
$
```

**Comment by CuriousIncident** [comment]
Usage: dirsearch.py [-u|--url] target [-e|--extensions] extensions [options] -->
python3 dirsearch.py -u www.hidden.com.us -e php,asp,aspx,do,jsp --plain-text-report /root/test
For me there is no bug there, just look at the usage scheme. Options are to be set after the extensions.

**Comment by 687766616e** [comment]
ok...😅(🤔🤔😐
