### ISSUE TITLE
saving the results

### ISSUE THREAD

**Issue by bing0o** [maurosoria/dirsearch#169]
hi,
there's an issue when you scan a list of URLs and save the output into a file , it saves only the last scanned URL's results  into the file , I hope you will fix it soon.

**Comment by z0kk** [comment]
I just started using dirsearch a few days ago and ran into the same thing. At first I thought I was missing something obvious but maybe it _is_ a bug?

In the meantime, I'm just copying the individual reports from the reports directory:

```
subs=$(cat inputfile.txt)
for sub in $subs; do cp ${dirsearchPath}/reports/${sub} .; done
```
