### ISSUE TITLE
errors in the script

### ISSUE THREAD

**Issue by ghost** [maurosoria/dirsearch#170]
Extensions: /Users/banginpadr/Desktop/Webtookit/dirsearch/db/open_redirect_wordlist.txt | HTTP method: get | Threads: 10 | Wordlist size: 6100

Error Log: /Users/banginpadr/Desktop/Webtookit/dirsearch/logs/errors-19-10-02_22-31-29.log
Traceback (most recent call last):
  File "dirsearch.py", line 40, in <module>
    main = Program()
  File "dirsearch.py", line 36, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/Users/banginpadr/Desktop/Webtookit/dirsearch/lib/controller/Controller.py", line 195, in __init__
    self.reportManager.close()
AttributeError: 'Controller' object has no attribute 'reportManager'

im getting these errors. any help please? thank you

**Comment by maurosoria** [comment]
Can you provide more information ? Arguments?

**Comment by kd54726** [comment]
Even I have the same issue when I run the code like this : **python3 dirsearch.py -u https://example.com -e html,js,php,,aspx,xml -R 4 -t 150 -b --plain-text-report=~/Documents/test.txt**

Some time back it didn't have this issue but after a month this error showed up. I tried to reinstalling the program but still the same error

**Comment by maurosoria** [comment]
Couldn't reproduce this problem. Are you sure is the last version?

**Comment by dwisiswant0** [comment]
me too

**Comment by schniggie** [comment]
same here.

**Comment by maurosoria** [comment]
I still cannot reproduce this error. Can you provide additional info?

**Comment by shadihh9** [comment]
me too 
![dire](https://user-images.githubusercontent.com/22076930/89852838-6db03d80-db98-11ea-904a-cf659f23ca4f.png)

**Comment by w2n1ck** [comment]
me too
