### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by attacker34** [maurosoria/dirsearch#180]
Dear @maurosoria 

Can you please add this concept into this tool

Check Page 19 and 20 at

https://i.blackhat.com/us-18/Wed-August-8/us-18-Orange-Tsai-Breaking-Parser-Logic-Take-Your-Path-Normalization-Off-And-Pop-0days-Out-2.pdf

Sincerely,

**Comment by mzfr** [comment]
@attacker34 Can you please specify which part you are talking about?
