### ISSUE TITLE
Add options to parse headers in '--exclude-regexps'

### ISSUE THREAD

**Issue by notdodo** [maurosoria/dirsearch#182]
Hi!

It should be possible to include in the search process also the headers of the response.
For example some application with custom 404 pages can only be scanned using a filter on some header (i.e. Content-Length).

**Comment by shelld3v** [comment]
>For example some application with custom 404 pages can only be scanned using a filter on some header (i.e. Content-Length).

Can you explain more about this?

**Comment by notdodo** [comment]
Hi!

Sorry it's been a long time and I don't know if I recall this issue correctly or it's not applicable in dirsearch.
What I meant was: some site uses a custom page for 404 that respond with a "200 OK" (not a 404 http status) that contains the text "page not found" or some custom header.
What I need to do: I know that the a blank "page not found" has a content-length of 300 (for example); using a regex/flag I'd like ignore all pages with this content-length (any other header),

**Comment by shelld3v** [comment]
I will do this soon for sure. But, I can see that you can use the `--exclude-sizes` flag. Also, by default, dirsearch does an advanced wildcard testing, so probably 200 with a custom 404 page will be filtered!

**Comment by notdodo** [comment]
Ok thank you, I think we can close the issue

**Comment by shelld3v** [comment]
Not yet!
