### ISSUE TITLE
Invalid extensions option selects all extensions

### ISSUE THREAD

**Issue by GoldenBadger** [maurosoria/dirsearch#19]
If you make the extensions option a string the program doesn't recognise, such as `''` or `foo`, it defaults to running searches for all of the extensions in its list. Is this the intended behaviour or should it fail when given invalid extensions? I'd be happy to implement this fix myself once I know what the intended behaviour is.

**Comment by maurosoria** [comment]
Which list? dirsearch only replaces the keyword %EXT% from the dictionary.

Because of that, If you provides '' as extension with the following dictionary:
index.%EXT%

I will try the path:
index.

And that's how it works
