### ISSUE TITLE
timeout error dirsearch

### ISSUE THREAD

**Issue by r03ky** [maurosoria/dirsearch#191]
why im always getting this error, plz help me to resolve this issue.

![Dirsearch issue](https://user-images.githubusercontent.com/13394410/69140292-091df180-0ae4-11ea-8bc9-15abeaece9b4.png)

**Comment by mzfr** [comment]
@r03ky It seems like either you have internet problem or the domain you were trying to scan didn't exist(or didn't allowed `get` request)

**Comment by r03ky** [comment]
thanx Mzfr you were right, it seems like my ip has been blocked by firewall, is there any option to used in order to avoid detection.?

**Comment by DustinTheGreat** [comment]
You can configure it to rotate through proxies.

**Comment by r03ky** [comment]
> 
> 
> You can configure it to rotate through proxies.

Dustin can you show an example of such changes plz

**Comment by DustinTheGreat** [comment]
just the usual way your would use proxies with urllib, Go to /lib/connection/Requester.py and add a list of proxies to cycle through.

**Comment by shelld3v** [comment]
@r03ky Can we close this?

**Comment by DustinTheGreat** [comment]
I

> @r03ky Can we close this?

Id say you can. I have these errors all the time, but its always just another networking issue.
