### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.reports'

### ISSUE THREAD

**Issue by teodem** [maurosoria/dirsearch#193]
Hi guys, using Dirsearch I have this problem:

`starting.asp web dir finished
Traceback (most recent call last):
  File "Module/dirsearch/dirsearch.py", line 26, in <module>
    from lib.controller import *
  File "/Yuki-Chan-The-Auto-Pentest/Module/dirsearch/lib/controller/__init__.py", line 1, in <module>
    from .Controller import *
  File "/Yuki-Chan-The-Auto-Pentest/Module/dirsearch/lib/controller/Controller.py", line 28, in <module>
    from lib.reports import JSONReport, PlainTextReport, SimpleReport
ModuleNotFoundError: No module named 'lib.reports'
fuzzing .asp web dir finished`

Can anyone help? Thx

**Comment by DustinTheGreat** [comment]
What command were you using?

**Comment by teodem** [comment]
I'm using Yuki Chan with Dirsearch module. I found today this, which is actually the same problem as i had: [https://github.com/Yukinoshita47/Yuki-Chan-The-Auto-Pentest/issues/8 ](url)
The folder "reports" is not present in this tool (Yuki), and the project seems to be abandoned since 2y

**Comment by DustinTheGreat** [comment]
So its not a dirsearch issue, thats good. I assume you got it running

**Comment by shelld3v** [comment]
Should we close this

**Comment by DustinTheGreat** [comment]
> Should we close this

Yeah it was probably just a compatibility error with an external program
