### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by dark-warlord14** [maurosoria/dirsearch#198]
will you please add an option to skip the url if too much server error happen or the status code is in between 500-599.
while doing content discovery on say 1000 urls it just slows down. so if we skip some of them it would nicer and speed up the whole process.
great tool btw. i am using it since i started in bug bounty world.
Would really love to know what you think about the feature request

**Comment by shelld3v** [comment]
Hi, this has been implemented with the flag: `--skip-on-status`. So please close this issue!
