### ISSUE TITLE
Unexpected results when scanning with or without extension words in dictionary

### ISSUE THREAD

**Issue by RazviAlex** [maurosoria/dirsearch#199]
Hi,
I have created a personal dictionary.
The dictionary words put are:
```
login
nologin
```
The page I used ends in `..../user/login.jsp`
And I made two tests, the results are:

![image](https://user-images.githubusercontent.com/51793648/70627814-3400ee80-1c27-11ea-9d11-c60e96a95d27.png)

Nothing.. and like I said to get a 200 - OK the url must ends like `..../user/login.jsp` . So in that case the `-e jsp` parameter is not doing nothing, no?.

Next try, add to the same dictionary one more word:
`login.jsp`

And try again the same scan with dirsearch. The results:

![image](https://user-images.githubusercontent.com/51793648/70627995-8f32e100-1c27-11ea-8fd2-786b7d6c1f24.png)

It return 200 - OK correct result. 

So from what I see, to find the correct directory, the **word** has to be put in the dictionary along with the extension **.jsp**. 
So what is `-e .jsp` for? It is unnecessary if always it must be specify in the dictionary the word with .jsp extension. 

I appreciate any help. Thanks!

**Comment by machinexa2** [comment]
Yes i have a same problem

**Comment by machinexa2** [comment]
@RazviAlex  i have same problem, the -e argument is just for show

**Comment by shelld3v** [comment]
@RazviAlex It must be `login.%EXT%` and `nologin.%EXT%`.

**Comment by shelld3v** [comment]
If you don't want to add `%EXT%` into your wordlist, then you can add the `-f` flag in the command.
```
login
nologin
```
==>
```
login
login.jsp
login/
nologin
nologin.jsp
nologin/
```

**Comment by shelld3v** [comment]
Add the `-f` flag plz. Then close this issue
