### ISSUE TITLE
Incorrect Wordlist size count?

### ISSUE THREAD

**Issue by estebancano-dev** [maurosoria/dirsearch#200]
Extensions: json, js | HTTP method: get | Threads: 20 | Wordlist size: **18**

and my wordlist has **6** lines.

Is dirsearch appending empty extension (so i get **18**) ? or it has to be **12**?

Gracias mauro!

**Comment by bug-hunter-karna** [comment]
Same problem with mine! I'm giving the path to my wordlist in -w parameter. My wordlist is of 39k lines but dirsearch is only taking wordlist size as 21k. Why is this happening?

**Comment by yeroc-sebrof** [comment]
Can you run `cat WORDLIST | sort | uniq | wc -l` and compare with `cat WORDLIST | wc -l`

**Comment by maurosoria** [comment]
@estebancano-dev did you solve your problem?

**Comment by estebancano-dev** [comment]
La verdad no probé, tampoco era un problema, solo algo que vi y me pareció
bien reportarlo x si era un error. Cerralo si querés! Abrazo

**Comment by shelld3v** [comment]
I don't see this is a bug. We can close this now @maurosoria!

**Comment by shelld3v** [comment]
Can you close this?
