### ISSUE TITLE
Handle 429 Errors [ Feature Request ]

### ISSUE THREAD

**Issue by ctrlsam** [maurosoria/dirsearch#201]
The `429` error (too many requests) could be handled by slowing down requests / some sort of rate limit calculator. Or could just notify the user that there is rate limiting and they should use the `-s DELAY` option.

**Comment by chowmean** [comment]
Hi, Any discussion regarding this happened anywhere I want to take this up.

**Comment by shelld3v** [comment]
#504

**Comment by shelld3v** [comment]
Hi @ctrlsam 🖐️, This feature has been implemented in the latest version. You can close this issue now!

**Comment by shelld3v** [comment]
Please close this!!!

**Comment by shelld3v** [comment]
Hi, can you close this issue Sam?

**Comment by ctrlsam** [comment]
> Hi, can you close this issue Sam?

Yep will do, sorry I missed you message before :)
