### ISSUE TITLE
[Feature Request] Report files and directories found in crawled file

### ISSUE THREAD

**Issue by LoHub** [maurosoria/dirsearch#204]
First of all, thank you for this wonderful tool which is the first that I use on CTF.
I would like to know if it possible to add the ability to dirsearch to parse crawled file to extract and report present path and use it for recursive searching.
To avoid massive report, Dirsearch should only report files of the targeted domain and in targeted root folder.
Thank you

**Comment by shelld3v** [comment]
Yeah, always has been :) Can you check if we have done what you said?

**Comment by maurosoria** [comment]
He means that actually crawl the discovered paths, then parse those links to add them to the recursion queue

And that's not currently supported. But it's a feature that much people asked me to add..
