### ISSUE TITLE
--timeout unit is s or ms?

### ISSUE THREAD

**Issue by possib1e** [maurosoria/dirsearch#205]
Hi, the default setting is below, what is the unit of timeout, for one link(like http://target.com/1.jsp) or for one target(http://target.com)?
#timeout = 30
#max-retries = 5

Thanks.

**Comment by dostoevskylabs** [comment]
seconds

**Comment by shelld3v** [comment]
Seconds, apply for any request sent in the scan, include both http://target.com and http://target.com/FUZZ. Please close this issue if it has answered your question
