### ISSUE TITLE
Не работает!

### ISSUE THREAD

**Issue by MrDmitry1107** [maurosoria/dirsearch#216]
![Снимок экрана от 2020-02-11 08-56-43](https://user-images.githubusercontent.com/54665743/74213956-82c11800-4cac-11ea-98b8-b464c6235414.png)

**Comment by linxon** [comment]
![Selection_141](https://user-images.githubusercontent.com/8144644/74215053-d59cce80-4cb0-11ea-8bdc-236aa5f27627.jpg)


P.S.
close it

**Comment by MrDmitry1107** [comment]
А что за EXTENSIONS?

**Comment by shelld3v** [comment]
@MrDmitry1107 Extensions here are file extensions, like `php`, `jsp`, `html`, `js`, `txt`, `py`, `asp`, `aspx`, ... You can try `dirsearch.py -u http://website.com -e php,html,asp,jsp`. It will replace all `%EXT%` in the wordlist with your extensions, like `admin.php`, `admin.html`, ... You need to learn more English and hacking to can understand and use more dirsearch options
