### ISSUE TITLE
-L options and --plain-text-report conflict

### ISSUE THREAD

**Issue by cwkiller** [maurosoria/dirsearch#219]
I use this command
python3 dirsearch.py -L gh.txt -e php -x 403,400 -t 20 --plain-text-report=1.txt
gh.txt  There are two domain
--plain-text-report=1.txt  result only the last domain

**Comment by maurosoria** [comment]
https://github.com/maurosoria/dirsearch/issues/105

**Comment by shelld3v** [comment]
Close this?

**Comment by shelld3v** [comment]
Fixed
