### ISSUE TITLE
Detecting invalid http codes and reacting to them sensibly

### ISSUE THREAD

**Issue by Viss** [maurosoria/dirsearch#222]
occasionally, I'll encounter a host that throws a 'page not found' page, but the return code is a 200 for some reason, so it would make a lot of sense for dirsearch to try some random garbage URI first to see what the "Actual error from the webserver is", even if the http return code is 200, and compare that page, or at least its headers, to the result of the actual test to see "is what I'm seeing the same as a known bad result"

I keep getting output texts of, like, 500,000 "http 200s", because the webserver has "nothing" on it, the "error" page returns http 200, and dirsearch thinks that literally every entry in my dictionary is there because the admin for the webserver doesnt understand how to http :D

**Comment by Viss** [comment]
bump?

**Comment by shelld3v** [comment]
@Viss dirsearch has already done that. Before brute-forcing, dirsearch will send 2 requests with 2 invalid paths, like `NjdfoEDI73F4kWis8j42n` (I don't remember what actually is), then check other responses if any of them has the same response with 2 first requests, it will throw away, even it's 200, 301, 302 or anything else.

**Comment by Viss** [comment]
oh, fantastic!

**Comment by shelld3v** [comment]
```
127.0.0.1 - - [01/Sep/2020 22:22:11] "GET / HTTP/1.1" 403 -
127.0.0.1 - - [01/Sep/2020 22:22:11] "GET /TIhgH725gAX4 HTTP/1.1" 404 -
127.0.0.1 - - [01/Sep/2020 22:22:11] "GET /Frlp2NXrnlTK/ HTTP/1.1" 404 -
127.0.0.1 - - [01/Sep/2020 22:22:11] "GET /c2enZzHTTa6o.js HTTP/1.1" 404 -
127.0.0.1 - - [01/Sep/2020 22:22:11] "GET /IAkOEasE78cA.html HTTP/1.1" 404 -
127.0.0.1 - - [01/Sep/2020 22:22:11] "GET /ztshN4lKpuht.txt HTTP/1.1" 404 -
127.0.0.1 - - [01/Sep/2020 22:22:11] "GET /a9xRKxLBltpV.xml HTTP/1.1" 404 -
127.0.0.1 - - [01/Sep/2020 22:22:11] "GET /ygQEZdF31hZh.asp HTTP/1.1" 404 -
127.0.0.1 - - [01/Sep/2020 22:22:11] "GET /HYapLPk2jJiG.php HTTP/1.1" 404 -
```

**Comment by shelld3v** [comment]
Close this? 👽 🦊 🐵 🐶 🐱
