### ISSUE TITLE
SSL Error connecting to server Try the -b flag to connect by host name 

### ISSUE THREAD

**Issue by hello13211** [maurosoria/dirsearch#224]
Hello can someone help me with this issue ? 

I installed python , Dirsearch tool on E drive 

I am using this tool on Windows 10 

I used this tool on kail Linux and everything is okay but I would like to use it on Windows 

Thank you

**Comment by cyb3rsalih** [comment]
I run dirsearch on MacOS 10.14.6. Same error here also.
I have to use http... for get rid of error. But this is not the solution.

**Comment by hello13211** [comment]
I already solved the problem, I think you need to add -h

**Comment by shelld3v** [comment]
LOL all you need is adding the `-b` flag!

**Comment by hello13211** [comment]
Yes -b I was WRONG on my previous email (-h)

**Comment by shelld3v** [comment]
You can close this now!
