### ISSUE TITLE
suggestion to add new argument

### ISSUE THREAD

**Issue by Sy3Omda** [maurosoria/dirsearch#230]
i see in many tools allowing to brute force dir with word-lists OR even word against multiple urls .
for example i need to test 'admin.php' for list of hosts.
so could we add for example argument (-W) capital to allowing bruteforce for one path

**Comment by shelld3v** [comment]
@Sy3Omda You can try with Tomnomnom's `meg` instead. This is a directory brute-forcing tool, not host brute-forcing, that feature is so much more different from the purpose of the tool, so it should be a new tool for sure, can't merge with `dirsearch`
