### ISSUE TITLE
Processes In Containers Should Not Run As Root

### ISSUE THREAD

**Issue by stegamjay** [maurosoria/dirsearch#231]
Dear Maintainer,

Processes In Containers Should Not Run As Root
https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b

for better docker security, run process as user ?

Tanks

**Comment by shelld3v** [comment]
dirsearch is not going to hack or steal personal information in your computer surely 🤣 🤣 🤣
