### ISSUE TITLE
Fail to access http://www.xxxx.cn/

### ISSUE THREAD

**Issue by xxsmile123** [maurosoria/dirsearch#234]
python3 JSFinder.py --request-by-hostname -u http://www.xxxx.cn/
usage: JSFinder.py [-h] [-u URL] [-c COOKIE] [-f FILE] [-ou OUTPUTURL] [-os OUTPUTSUBDOMAIN] [-j] [-d]
JSFinder.py: error: unrecognized arguments: --request-by-hostname

**Comment by mzfr** [comment]
@xxsmile123 what is JSFinder.py? In which folder did you find it?

**Comment by shelld3v** [comment]
@xxsmile123 This is `dirsearch`, not `JSFinder`. Please report your problem [here](https://github.com/Threezh1/JSFinder)
