### ISSUE TITLE
strange report files

### ISSUE THREAD

**Issue by eth481642** [maurosoria/dirsearch#24]
When program finished scanning, report file have a big size(for example 15 kb(but actually report have 10-15 lines itself)) and i cant open it with any graphical editor, but when i read report file using cat - it prints normal
OS - GNU/Linux

**Comment by maurosoria** [comment]
Yes, I'm having the same problem. I'll try to fix it.

Thanks

**Comment by maurosoria** [comment]
pull the last version and tell me if it's fixed

**Comment by eth481642** [comment]
yes,it works fine
thanks a lot
