### ISSUE TITLE
TypeError: config() takes 8 positional arguments but 9 were given

### ISSUE THREAD

**Issue by 4V4loon** [maurosoria/dirsearch#240]
Kali:~/dirsearch$ sudo python3 dirsearch.py -u http://10.10.10.28 -e php

 _|. _ _  _  _  _ _|_    v0.3.9
(_||| _) (/_(_|| (_| )

Traceback (most recent call last):
  File "dirsearch.py", line 40, in <module>
    main = Program()
  File "dirsearch.py", line 36, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/home/isi/dirsearch/lib/controller/Controller.py", line 125, in __init__
    self.printConfig()
  File "/home/isi/dirsearch/lib/controller/Controller.py", line 233, in printConfig
    self.output.config(
TypeError: config() takes 8 positional arguments but 9 were given

**Comment by d0n601** [comment]
Getting same error now, haven't had it in the past.

**Comment by jgrobbins** [comment]
I have the same error as well

**Comment by maurosoria** [comment]
Hello guys,

I've accepted a few pull requests today and I haven't finished the modifications yet.

Try getting the latest version from here https://github.com/maurosoria/dirsearch/releases

**Comment by evilgurren** [comment]
In lib/output/CLIOutput.py  line 176
There is a missing parameter "suffixes".

And in lib/controller/Controller.py line 373
There is also a missing parameter "self.batch"

**Comment by ftk-sostupid** [comment]
dirsearch/lib/controller/Controller.py 
```
        self.output.config(
            ', '.join(self.arguments.extensions),
            ', '.join(self.arguments.suffixes),
            str(self.arguments.threadsCount),
            str(len(self.dictionary)),
            str(requestCount),
            str(self.httpmethod),
            self.recursive,
            str(self.recursive_level_max),
        )
```
Look at the last ‘,’.

**Comment by ic32k** [comment]
Same issue here.... And don't know what element add to the function to handle 9 arguments

**Comment by shikhar2816** [comment]
I am also getting this same issue just please fix this issue.

**Comment by AEROBATlCS** [comment]
Hi codders and dear [maurosoria](https://github.com/maurosoria).
I've got the same errors after system(Win10x64) updating.
Hope maurosoria fix this syntax problem soon.
Best wishes!

**Comment by billpappas77** [comment]
I had the same issue, using the source code from: https://github.com/maurosoria/dirsearch/releases it worked for me

**Comment by 4V4loon** [comment]
Working All Thanks!
