### ISSUE TITLE
Dirserach doesnt perform recursive dirsearch on 403 Error

### ISSUE THREAD

**Issue by machinexa2** [maurosoria/dirsearch#242]
Lets say there's a CTF in which you get 403 error dir however there is one file called shit.txt in which is 200 OK 
however it doesnt perform recursive test when 403 error is shown. 
Like 
in 
localhost/admin (403 ERROR)
localhost/admin/200OKFILE.html (200 OK)
if i do two dirsearch one `dirsearch.py -u localhost/ ..... -r -R 10` and another `dirsearch.py -u localhost/admin ..... -r -R 10`
however a single command should find all directory

**Comment by machinexa2** [comment]
Even it doesnt perform recursion on 200 ok sites 
![image](https://user-images.githubusercontent.com/60662297/85684767-222bf800-b6ee-11ea-9531-3dd752b7223e.png)

**Comment by shelld3v** [comment]
This is the expected behavior. Usually, 200 means you have hit the correct file and not folder, so brute-force after it will get 404. In this situation, you must perform recursion by your-self.

**Comment by shelld3v** [comment]
Also, dirsearch only perform recursion on endpoints that end with `/`. For example, `admin/`
