### ISSUE TITLE
Syntax error: invalid syntax

### ISSUE THREAD

**Issue by heru** [maurosoria/dirsearch#244]
Hi,
this error occured when using master branch:

Traceback (most recent call last):
  File "dirsearch.py", line 27, in <module>
    from lib.controller import *
  File "/home/heru/sec-tools/dirsearch/lib/controller/__init__.py", line 1, in <module>
    from .Controller import *
  File "/home/heru/sec-tools/dirsearch/lib/controller/Controller.py", line 330
    directoryPath = FileUtils.buildPath(self.savePath, 'reports', f'{requester.protocol}_{requester.host}_{requester.httpmethod}')
                                                                                                                                ^
SyntaxError: invalid syntax

env: Linux 4.4.0-184-generic #214-Ubuntu
python: python3.5.2

**Comment by maurosoria** [comment]
Hello @heru ,

Fetch the latest version from git. If you still with trouble tell me which settings are you using.

Regards,
Mauro

**Comment by steampixel** [comment]
@maurosoria Hi,
I am currently facing similar trouble. I just fetched the latest Version from git today (0.3.9). Then I build the latest docker image using

`sudo docker build -t "dirsearch:v0.3.9" .`

Then I tried to scan my own website using this command

`sudo docker run -it --rm "dirsearch:v0.3.9" -u https://steampixel.de/ -E`

But then the following error occurs. I don't changed any configuration.

```
Traceback (most recent call last):
  File "/root/dirsearch.py", line 28, in <module>
    from lib.output import *
  File "/root/lib/output/__init__.py", line 1, in <module>
    from .CLIOutput import *
  File "/root/lib/output/CLIOutput.py", line 182
    suffixes.
            ^
SyntaxError: invalid syntax
```
I am using Docker version 19.03.6 on Umbuntu 18.04.4 LTS (Bionic Beaver)

**Comment by shelld3v** [comment]
Hi @steampixel, sorry for this, this is my fault. Please wait a little bit for the author to merge the fix.

**Comment by RootUp** [comment]
Replace `suffixes.` with `suffixes,` on file **CLIOutput.py** (line number 182).

**Comment by shelld3v** [comment]
I have already done that 3 hours ago, 3 minutes after the steampixel's comment: https://github.com/maurosoria/dirsearch/pull/320
