### ISSUE TITLE
default report output is not working 

### ISSUE THREAD

**Issue by vishnurajkv** [maurosoria/dirsearch#245]
{requester.protocol}_{requester.host}_{requester.httpmethod}

**Comment by noraj** [comment]
![image](https://user-images.githubusercontent.com/16578570/85993560-cebfef80-b9f6-11ea-9d7f-f304e18abc5e.png)

**Comment by shelld3v** [comment]
Hi, can you guys check again with the dirsearch latest version? If the error is still there, let me know and I will fix it!

**Comment by vishnurajkv** [comment]
Yes, it is fixed! :)

**Comment by shelld3v** [comment]
Can you close this please!

**Comment by vishnurajkv** [comment]
sure. :)
