### ISSUE TITLE
--proxy option ignored

### ISSUE THREAD

**Issue by noraj** [maurosoria/dirsearch#246]
The proxy option is always ignored, nothing come through the proxy.

The help message is saying:

```
    --proxy=HTTPPROXY, --http-proxy=HTTPPROXY
                        Http Proxy (example: localhost:8080
```

So I tried all those:

```
dirsearch -u https://example.org/ -e txt --proxy 127.0.0.1:8080
dirsearch -u https://example.org/ -e txt --proxy=127.0.0.1:8080
dirsearch -u https://example.org/ -e txt --proxy http://127.0.0.1:8080
dirsearch -u https://example.org/ -e txt --http-proxy 127.0.0.1:8080
```

PS: I tried with ffuf proxy option and it works, so it's not a proxy issue from my side.

**Comment by shelld3v** [comment]
Can you retry and give us more info about the reproduce steps?

**Comment by noraj** [comment]
I had burp listener binding on 127.0.0.1:8080, then I tried to do whatever enumeration with dirsearch but using `--http-proxy` so the requests should all be passing through the proxy but instead it was still enumerating directly without using the proxy.

**Comment by shelld3v** [comment]
Can you recheck again? You tried with `--http-proxy localhost:8080` or `--http-proxy https://localhost:8080`?

**Comment by noraj** [comment]
Both and more:

![image](https://user-images.githubusercontent.com/16578570/94671756-904b1100-0314-11eb-9683-100cae90d1a8.png)

**Comment by shelld3v** [comment]
I can't reproduce your problem, everything is working as intended on my side. Have you installed the latest version of dirsearch?

**Comment by noraj** [comment]
I retried

- :heavy_check_mark: `dirsearch -u https://example.org/ -e txt --proxy 127.0.0.1:8080`
- :heavy_check_mark: `dirsearch -u https://example.org/ -e txt --proxy=127.0.0.1:8080`
- :heavy_check_mark: `dirsearch -u https://example.org/ -e txt --proxy http://127.0.0.1:8080`
- :heavy_check_mark: `dirsearch -u https://example.org/ -e txt --http-proxy 127.0.0.1:8080`
- :heavy_check_mark: `dirsearch -u https://example.org/ -e txt --http-proxy http://127.0.0.1:8080`

I must have been fixed between the moment when the bug was opened (June 2020) and the moment of your first reply (September 2020).
