### ISSUE TITLE
Remove leading NULL character from JSON report files

### ISSUE THREAD

**Issue by Doctor-love** [maurosoria/dirsearch#25]
For some reason, dirsearch begins all JSON report files with a bunch of NULL characters.
This confuses some JSON decoders, like the one included in Python.

**Comment by maurosoria** [comment]
duplicate of https://github.com/maurosoria/dirsearch/issues/24

**Comment by maurosoria** [comment]
pull the las version and tell me if it's fixed

**Comment by Doctor-love** [comment]
Looks much better - thanks a lot!
