### ISSUE TITLE
--exclude-texts= not working

### ISSUE THREAD

**Issue by Phoenix1112** [maurosoria/dirsearch#251]
hello.. i am using this param --exclude-texts=phpMyAdmin . but despite the target site is the phpmyadmin login page, it shows no results. Although phpMyAdmin is in the source code of the target site, it cannot find dirsearch.

**Comment by IslaIDK** [comment]
i did pull request for this issue 
till they fix it just go to /lib/core/ArgumentParser.py and go to line 288 and add this 
self.excludeTexts = config.safe_get("general", "exclude-texts", None)

**Comment by shelld3v** [comment]
@Phoenix1112 The problem is now resolved, please close this! (Also remember to re-install `dirsearch` to see the fix)
