### ISSUE TITLE
Str not callable error when use printoutput

### ISSUE THREAD

**Issue by ProxyErgo** [maurosoria/dirsearch#252]
In lib/output/PrintOutput.py target function 
```
def target(self, target):
        self.target = target
```
this will rewrite target function to str and after first use in Controller.py (in multi url) ,it will cause an error.

**Comment by shelld3v** [comment]
You can open a pull request for this

**Comment by shelld3v** [comment]
@ProxyErgo No, this is not a problem! What you are wrong here is that `self.target` is a variable and `self.target()` is a function, actually a function call, the difference between function and variable is the `()`. The fact that we even can't edit a function in python manually:

```python3
>>> def test():
...     print(1)
...
>>> test() = 1
  File "<stdin>", line 1
SyntaxError: can't assign to function call
>>>
```

Thank you for your help, if everything has been done, then you can close this!!!
