### ISSUE TITLE
Can I test 10 URLs at the same time

### ISSUE THREAD

**Issue by sanqiushu-ns** [maurosoria/dirsearch#254]
Can I test 10 URLs at the same time。10 threads per URL😋

**Comment by shelld3v** [comment]
Then your computer will open around 100 threads, able to DoS in some computers 😆 You can try `--clean-view` instead, can't test all URLs at the same time but will make a better output when brute-force a list of URLs. 
And if you still want that feature, try to open 10 terminals and run dirsearch in each of them 😬 😁

**Comment by its0x08** [comment]
Tmux will help on that!
Just 1 terminal needed 🙌🏻
