### ISSUE TITLE
Dont't search Suffixes on scan

### ISSUE THREAD

**Issue by fallfur** [maurosoria/dirsearch#256]
When you run the option "-e" or "--extensions" the tool does not look for these extensions, it is reflected in the proxy burpsuite, i need a dependency or something? I try with --thread 10, 1 and 50

![2020-07-17_16-56](https://user-images.githubusercontent.com/46113075/87800235-6d997800-c84e-11ea-9cd4-094957225da2.png)

![image](https://user-images.githubusercontent.com/46113075/87800282-7f7b1b00-c84e-11ea-91b8-811c68da8a91.png)

**Comment by yogeshojha** [comment]
Happens with me as well, I was also about to raise this issue. 

I am running dirsearch inside docker when I run simple 

`python3 /app/tools/dirsearch/dirsearch.py -u https://something.com -w db/dicc.txt -e php,txt -t 100`

This considers PHP and txt extensions as the suffix. But when I add `--suffix php,txt` it takes php and txt as both extension and suffix. 

which will result in 

admin.phpphp
admin.phptxt

Something like this

**Comment by yogeshojha** [comment]
Also, this doesn't happen in the older version of dirsearch. I had cloned it to another directory a month back, that version seems to work as expected.

**Comment by sirgustavx** [comment]
@fallfur, the list must have the special word %EXT%. Like this:

```ascii
this.%EXT%
is.%EXT%
a.%EXT%
test.%EXT%
```

You can also use -f | --force-extensions switch to append extensions to every word in the wordlists.

See more at https://github.com/maurosoria/dirsearch/blob/master/README.md in "About wordlists".

**Comment by shelld3v** [comment]
Hi @fallfur and @yogeshojha, 

I'm so sorry for this inconvenience. This actually is a bug and we have fixed it. Can you recheck?

Thanks

**Comment by fallfur** [comment]
I have the same issue, but with the default wordlist it works well, but with an external wordlist don't try suffixes.

![photo_2020-09-23_11-28-26](https://user-images.githubusercontent.com/46113075/93994950-b7dc2f80-fd90-11ea-97cb-2914dd77f23c.jpg)
![photo_2020-09-23_11-28-31](https://user-images.githubusercontent.com/46113075/93994975-bb6fb680-fd90-11ea-907f-f7e9bc3b318d.jpg)

**Comment by shelld3v** [comment]
Add `-f` please!

**Comment by fallfur** [comment]
Oh! Thats it! Sorry master, now it goes well! Nice job!
