### ISSUE TITLE
SSL Error connecting to server. Try the -b flag to connect by hostname

### ISSUE THREAD

**Issue by mikely22** [maurosoria/dirsearch#263]
SSL Error connecting to server. Try the -b flag to connect by hostname

Please can you explain me to what way to fix this issue Thanks

**Comment by shelld3v** [comment]
Add the -b flag and then close this issue 🌝

**Comment by maurosoria** [comment]
I should scan the server for a WAF to do this. The problem is that requests does not cache the DNS by default, and that impacts the performance.

**Comment by shelld3v** [comment]
Hi @mikely22, can you retest with the latest commit of dirsearch?
