### ISSUE TITLE
--http-method no such option

### ISSUE THREAD

**Issue by qran253** [maurosoria/dirsearch#266]
![image](https://user-images.githubusercontent.com/29623610/90642184-1f0f3d00-e243-11ea-959c-eb2570146f44.png)

--http-method no such option

**Comment by shelld3v** [comment]
Are you sure you are using the latest version? Try to re-download/re-git dirsearch again to have the latest version

**Comment by shelld3v** [comment]
Done? If yes, then you can close this ❤️
