### ISSUE TITLE
Can't brute-force with `../` or `./` in the URL

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#272]
I can't brute-force with any URL like this: `https://yahoo.com/../` which contains `../` (or `./`) in the path to bypass 403 sometimes. It will send requests to `https://yahoo.com/admin` rather than `https://yahoo.com/../admin` when brute-forcing
What I want is `GET /../admin HTTP/1.1` but the result is different: `GET /admin HTTP/1.1`. Can you fix it?

**Comment by maurosoria** [comment]
https://github.com/psf/requests/issues/1454 ?

**Comment by shelld3v** [comment]
I don't understand what do you mean. I am not talking about URL encoding, I mean I brute-forced with this command `dirsearch.py -u http://localhost:4444/../ -e php`, and my server received:

```
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /.AppleDB HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /.CSV HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /.CVS HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /.DS_Store HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /.LOCAL HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /.LSOverride HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /.SyncID HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /.SyncIgnore HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /.Trash HTTP/1.1" 404 -
```
It supposed to be:

```
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /../.AppleDB HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /../.CSV HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /../.CVS HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /../.DS_Store HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /../.LOCAL HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /../.LSOverride HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /../.SyncID HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /../.SyncIgnore HTTP/1.1" 404 -
127.0.0.1 - - [31/Aug/2020 15:13:58] "GET /../.Trash HTTP/1.1" 404 -
```

**Comment by maurosoria** [comment]
Requests automatically try to resolve to a full no-relative path. So even if you try to do that, requests will transform the query.

That's why you need a little patch.

https://github.com/psf/requests/issues/1454

**Comment by shelld3v** [comment]
Hey, I don't know why but this works in dictionary.py but doesn't in my local machine. I ran a quick test:

```python
import urllib.parse
import requests

url = urllib.parse.quote('http://127.0.0.1:4444/../test', safe=':./')
requests.get(url)
```

And it didn't know. Can you help me out?

**Comment by shelld3v** [comment]
The same with this code:

```python
import urllib.parse
import requests

url = 'http://127.0.0.1:4444/./test'
url = urllib.parse.unquote(url)
url = urllib.parse.quote(url, safe=':./&=')
requests.get(url)
```

**Comment by shelld3v** [comment]
The fact that this works good in python 2, with `urllib.quote` instead of `urllib.parse.quote`:

```python
# python 2
import urllib
import requests

url = 'http://127.0.0.1:4444/./test'
url = urllib.unquote(url)
url = urllib.quote(url, safe=':./&=')
requests.get(url)
```

**Comment by shelld3v** [comment]
Sad sad =(

- psf/requests#5289
- https://mazinahmed.net/thoughts/testing-for-path-traversal-with-python/
