### ISSUE TITLE
Fix log path for Debian Package 

### ISSUE THREAD

**Issue by drego85** [maurosoria/dirsearch#28]
Hi Mauro,
I'm a developer of BackBox Linux. Remember?! :D

Now the software will automatically generate the log, to create a correctly Debian package would be appropriate that the logs were generated in the user's folder.

Otherwise the script must be executed with the permissions of SUDO. Otherwise it generates the error "Permission denied: '/usr/share/DirSearch/logs".

You can change the log salvage path? In Python you can use: os.path.expanduser ("~")

Thanks
Andrea

**Comment by maurosoria** [comment]
Get the last version from master branch, modify the default.conf and uncomment the following line:

#save-logs-home = True

Give it a try and let me know if it's working
