### ISSUE TITLE
Offer the possibility to use language-specific dictionaries

### ISSUE THREAD

**Issue by benji1000** [maurosoria/dirsearch#29]
Hello and thank you for this tool!

I was wondering if you could implement a system that would allow us to use dictionaries specific to a language. For example, dirseach could by default work on a common dictionary (with strings like .svn, .git, backup, etc) as well as an English dictionary (with strings like schedule, gallery...), and we could also add an option in the command line (for example, --language ISOCODE) to test for language-specific strings from dictionaries located in the db/ folder (for example, db/dicc_ISOCODE.txt).

Thank you for your answer.

**Comment by maurosoria** [comment]
Yes, it's a good idea. I'm planning to add some sort of wordlist template engine. I'll try to finish that new feature soon.

**Comment by shelld3v** [comment]
Splitting wordlist entries by language is impossible, and even possible, not worth to implement
