### ISSUE TITLE
[Suggestion] Headers from file

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#292]
Use `--ratelimit-bypass-headers` flag will add "bypass rate limiting" headers into outgoing requests, those headers are:
```
X-Originating-IP: 127.0.01
X-Forwarded-For: 127.0.01
X-Remote-IP: 127.0.01
X-Remote-Addr: 127.0.01
X-Client-IP: 127.0.01
X-Host: 127.0.01
X-Forwared-Host: 127.0.01
True-Client-IP: 127.0.01
```

I think the workflow is simple, in **ArgumentParser.py**, add a new argument called `--ratelimit-bypass-headers`, if the flag is used, then we will add those headers (above) in to `options.headers`

**Comment by cwkiller** [comment]
Suggestion add a random X-Forwarded-For headers argument bypass waf

**Comment by maurosoria** [comment]
Shouldn't be better something like --header-list headers.txt ?

**Comment by shelld3v** [comment]
Lol that is awesome !!! I will do it 😎

**Comment by chowmean** [comment]
Hi, what was the decision here?  I want to take this up if possible.

**Comment by shelld3v** [comment]
The decision is to create an option that can take headers from a file

**Comment by chowmean** [comment]
Awesome I will be working on it. @shelld3v
