### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by user87983** [maurosoria/dirsearch#324]
in this file : lib/output/CLIOutput.py
there is a syntax error in the line 182
 181:    extensions,
 182:    suffixes.
 183:    threads,

replace the . with ,

**Comment by shelld3v** [comment]
Hi, sorry for this inconvenience. I have requested a fix for this already but still waiting for the author to merge it, thank you for your help!

**Comment by bradleman** [comment]
Just found this and was going to report.

**Comment by shelld3v** [comment]
Everything has been fixed, you now can close this!
