### ISSUE TITLE
Exclude by "x in string" instead of exact dirname?

### ISSUE THREAD

**Issue by dwendt** [maurosoria/dirsearch#33]
Hey,

Often times you'll get a series of dirnames that return garbage. Sometimes they'll look like:

/offers-orlando/
/offers-mexico/
/offers-newyork/

etc..

What would be the best way to be able to exclude these sorts of directories? I'm opening an issue because I'd like other thoughts. I'm not sure if there should be an exclude by regex or exclude by simply checking for a substring in the path. Thoughts?

**Comment by maurosoria** [comment]
There is no such option in dirsearch. 

In those cases I go to the "reports" folder and use the "grep" command to look for what I want. And if I want to do it while dirsearch is running, I "tail -f" the report file.
