### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by Miserlou** [maurosoria/dirsearch#34]
This would make a great addition to PyPI! Please add a setup.py file and publish this project so that it can be installed through pip!

**Comment by maxvonhippel** [comment]
I think this is on PyPi.  If that is the case then this issue should be closed.  (I say I think because I ran pip install dirsearch on Pythonista on my iPhone in stash and it worked, but I haven't thoroughly checked on a real computer).

**Comment by maurosoria** [comment]
maxvonhippel, the dirsearch in PyPi is a different project

**Comment by shelld3v** [comment]
Wait, that guy stole our tool name in PyPi, is that illegal?

**Comment by shelld3v** [comment]
Done
