### ISSUE TITLE
%EXT% in dictionary

### ISSUE THREAD

**Issue by szeghybarna** [maurosoria/dirsearch#35]
Please document somewhere this. It took me half day to realize, I need to add %EXT% on line endings in dictionary file to check extensions. Please...

**Comment by maurosoria** [comment]
I updated the readme with the note

**Comment by szeghybarna** [comment]
Thanks!
By the way, if you use **example%EXT%** and add **/** to extensions, it can be one line in dict.

**Comment by maurosoria** [comment]
No problem dude, you're welcome.

Yes, I did it on purpose because I thought it's more hackable this way and you can use it the way you want. What if you want to use the passed extensions at the begining or in the middle of the word? You can't do that in the other way...
