### ISSUE TITLE
lib/controller/Controller.py line 441 is a bug

### ISSUE THREAD

**Issue by dc198488** [maurosoria/dirsearch#353]
line441-447:
`  excludeRegex = re.compile(excludeRegexp)

                for excludeRegexp in self.excludeRegexps:

                    if (
                        excludeRegex.search(path.response.body.decode())
                        is not None`

maybe is:
`  

                for excludeRegexp in self.excludeRegexps:
                    excludeRegex = re.compile(excludeRegexp)
                    if (
                        excludeRegex.search(path.response.body.decode())
                        is not None`

**Comment by shelld3v** [comment]
Sorry about that!!! I have already created a pull request for the fix a few hours ago

**Comment by shelld3v** [comment]
Hi, this problem has been fixed, you can close it now

**Comment by dc198488** [comment]
thanks
