### ISSUE TITLE
Release dirsearch v0.4.0

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#360]
Please release dirsearch v0.4.0 now. I can edit the README for you! Remember to add as many new updates as you can, with detailed information. Bugs, speed, new options, ...

**Comment by maurosoria** [comment]
Hello @shelld3v ,

I will do it soon. Generally, I wait a couple of days for testing purposes before drafting a new release. Let's wait a couple of days to check if it's everything right and then I will do it.

Thanks =)

**Comment by shelld3v** [comment]
Is it OK now?

**Comment by maurosoria** [comment]
Let's prepare the draft to be released in the next two days. Would you want write the change log?

**Comment by shelld3v** [comment]
Maybe 💭

**Comment by shelld3v** [comment]
Changelog:

- Exclude extensions argument added
- Added custom prefixes and suffixes
- No dot extensions option
- Lowercase and uppercase wordlist
- Support HTTP request data
- Added minimal response length and maximal response length arguments
- Added include status codes and exclude status codes arguments
- --clean-view option added
- Added option to print the full URL in the output
- Multiple bugfixes

There are some more, but I can't remember!

**Comment by maurosoria** [comment]
Done ^_^

**Comment by shelld3v** [comment]
Thank you so much!!!
