### ISSUE TITLE
redirect path for 3** codes in json

### ISSUE THREAD

**Issue by hollow1** [maurosoria/dirsearch#37]
Hi!
Why does the redirect path exist in console output:
301 -    0B  - /.CSV  ->  http://website/csv-parser/
And does not exist in json:
 { "content-length": 0, "path": "/.CSV", "status": 301 }
Can you update this?

**Comment by maurosoria** [comment]
Upgrade your version and give it a try

**Comment by hollow1** [comment]
Nice, thanks a lot!!
