### ISSUE TITLE
Too much test requests?

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#373]
Before start brute-forcing, I saw that dirsearch will send 2 test requests for each situation, include extensions, `.` and `/`. I'm not gonna explain details about those test requests since you have already known about it:

```python
    def setup(self):
        firstPath = self.preffix + self.testPath + self.suffix
        firstResponse = self.requester.request(firstPath)
        self.invalidStatus = firstResponse.status
        
        secondPath = self.preffix + RandomUtils.randString(omit=self.testPath) + self.suffix
        secondResponse = self.requester.request(secondPath)

        if self.invalidStatus == 404:
            # Using the response status code is enough :-}
            return

        # look for redirects
        elif (
            firstResponse.status in self.redirectStatusCodes
            and firstResponse.redirect
            and secondResponse.redirect
        ):
            self.redirectRegExp = self.generateRedirectRegExp(
                firstResponse.redirect, secondResponse.redirect
            )

        # Analyze response bodies
        self.dynamicParser = DynamicContentParser(
            self.requester, firstPath, firstResponse.body, secondResponse.body
        )
```

In the past, I saw that dirsearch only sent 1 request. Sending 2 requests will cause a problem: a long delay. The delay will be double longer than in the past, and I don't see that sending 2 requests will increase the accuracy. Remember that test requests won't be sent with threads so the delay will be very long, from 3-20 seconds: (`.` + `/` + 5-10 extensions) * 2 = 15-25 requests.

Should we reduce the test request to 1 as in the past? Since I don't see too much difference about the accuracy between the current version (I am using) and the version I used in the past!

**Comment by maurosoria** [comment]
Hello @shelld3v ,

Sorry for being late, I thought I had already answered.

We'll keep this way, because the purpose of the second requests is to look for dynamic content and do some comparisons.

Actually, the code was planned to support N requests, and that might be useful in the future.

Two requests is the necessary to generate the appropriate 2 random strings that are different enough to do the diffing tasks.

**Comment by shelld3v** [comment]
I mean, if `blahblah1.php` returns `404 Not found` and `blahblah2.php` also returns `404 Not found`, then why we should perform the second request? Except if you can do something like this:
- If `blahblah1.php` returns `404 Not found. Error code: joawt849` and `blahblah1.php` returns `404 Not found. Error code: maoid900`, then anything that matches `404 Not found. Error code: ` will be excluded!!!
