### ISSUE TITLE
SyntaxError: non-default argument follows default argument

### ISSUE THREAD

**Issue by vonjk** [maurosoria/dirsearch#400]
![image](https://user-images.githubusercontent.com/30076142/93434953-597c0080-f8fb-11ea-8250-e9b4d6eca696.png)

**Comment by shelld3v** [comment]
Hi, sorry for this, we are fixing it and will comeback soon.

**Comment by vonjk** [comment]
/lib/core/Dictionary.py
    def __init__(self, paths, extensions, excludeExtensions, suffixes=None, prefixes=None, lowercase=False, uppercase=False, forcedExtensions=False, noDotExtensions=False):

**Comment by shelld3v** [comment]
I don't understand what do you mean

**Comment by ndanilo8** [comment]
hey guys I'm having the same problem

**Comment by n04x** [comment]
Any update for this issue? Should we take a previous version while you are working on it?

**Comment by shelld3v** [comment]
No, it may take only a few hours more, since we have found the root cause, but waiting for the author of the project (@maurosoria) to be online and apply the fix

**Comment by shelld3v** [comment]
Can you recheck?

**Comment by elzerver** [comment]
It just needs to rearrange the order of the excludeExtensions parameter following to the extensions parameter as @vonjk says.

**Comment by shelld3v** [comment]
I have fixed everything yesterday, can you recheck?

**Comment by ndanilo8** [comment]
I will check, give me 1 sec

**Comment by shelld3v** [comment]
Ohh, don't redownload it, there is another bug. I have submitted a fix (pull request) but waiting the author to merge it

**Comment by ndanilo8** [comment]
Copy, I will wait

**Comment by maurosoria** [comment]
Merged. Check now

**Comment by shelld3v** [comment]
❤️

**Comment by ndanilo8** [comment]
perfect <3
