### ISSUE TITLE
dirsearch hangs in middle inside Docker container

### ISSUE THREAD

**Issue by 0xdekster** [maurosoria/dirsearch#421]
Hi

I am building a recon tool and using various tools, but dirsearh gets hanged in the middle and doesnt resume at all inside docker container.

The recon script is working inside docker container, i have tried using threads and timeout but it still hangs and doesnt resume inside docker.

Any help is appreciated

**Comment by shelld3v** [comment]
Can you give me more information? I mean, when dirsearch was running for a while, it hanged without any reason or it even didn't start brute-forcing?

**Comment by shelld3v** [comment]
Hi @0xdekster, saw you just released ReconNote, a tool to automate the recon process. It sucks a good tool, with awesome UI, and thank you for adding dirsearch into it 🤩🤩🤩 Have you fixed your problem? If it's yes, then great!!! And I have a suggestion: Can you ask your users (ReconNote users) about feedback, like bugs, features, main workflow updates, ... for dirsearch so we can make this tool better and better?

Thank you! Again, ReconNote is one of the best combination tools I have ever seen. Special, I super impressed with the UI

**Comment by 0xdekster** [comment]
@shelld3v Thanks a lot man , yea dirsearch works great ofcourse man , i will ask for suggestions for sure :)
