### ISSUE TITLE
Is there a option to save the results as such we are seing the output?

### ISSUE THREAD

**Issue by whiteorange007** [maurosoria/dirsearch#441]
output options does not provide option to do this.Taking stdin is not giving pretty results as it show every request done

**Comment by shelld3v** [comment]
I don't really understand this! Do you mean printing the `Last request to: ...` into the file?

**Comment by whiteorange007** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/64798662/94653623-7b24b100-0319-11eb-84dc-083a48dd12fb.png)
I want to get the save the output like this on the screenshot.Any help?

**Comment by shelld3v** [comment]
Dude, you are using dirsearch v0.3.8, please reinstall it now and feel the power

**Comment by shelld3v** [comment]
Done? You can close this!

**Comment by whiteorange007** [comment]
NO, The latest version also do not have option to save the output as the screenshot i have shown.

**Comment by shelld3v** [comment]
```
$ python3 dirsearch.py -E -u example.com

  _|. _ _ _  _  _ _|_     v0.4.0
 (_||| _)(/_(_|| (_| )

Extensions: php, asp, aspx, jsp, jspx, html, htm, js | HTTP method: GET | Threads: 20 | Wordlist size: 10395

Error Log: /tmp/dirsearch/logs/errors-20-10-03_17-17-44.log

Target: example.com

Output File: /tmp/dirsearch/reports/example.com/_20-10-03_17-17-44.txt     <-- Output file

[17:17:44] Starting:
[17:17:55] 403 -  345B  - /.dep.inc
2.56% - Last request to: .dockerignore
```

**Comment by whiteorange007** [comment]
what is this?

**Comment by shelld3v** [comment]
The output will be saved at `[BASEPATH]/dirsearch/reports/[TARGET]/` by default. Of course, you still can change it

**Comment by shelld3v** [comment]
From your screenshot, it will be saved at: `C:\Users\Alpha\Desktop\TOOLS\dirsearch\reports\youtube.com\`

**Comment by shelld3v** [comment]
If you have scanned youtube.com, then your youtube scanned report will be saved at `C:\Users\Alpha\Desktop\TOOLS\dirsearch\reports\youtube.com\`

**Comment by whiteorange007** [comment]
I Will explian my use case.I have a list of urls for directory bruteforcing.I can make a list and give command to scan all the directories and save the output.In output the finest option is the json output but in json output it is inconvenient to see the results.It would be easy to see  each directory found under a host in a list as in screenshot.I hope you understood.

**Comment by shelld3v** [comment]
Yeah, dirsearch support that. If you scan a list of URLs (from a file):

```
https://youtube.com
https://google.com
https://facebook.com
```

Then the reports will be saved at `C:\Users\Alpha\Desktop\TOOLS\dirsearch\reports\BATCH-{YEAR}-{MONTH}-{DATE}_{HOURS}-{MINUTES}-{SECONDS}`. Just open the `C:\Users\Alpha\Desktop\TOOLS\dirsearch\reports\` folder and you will see that! Don't forget to use the `-q` flag :)

**Comment by shelld3v** [comment]
```
  Reports:
    --simple-report=SIMPLEOUTPUTFILE
                        Only found paths
    --plain-text-report=PLAINTEXTOUTPUTFILE
                        Found paths with status codes
    --json-report=JSONOUTPUTFILE
```

**Comment by shelld3v** [comment]
Also, if you have any idea about a dirsearch feature, please don't afraid to talk about it, we will listen and help you. If you are having a suggestion for a dirsearch output format, please tell me, we are thinking about XML and HTML!

**Comment by whiteorange007** [comment]
Thank you very much,Can you tell which line of code should be delated to Disable the "% and last request to"
![Screenshot 10-03-2020 16 02 13](https://user-images.githubusercontent.com/64798662/94989361-d95bc900-0591-11eb-8ae9-3be627a78107.png) line on output,so i can make direct output to a file by | tee output.txt

**Comment by shelld3v** [comment]
The `-q` flag

**Comment by shelld3v** [comment]
Also, are you still having problems with output reports (default reports)?

**Comment by whiteorange007** [comment]
Thanks,this is absolute wonderfull tool,hats off.Sorry if i bothered you i am just starting using linux.

**Comment by shelld3v** [comment]
Don't forget to give us a star :)
