### ISSUE TITLE
Probabilistic dictionary from metrics of old scans

### ISSUE THREAD

**Issue by benoitmaudet** [maurosoria/dirsearch#45]
Hello, 

It would be great to have probabilistic brute-force ! (ex: search for most used directories, then search for most used files in these specifics directories). 

Regards,

**Comment by egilas** [comment]
What would the probabilities be based on? Previous tests executed by the user?

**Comment by amocrenco** [comment]
@egilas what if we test some random websites having this vulnerability? in my country it's legal to do this without malicious intent

**Comment by maurosoria** [comment]
Interested in this feature. Ideas? What would the probabilities be based on?

**Comment by amalmurali47** [comment]
I propose the following approach.

1. Take the word list supplied by the user and store it in a local database - preferably SQLite.
2. When the user runs `dirsearch`, and any of the entries in the word list gives a hit, update the counter for that entry in the database table.
3. At the end of the runs, the most frequently observed hit would have bubbled up to the top.

This way, we can supply bigger word lists, and depending on each user's testing domain and number of runs, their word list would get auto-trained and efficient, not to mention that this would probably speed up the time to get the results too.

**Comment by maurosoria** [comment]
It can be done using the report files. Are you sure sqlite would handle huge wordlists?

**Comment by benoitmaudet** [comment]
Sorry for the delay, using report files could be great 👍. Maybe the easiest way to do it is to create a report parser extracting the n most used directories/files.

**Comment by mzfr** [comment]
@maurosoria this doesn't make sense to me since probability obviously changes with every different website. Also if someone wants to test `most common words` then they can use various existing lists like `common.txt` etc from seclist.

**Comment by shelld3v** [comment]
Agree with @mzfr
