### ISSUE TITLE
Tag for Hacktoberfest

### ISSUE THREAD

**Issue by jsfan** [maurosoria/dirsearch#457]
@maurosoria If you tag the repo "hacktoberfest", you might get contributions in the next few weeks. The rules at Hacktoberfest have changed to make it opt-in, so there is a much better chance to attract people via the tag this year than there would have been in past years.

**Comment by shelld3v** [comment]
What is Hacktoberfest?

**Comment by l9sk** [comment]
@shelld3v
https://github.com/digitalocean/hacktoberfest/pull/596
https://blog.domenic.me/hacktoberfest/

**Comment by shelld3v** [comment]
@jsfan https://blog.domenic.me/hacktoberfest/ 👍

**Comment by jsfan** [comment]
@shelld3v Yes, there is a risk of spam. However, the blog post is outdated. The rules were changed for exactly that reason. I have a repo open for Hacktoberfest and I've only got one PR so far and it was high quality.

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by shelld3v** [comment]
Hey @jsfan, added that tag, can we close this?

**Comment by jsfan** [comment]
:+1:
