### ISSUE TITLE
Update thirdparty modules?

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#467]
It has been 6 years and those modules have probably been updated a lot, with better performance, ... Should we update them?

**Comment by maurosoria** [comment]
Yes, for sure!

**Comment by christianl-das** [comment]
Is there a reason why they are bundled rather than just be dependencies?

**Comment by shelld3v** [comment]
@christianl-das (@jsfan:) Because to install pip (python) on Windows it's really hard + complex, many people (a lot) even don't know how to do it. So why we don't just create an app that just needs to install and run!

**Comment by jsfan** [comment]
Sorry, I have too many Github accounts... ;)

That makes sense. I am not a Windows guy, so didn't think of that.

**Comment by shelld3v** [comment]
L O L Can you tell me how many total accounts do you have? 🤣🤣🤣 And what do they used for?

**Comment by jsfan** [comment]
That's it now. They have access to different private repositories owned by different organisations.

**Comment by qumusabel** [comment]
> Because to install pip (python) on Windows it's really hard + complex

Isn't it a matter of enabling a checkbox in python installer?
![image](https://user-images.githubusercontent.com/18624304/118158159-da60ad00-b434-11eb-976f-2249f29dc4de.png)
(actually installed by default).
`/thirdparty` also mentioned in #736

**Comment by shelld3v** [comment]
> > Because to install pip (python) on Windows it's really hard + complex
> 
> Isn't it a matter of enabling a checkbox in python installer?
> ![image](https://user-images.githubusercontent.com/18624304/118158159-da60ad00-b434-11eb-976f-2249f29dc4de.png)
> (actually installed by default).
> `/thirdparty` also mentioned in #736

The reason why I said it was complex is that people have to run cmd in the correct folder (the one contains pip.exe)

**Comment by qumusabel** [comment]
> run cmd in the correct folder

never had to do that, also you can add python & all the other stuff to PATH. I don't think you should bother shipping thirdparty modules just because someone can't click a checkbox.

**Comment by shelld3v** [comment]
>never had to do that

In Windows, yes. I know it's not a too hard thing to do, but want to make the installation easier for all users, including non-tech people
