### ISSUE TITLE
can't search website with non-standard port

### ISSUE THREAD

**Issue by bupsdx** [maurosoria/dirsearch#469]
Hello,I use the latest version  to search a website with non-standard port, like http://123.206.87.240:8002
in Windows,i used command like:  `python dirsearch.py -u "http://123.206.87.240:8002" -e *`
but  an error appeard:
`Traceback (most recent call last):
  File "dirsearch.py", line 46, in <module>
    main = Program()
  File "dirsearch.py", line 42, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "C:\Users\xxxx\Desktop\dirsearch-master\lib\controller\Controller.py", line 154, in __init__
    self.requester = Requester(
  File "C:\Users\xxxx\Desktop\dirsearch-master\lib\connection\Requester.py", line 102, in __init__
    headers["Host"] += ":{0}".format(self.port)
NameError: name 'headers' is not defined`

i also use `python dirsearch.py -u http://123.206.87.240:8002 -e *`       
it's the same error

i tried in linux, but it's same too. So i don't know what is wrong.

**Comment by bupsdx** [comment]
thanks。 Bug fix #470  slove the problem

**Comment by shelld3v** [comment]
LOL @maurosoria hasn't merged it yet

**Comment by bupsdx** [comment]
I change the code myself, it's OK now

**Comment by shelld3v** [comment]
You still shouldn't close this!

**Comment by bupsdx** [comment]
OK,now it's reopen
