### ISSUE TITLE
Couldn't resolve DNS (Linux)

### ISSUE THREAD

**Issue by Be1nna** [maurosoria/dirsearch#476]
Error Log: /root/dirsearch/logs/errors-20-10-10_00-28-41.log

**Comment by DustinTheGreat** [comment]
Whats the url your using?

**Comment by shelld3v** [comment]
@Be1nna Can you give us any information about the bug?

**Comment by Be1nna** [comment]
python3 dirsearch.py -b  -u “subdomain.subdomain.example.com” -e html,json
I get this error when I want to run it with this command.

**Comment by shelld3v** [comment]
Do you able to hit "http://subdomain.subdomain.example.com" from your browser?

**Comment by DustinTheGreat** [comment]
Yeah try what @shelld3v or also try adding the https:// 
I hit a similar problem last week. also you aren't using the quotes right lol?

**Comment by Be1nna** [comment]
Thank you very much!
