### ISSUE TITLE
Problems with Keep-alive connection

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#485]
Hi 🖐️ 

Recently, I had a problem with dirsearch. I found a subdomain and tried to brute-force it with dirsearch. After around 3 seconds, the server returned 429 too many requests. I have a lot of experience with this so I waited a couple of minutes then brute-forced again with fewer threads. It surprised me that I still can access the subdomain (without blocked) from my browser, but whenever dirsearch sent 12 requests, the next requests will return 429. I also tested with FFUF and nothing happened. And after dug a little bit, I believe that the problem came from the keep-alive connection.

From my investigation, I found several problems with keep-alive: not all the servers support keep-alive connection, some servers will have problems with keep-alive connection (block when received too many requests for example, like my situation), ...

So I highly advise you to remove keep-alive connection, although maybe not now, to can keep the speed of dirsearch, but in the future

**Comment by maurosoria** [comment]
Hello @shelld3v,

Try to run dirsearch again, but proxying through burp. Then tell me the results.

Thanks for everything

**Comment by shelld3v** [comment]
Thanks, but please merge my PRs first, special is #479 :)

**Comment by shelld3v** [comment]
Also, congrats for 4.6k stars
