### ISSUE TITLE
Error when running dirsearch

### ISSUE THREAD

**Issue by momocr7** [maurosoria/dirsearch#486]
when I run dirsearch, this error appears!

`` 
File "/home/momo/dirsearch/lib/controller/Controller.py", line 172, in __init__
    self.requester.request("")
  File "/home/momo/dirsearch/lib/connection/Requester.py", line 180, in request
    del headers
``
![rr](https://user-images.githubusercontent.com/40707762/95951683-28f28e00-0df7-11eb-86e4-a65fa3a08240.png)

what is the problem here?

**Comment by shelld3v** [comment]
Hi, sorry for that, it is a bug and will be fixed soon! Also, you are using dirsearch the wrong way, dirsearch doesn't replace `*` with all extensions (a wrong think of many dirsearch users)
