### ISSUE TITLE
Warning when target use a self-signed certificate

### ISSUE THREAD

**Issue by psyray** [maurosoria/dirsearch#512]
Hi,

I've update from 0.3.9 to 0.4.0 and now I have this message displaying during a scan
```
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.129.23.235'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```
This make the output unreadable.
I don't see any parameter to disable certificate check in dirsearch.

According [to this doc](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings) I've added the `urllib3.disable_warnings()` juste after the `import urllib3` in the `thirdparty/requests/__init__.py` file
Warnings gone 

Could you add a parameter to disable certification check ?

**Comment by shelld3v** [comment]
Hi, sorry about that. I have submitted a fix and waiting for @maurosoria to merge this PR

**Comment by shelld3v** [comment]
Hi, fixed! You can close this now!

**Comment by shelld3v** [comment]
This has been fixed, please close the issue
