### ISSUE TITLE
Getting error when dirsearch runs 

### ISSUE THREAD

**Issue by 0xdekster** [maurosoria/dirsearch#528]
Hi @shelld3v  

I am getting this error in my reconnote tool as well as running it isolated -

   from lib.connection.request_exception import RequestException
  File "/deksterecon/dirsearch/lib/connection/__init__.py", line 2, in <module>
    from .requester import *  # noqa: F401
  File "/deksterecon/dirsearch/lib/connection/requester.py", line 25, in <module>
    import thirdparty.requests as requests
  File "/deksterecon/dirsearch/thirdparty/requests/__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'

Can you please see this ?

**Comment by shelld3v** [comment]
Are you running with python3?

**Comment by 0xdekster** [comment]
Yes with python3 @shelld3v

**Comment by shelld3v** [comment]
Hi, can you install urllib3 with pip? I mean, `pip3 install urllib3`

**Comment by shelld3v** [comment]
Or `pip install urllib3`, I don't know

**Comment by 0xdekster** [comment]
@shelld3v Fixed by using --url-list , giving error with -l
