### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mhmh55516** [maurosoria/dirsearch#548]
When i start dirsearch with proxies after while i got ip banned in response , dirsearch think is a valid page as status code 200 but it actually 404 (Not found) and the page going to results.

What i need is make options that when porxy ban use other proxy in list and without contintun for next word or not the add the page in results .

**Comment by shelld3v** [comment]
Try `--proxy-list`!

**Comment by mhmh55516** [comment]
You don't understand me !!
i have waf block my ip after 200 requests and show page with (200 ok) and in response "ip blocked" and while i use dirsearch to brute force get me back (200 ok) beacuse my ip is blocked as mention before but in real with other ip the page is not found (404) .

**Comment by shelld3v** [comment]
Hey, there is no way for us to can know has the server blocked you or not! Any detector in this situation can cause false negatives, and I think the best solution for you now is to reduce the threads, or create a delay (that can limit the requests/sec), or add more proxy hosts into your list of proxies so each host will send fewer requests!

**Comment by mhmh55516** [comment]
You can add option like this "--exclude-texts=EXCLUDETEXTS" for ip ban if they match try word with another proxy .

**Comment by shelld3v** [comment]
That is a good solution. And you need to add it by yourself since there is no way for us to know what is the exclude text for IP banned responses

**Comment by mhmh55516** [comment]
that looks good.
