### ISSUE TITLE
get_terminal_size() under FreeBSD

### ISSUE THREAD

**Issue by pbdname** [maurosoria/dirsearch#56]
First, thank you for your work.

Please add FreeBSD to the list of operating systems under which to use _get_terminal_size_linux() function:

```
diff lib/utils/TerminalSize.py ~/dirsearch.git/trunk/lib/utils/TerminalSize.py
40c40
<     if current_os in ['Linux', 'Darwin', 'FreeBSD'] or current_os.startswith('CYGWIN'):
---
>     if current_os in ['Linux', 'Darwin'] or current_os.startswith('CYGWIN'):
42a43
>         print("default")
```

Also _print("default")_ on line 43 seems to be a forgotten debug message.

**Comment by maurosoria** [comment]
Thanks for the report. I've just submitted the fix.
