### ISSUE TITLE
Don't works, help please

### ISSUE THREAD

**Issue by Shuhard253** [maurosoria/dirsearch#563]
python3 dirsearch.py -e php,html,js -u https://target

Traceback (most recent call last):
  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 36, in __init__
    self.arguments = ArgumentParser(self.script_path)
  File "/home/dom/dirsearch/lib/core/argument_parser.py", line 337, in __init__
    self.exit_on_error = options.exit_on_error
AttributeError: 'Values' object has no attribute 'exit_on_error'

python 3.8.4
OS - KaliLinux

what i do wrong?

**Comment by Zedzor** [comment]
Try downloading again, i think they fixed it!

**Comment by Shuhard253** [comment]
I do git clone  hour ago today, may be something else?

**Comment by Zedzor** [comment]
they fixed it 16 minutes ago on their last commit

**Comment by appstr** [comment]
> Try downloading again, i think they fixed it!

This fixed the issue for me.

I deleted the old repository and re-ran `git clone https://github.com/maurosoria/dirsearch.git`

Everything works fine now.

**Comment by Shuhard253** [comment]
Yep, it's work fine now! thnx for help :)

**Comment by Shuhard253** [comment]
Close
