### ISSUE TITLE
Give me Error on Ubuntu

### ISSUE THREAD

**Issue by Sajjadkhan12** [maurosoria/dirsearch#593]
`**  File "dirsearch.py", line 47, in <module>
    main = Program()
  File "dirsearch.py", line 36, in __init__
    self.arguments = ArgumentParser(self.script_path)
  File "/home/sajjad/tools/dirsearch/lib/core/argument_parser.py", line 337, in __init__
    self.exit_on_error = options.exit_on_error
AttributeError: 'Values' object has no attribute 'exit_on_error'
**`
I get the following error while running on ubuntu can you please help

**Comment by shelld3v** [comment]
Hi, please update to the latest version (re-download it)
