### ISSUE TITLE
Error running dirsearch

### ISSUE THREAD

**Issue by bulldog888** [maurosoria/dirsearch#625]
root@kali:/opt/dirsearch# python3 dirsearch.py -u http://10.10.10.28 -e php
Traceback (most recent call last):
  File "dirsearch.py", line 28, in <module>
    from lib.controller import Controller
  File "/opt/dirsearch/lib/controller/__init__.py", line 1, in <module>
    from .controller import *  # noqa: F401
  File "/opt/dirsearch/lib/controller/controller.py", line 532
    elif path.response.redirect:
    ^
SyntaxError: invalid syntax

Help please.

**Comment by shelld3v** [comment]
Hi, you can temporarily try this: `git clone https://github.com/TheBinitGhimire/dirsearch.git`, since the project owner hasn't merged the fix yet!

**Comment by bulldog888** [comment]
> Hi, you can temporarily try this: `git clone https://github.com/TheBinitGhimire/dirsearch.git`, since the project owner hasn't merged the fix yet!

Thanks!! it worked

**Comment by shelld3v** [comment]
You can close this now!
