### ISSUE TITLE
Error Running dirsearch 

### ISSUE THREAD

**Issue by luapy** [maurosoria/dirsearch#627]
Running dirsearch has SyntaxError with python 3.8.1(win10)

Some error picture
![111](https://user-images.githubusercontent.com/24366795/99937114-da45f580-2d9f-11eb-9c37-a102a1cb296c.png)
![2222](https://user-images.githubusercontent.com/24366795/99937117-dc0fb900-2d9f-11eb-8462-e7e8302ec8a3.png)
![334](https://user-images.githubusercontent.com/24366795/99937165-f5b10080-2d9f-11eb-94e3-5377d0d13686.png)

**Comment by shelld3v** [comment]
>Hi, you can temporarily try this: git clone https://github.com/TheBinitGhimire/dirsearch.git, since the project owner hasn't merged the fix yet!

**Comment by shelld3v** [comment]
`git clone https://github.com/TheBinitGhimire/dirsearch.git`

**Comment by shelld3v** [comment]
Sorry for this inconvenience!

**Comment by luapy** [comment]
> Sorry for this inconvenience!



> > Hi, you can temporarily try this: git clone https://github.com/TheBinitGhimire/dirsearch.git, since the project owner hasn't merged the fix yet!

Ok,Thanks for your reply,it is useful
