### ISSUE TITLE
Error: from lib.controller import Controller

### ISSUE THREAD

**Issue by niravsikotaria** [maurosoria/dirsearch#630]
OS = Kali Linux 2020.1

Python version = Python 3.7.6  

screenshots:
![Screenshot (1)](https://user-images.githubusercontent.com/5881266/100045887-1b88e480-2e36-11eb-9ba4-fab1d7864fbc.png)

dirsearch command: python3 dirsearch.py -e php,html,js -u https://target

console output:
Traceback (most recent call last):
  File "dirsearch.py", line 28, in <module>
    from lib.controller import Controller
  File "/home/kali/dirsearch/lib/controller/__init__.py", line 1, in <module>
    from .controller import *  # noqa: F401
  File "/home/kali/dirsearch/lib/controller/controller.py", line 532
    elif path.response.redirect:
    ^
SyntaxError: invalid syntax

**Comment by shelld3v** [comment]
Fixed now!

**Comment by shelld3v** [comment]
Can you please re-install dirsearch?

**Comment by niravsikotaria** [comment]
> Can you please re-install dirsearch?
after re-install dirsearch getting this error
![Screenshot (3)](https://user-images.githubusercontent.com/5881266/100111914-a7c9f480-2e94-11eb-8032-bf7d81092667.png)

**Comment by shelld3v** [comment]
Wow wow, this is an edge case. Probably it comes from your python version or something. I believe you can resolve this by `pip3 install -r requirements.txt`

**Comment by niravsikotaria** [comment]
> Wow wow, this is an edge case. Probably it comes from your python version or something. I believe you can resolve this by `pip3 install -r requirements.txt`

![Uploading Screenshot (4).png…]()

**Comment by shelld3v** [comment]
Hi, I can't reproduce your problem as well as identify the root cause. Can you try this: `pip3 install chardet`

**Comment by shelld3v** [comment]
This will require an investigation

**Comment by niravsikotaria** [comment]
ya sure I will try thanks for the support dear, I think there is a path mistake

**Comment by niravsikotaria** [comment]
Finally its Works Dear, Just I change: python3 to python

Ex:
python3 dirsearch.py -e php,html,js -u https://target.com  **Getting Error**
python dirsearch.py -e php,html,js -u https://target.com **Working Like Rocket**

**To all user you get any error please change this, it will work**

**Comment by shelld3v** [comment]
WOW!!! You can close this now

**Comment by niravsikotaria** [comment]
Ya sure.
