### ISSUE TITLE
UnboundLocalError: local variable 'url' referenced before assignment

### ISSUE THREAD

**Issue by wey123** [maurosoria/dirsearch#634]
OS: Windows 10

![image](https://user-images.githubusercontent.com/11818537/100146691-0f724680-2e79-11eb-94d6-f05f3b563322.png)

Output:
docker run -it --rm "dirsearch:v0.4.0" -u www.google.com.br -e php,html,js,zip                                                                                     /root/dirsearch/thirdparty/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

  _|. _ _  _  _  _ _|_    v0.4.0
 (_||| _) (/_(_|| (_| )

Extensions: php, html, js, zip | HTTP method: GET | Threads: 20 | Wordlist size: 10303

Error Log: /root/dirsearch/logs/errors-20-11-24_20-07-41.log

Target: http://www.google.com.br/

Traceback (most recent call last):
  File "/root/dirsearch/./dirsearch.py", line 47, in <module>
    main = Program()
  File "/root/dirsearch/./dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/root/dirsearch/lib/controller/controller.py", line 184, in __init__
    self.requester.request("")
  File "/root/dirsearch/lib/connection/requester.py", line 160, in request
    url += path
UnboundLocalError: local variable 'url' referenced before assignment

**Comment by rjbathgate** [comment]
See my comment https://github.com/maurosoria/dirsearch/issues/636

**Comment by shelld3v** [comment]
Fixed

**Comment by wey123** [comment]
solved
