### ISSUE TITLE
UnboundLocalError: local variable 'url' referenced before assignment

### ISSUE THREAD

**Issue by Pen4Test2Hacker0** [maurosoria/dirsearch#636]
### What is the current behavior?

when given the command to scan url, it won't do the scan and gives out an UnboundLocalError: local variable 'url' referenced before assignment at the end.

### What is the expected behavior?

should enumerate the web server for common directories

### Any additional information?

the OS is debian 5.9.6-1kali linux (2020-11-11) 

#### Checker:
 - [ Y ] I have read the documentation (README)
![dirsearchErr](https://user-images.githubusercontent.com/74991921/100156975-75f26700-2e6f-11eb-84f4-a896d6b57fd1.png)

**Comment by rjbathgate** [comment]
I receive exactly the same error.

Looking through recent commits, there have been some amends to the 'url' recently, so I took a gamble and checked out to a commit before these were merged (`git checkout b642d2d0bb260454e243f2d49c079dd9b6c8d32c`) and now everything seems to be working fine.

So a bug must have been introduced between b642d2d0bb260454e243f2d49c079dd9b6c8d32c and latest.

**Comment by shelld3v** [comment]
Fixed!

**Comment by shelld3v** [comment]
Can you close this?

**Comment by shelld3v** [comment]
Hi, please close this!
