### ISSUE TITLE
Moving from threads to asyncio

### ISSUE THREAD

**Issue by maurosoria** [maurosoria/dirsearch#643]
Hello folks,

I am opening this issue because I do not have the time to do it myself, but I really think that now is the momentot move from threads to an asyncio based application (at least for requests and some callbacks).

I planned from the beginning to do this, but back then asyncio wasn't widely supported by most of linux distros and wasn't as mature like it is today. 

This is a very important step, because it would open the door to add extra scanning capabilities to dirsearch, that now seems very difficult with a normal thread scheme.

### What is the feature?

Moving from a regular thread-based system to an asynchronous based requests system would improve the performance.

### Take into consideration
* The idea is using an asyncio executor for processing Jobs.
* It is important to follow pep8 guidelines and validate the code.
* It might be a good idea considering a model who may, in the future, support scanning multiple hosts at the same time (like [meg](https://github.com/tomnomnom/meg))
* I guess the proper library for doing this may be [aiohttp](https://docs.aiohttp.org/en/stable/), but I guess for now it is important to stop using threads and keep using [requests](https://requests.readthedocs.io/en/master/).
* It can be very time consuming to code, but maybe using CPU bound executor for certain tasks could make a difference (maybe not).

Obviously, I will assist you if you want to cooperate in all I can, and I will review the code myself.

Thanks for cooperating, and spread the voice!

Regards, 
Mauro

**Comment by shelld3v** [comment]
Should we fully stop using threads and turn into async, or support both?

**Comment by shelld3v** [comment]
And the fact that it will be really hard to can control the speed if we use asyncio

**Comment by maurosoria** [comment]
it is possible to mix asyncio with threads, using the proper asyncio executor:
[](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor)

**Comment by shelld3v** [comment]
What if I want to brute-force with just 2 requests per second? Of course, we can set the requests max-rate in aiohttp, but it will send 2 requests in 1/100 second, then wait after 99/100 second to do it again, something that will be really weird with me

**Comment by dbfreem** [comment]
@maurosoria I actually have a lot of experience moving code over to asyncio. One thing to keep in mind is it can grow legs really quickly and get complex. Do you have a suggestion on where would be a good section to pull off and move over to asyncio. I would expect to use aiohttp instead of request though, so you get the true benefit of asyncio.

Anyways, thought I would reach out and see if you wall were still moving forward with this, if so if you needed some help.

**Comment by maurosoria** [comment]
Hello @dbfreem ! I am very grateful for your interest !

IMO Fuzzer class is the best candidate for starting to move code. You can rewrite that class, create a super class BaseFuzzer, and just move the old class to a subclass (e.g. TheadingFuzzer) and you can write another (eg. AsyncioFuzzer). 

In that way we can write universal unit tests for both fuzzers (and make other ones in the future!).

the other candidate (which I'm also looking forward to doing that) is the Controller class. But, in that case, is much more complex because you need to completely rewrite everything (report writing, user input, etc).


If you are really into this please do not hesitate in use this or another communication method you prefer (like twitter!)

**Comment by dbfreem** [comment]
Hey @maurosoria that sounds like a great plan. I plan on working on this over the holidays, so I will keep you up to date on the progress.

**Comment by willjprice** [comment]
Following

**Comment by maurosoria** [comment]
Hello! Any noticie about this ?

**Comment by Prady18** [comment]
No

**Comment by DylanTiger** [comment]
Hey what are you going to use asyncio and aiohttp or asyncio and httpx? or something else that i ignore? I think that with chatgpt help it won't need much to accomplish it :D

**Comment by Prady18** [comment]
Good question! ⁉️

**Comment by asadmins** [comment]
Is there any progress on this project?

**Comment by shelld3v** [comment]
> Is there any progress on this project?

Not yet

**Comment by zrquan** [comment]
Hey guys, I've submitted a draft PR to support asynchronous mode, testing and reviews are welcome. The speedup from using coroutines is significant, hopefully it can be merged into the master branch soon 😄
