### ISSUE TITLE
While running dirsearch I'm getting these errors

### ISSUE THREAD

**Issue by de-adshot** [maurosoria/dirsearch#647]
![image](https://user-images.githubusercontent.com/11958190/101131735-ce71f300-362b-11eb-8a3b-72b0cd312557.png)

**Comment by shelld3v** [comment]
This is the temporary solution: `git clone https://github.com/shelld3v/dirsearch.git -b patch-6`

**Comment by shelld3v** [comment]
Hi, this has officially been fixed! You can close this now.
