### ISSUE TITLE
[e]xit / [c]ontinue / [i]gnore / [s]kip target:

### ISSUE THREAD

**Issue by alfonsocaponi** [maurosoria/dirsearch#663]
:( :( :(

How avoid this ?!

**Comment by shelld3v** [comment]
It looks like you just hit 429 response status code (the signal shows that your requests have been blocked by the server). You should wait a little bit until the server unblocks you, then use `c`. If you still want to brute-force without caring about it, try `i`. But, there is a bug in this feature, and I have submitted PR to fix this, but haven't been merged by @maurosoria yet. So if you want to use the fix: `git clone https://github.com/shelld3v/dirsearch.git -b patch-18`. Even what, I advise you not to ignore this thing, if you don't know what 429 HTTP code is, check out it on Google,

**Comment by alfonsocaponi** [comment]
Thank you very much for your support. I don't think so. I excluded 429 ret code with "-x" options. I've only 403s, intentionally.
I like use dirsearch inside a script... and this interaction is a problem. I would not want to use "expect" or other :(

**Comment by shelld3v** [comment]
You intentionally ignore 429? Wow, it's OK if you want! You can enter `i` to stop receiving 429 warnings!

**Comment by alfonsocaponi** [comment]
Yes, it's ok in my case. I would like to suggest an options like "--assume-continue" and/or "--assume-ignore" to avoid user interaction :)

**Comment by shelld3v** [comment]
Yeah!! Thanks for that

**Comment by shelld3v** [comment]
Can you close this?

**Comment by chvancooten** [comment]
+1 on this issue. The lack of a `--batch` mode makes it impossible to use Dirsearch in headless scripts (which is also what I'm looking for). In my case, I would like to skip the target domain whenever a HTTP 429 is hit. This doesn't seem possible currently, so I don't see why this issue should be closed :)

**Comment by shelld3v** [comment]
Hi, good news: this has been addressed and will be fixed in the next release. Thanks for your request 🎉

**Comment by bootyhunt3r** [comment]
Any idea when will the update be released ?

**Comment by shelld3v** [comment]
A few days more
