### ISSUE TITLE
Recursive switch doesn't seem to work

### ISSUE THREAD

**Issue by felpsbr977** [maurosoria/dirsearch#664]
recursive mode is not working for me

**Comment by shelld3v** [comment]
Can you give more information?

**Comment by felpsbr977** [comment]
when I put the command -r it doesn't work nothing happens, "python3 dirsearch.py -e php,js -u https://*******.***.*****.***/ -r  "

**Comment by shelld3v** [comment]
Hi, this is a bug and will be fixed soon!

**Comment by saadsaqi** [comment]
Yar kn ho tum or kiya kerna chaty ho

**Comment by harsh095** [comment]
No

**Comment by harsh095** [comment]
Soory

**Comment by harsh095** [comment]
Hello
I am bsc students from Gujarat.
Me haking sikhana chahata hu .
Please help me..

**Comment by shelld3v** [comment]
Hi, I can't understand what you are talking about!

**Comment by Phoenix1112** [comment]
@shelld3v recursive not working.. Even if the recursive mode is enabled, the program terminates without rescanning the found directories.

example path found with dirsearch

/path/

but /path /* doesn't rescan.

**Comment by shelld3v** [comment]
Hi, I confirmed this is a bug, and the fix will be merged soon. Now, to scan recursively, you just need to not add the `-r` flag

**Comment by Phoenix1112** [comment]
@shelld3v thanks... <3
