### ISSUE TITLE
Double slash in output

### ISSUE THREAD

**Issue by huyndnse63331** [maurosoria/dirsearch#687]
### What is the current behavior?
Why i keep getting double slash on every dirsearch outputs on recent updates.

### Any additional information?
![image](https://user-images.githubusercontent.com/25204246/102960794-4d649800-4515-11eb-8bae-55163196581c.png)

Distro: macOS Catalina

OS, python version, screenshots, dirsearch command, console output, ...?

#### Checker:
 - [x] I have read the documentation (README)

**Comment by shelld3v** [comment]
Hi, I think this is an old bug, and has been fixed in the latest version! Try to redownload again: `git clone https://github.com/maurosoria/dirsearch.git`

**Comment by huyndnse63331** [comment]
Hi again, i forgot to mention that i forgot to attach an image about cloing the repo just a few minutes ago before this issue was opened.

![image](https://user-images.githubusercontent.com/25204246/102961242-63268d00-4516-11eb-9b9a-51d67e47dc2e.png)

**Comment by huyndnse63331** [comment]
I'm uisng Python 3.9.1 btw.

**Comment by shelld3v** [comment]
Can you give me the command that you are using?

**Comment by huyndnse63331** [comment]
Sure thing.

`
dirsearch -e php,html -r -R 3 --random-agent -b -w ~/wordlist/dicc.txt -t 200 -u 'https://example.com/'`

**Comment by shelld3v** [comment]
You are probably using the old version for sure! Because in the latest update, the `--random-agent` flag has become `--random-user-agent`

**Comment by huyndnse63331** [comment]
Yeah thanks for mentioning that option, i checked again and i didn't call dirsearch in the correct directory, my mistake, thank you.
