### ISSUE TITLE
URL list file not work file 

### ISSUE THREAD

**Issue by zenner3000** [maurosoria/dirsearch#688]
**Windows 2012  + python 3.8.3  + the latest dirsearch**
I want to scan an url list , when I execute the command like this:
**python3 dirsearch.py -e php -l urllist.txt --plain-text-report report.txt**

it shows 
URL target is missing, try using -u <url>

README say use like this:
**python3 dirsearch.py -e php -l URLs.txt --plain-text-report report.txt**
but not works

but after testing on kali 2020 , it works !

**Comment by shelld3v** [comment]
So, has it worked yet? If yes, you can close this!

**Comment by shelld3v** [comment]
Please close this if you fixed it!
