### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by just805** [maurosoria/dirsearch#689]
环境：
kali 2020.4
python3

![fy1](https://user-images.githubusercontent.com/18697510/103058375-f1fddd00-45dc-11eb-8acb-8ef75e4d2b78.png)
![fy2](https://user-images.githubusercontent.com/18697510/103058381-f3c7a080-45dc-11eb-9fdb-a9da91cb7451.png)

调用kali 自带字典大约133.4Mib，出现程序报错。 
默认dirsearch 字典也出现python报错。详细截图如下：
![fy3](https://user-images.githubusercontent.com/18697510/103058387-f75b2780-45dc-11eb-98fb-2181823f457b.png)

**Comment by shelld3v** [comment]
嗨，我相信这个问题是Web服务器问题，而不是dirsearch。我希望您能给我FULL错误回溯。我只能从您的屏幕截图中提取一半

**Comment by just805** [comment]
感谢作者，确实是服务器问题。我测试google 没有报错。

**Comment by shelld3v** [comment]
您可以立即关闭它! :heart:
