### ISSUE TITLE
Release v0.4.2

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#697]
Waiting for this!

**Comment by maurosoria** [comment]
What do you prefer, last year or new year relase?

**Comment by shelld3v** [comment]
Well, new year 🎉

**Comment by maurosoria** [comment]
Let's wait a couple of days with these new PRs until we are sure everything is alright.

**Comment by shelld3v** [comment]
🙏

**Comment by shelld3v** [comment]
Requirements:
- [ ] Update README
- [ ] Update CHANGELOG.md
- [ ] Update controller.py
- [ ] Update argument_parser.py
- [ ] Tweet!

**Comment by maurosoria** [comment]
Check the branch refactor, I didn't test it yet (the fix for the urllib3 dependency)

**Comment by shelld3v** [comment]
Hey, it seems okay. But when I hit `CTRL+C`, it takes really long to pause the process!!

I think we need to test more before merging that branch, and we can release the new version now ;)
