### ISSUE TITLE
Remove DOT when no-extension

### ISSUE THREAD

**Issue by adon90** [maurosoria/dirsearch#70]
Let's say you want to try aspx,asp and no extension.
When you try this:  `-e asp,aspx,,` it tries, -let's say the current word is service-:
```
service.asp
service.aspx
service.
service/
```

You want to look for:

```
service.asp
service.aspx
service
service/
```
So these two lines do the trick:
 `dirsearch/lib/connection/Requester.py` file:

```
if url.endswith('.'):
    url = url[:-1]
```

I added it before the request:  lines 130-131

![dirsearch](https://user-images.githubusercontent.com/7115563/31881011-7c860010-b7e2-11e7-8ce4-a211580447a9.png)

;)

**Comment by Rockajansky** [comment]
¯\_(ツ)_/¯

**Comment by maurosoria** [comment]
Thanks adon90,

I pushed a fix for this issue. It's not the one you provided because I thought the Requester class is not the responsable of managing this situation.

**Comment by adon90** [comment]
Hey! No problem ;) I just saw your commit. Yeah The Requested class is not
the responsable, I think you received my pull request becase in there I did
almost the same change you did
I would like you to see it, because I also added a --filter-size option:
https://github.com/adon90/dirsearch
Regards!

2017-11-15 0:54 GMT+01:00 Mauro Soria <notifications@github.com>:
