### ISSUE TITLE
How to set delay time?

### ISSUE THREAD

**Issue by ycjcl868** [maurosoria/dirsearch#72]
if not set delay time , the waf would ban it!

**Comment by fuuddanni** [comment]
It´s option -t Timeout or thread: Connection Settings:
    --timeout=TIMEOUT, --timeout=TIMEOUT
                        Connection timeout

**Comment by ycjcl868** [comment]
`-t`  is threadcount 
![image](https://user-images.githubusercontent.com/13595509/32413147-39035126-c246-11e7-82ba-c76044e2bbba.png)

**Comment by drego85** [comment]
Use “-s”

**Comment by ycjcl868** [comment]
Thanks @drego85 , It works!
