### ISSUE TITLE
Brute force stucked

### ISSUE THREAD

**Issue by code401-id** [maurosoria/dirsearch#727]
before the update I have used this tool and I really like it, but after I updated I got a lot of errors when starting the brute force, I used the latest version on Android via the Termux application, does termux support python3?

**Comment by shelld3v** [comment]
Can you give me the error message (traceback)?

**Comment by code401-id** [comment]
Wait i take a screnshoot

**Comment by code401-id** [comment]
@shelld3v 
> Can you give me the error message (traceback)?

![Screenshot_2021-01-16-23-23-01-934_com termux](https://user-images.githubusercontent.com/77542114/104817152-03d84600-5852-11eb-9c80-774ff2ba8122.png)

**Comment by shelld3v** [comment]
Hi, this is an Android problem, and there isn't any solution for this yet!

From what I found:

>Solution to above problem. Use proot distros in termux. Android support semaphores but the termux being based on aarch64 thats new architecture thee are restrictions. But not on proot based distros as they use arm64 repos l. So install arch or ubuntu on termux

**Comment by code401-id** [comment]
very helpful and made me understand the explanation of the problem I was experiencing, thank you have a nice day

**Comment by shelld3v** [comment]
Have a nice day and a nice year too! Don't forget to close this issue if it has been solved ;)
