### ISSUE TITLE
TypeError: separation() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by tomasz-kusy** [maurosoria/dirsearch#729]
Hi,
I made git pull (to current commit 9b4bb83b254a9d04854e7ffff89b9052507fd1a6). 
Unfortunately I have error:
`
Traceback (most recent call last):
  File "./dirsearch.py", line 47, in <module>
    main = Program()
  File "./dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/root/dirsearch/lib/controller/controller.py", line 169, in __init__
    self.printConfig()
  File "/root/dirsearch/lib/controller/controller.py", line 278, in printConfig
    str(self.httpmethod),
  File "/root/dirsearch/lib/output/cli_output.py", line 217, in config
    config += self.separation(config, particle) + particle
TypeError: separation() takes 2 positional arguments but 3 were given
`
After rollback last commit (git reset --hard 18d47e217b153d4e6ed543a7267311e31fe0f454) everything works ok.

**Comment by shelld3v** [comment]
Hey, it will be fixed after this PR get merged: #728

**Comment by Facucuervo87** [comment]
same error solved with git reset --hard 18d47e2

**Comment by gshacklebolt** [comment]
> same error solved with git reset --hard [18d47e2](https://github.com/maurosoria/dirsearch/commit/18d47e217b153d4e6ed543a7267311e31fe0f454)

Thanks brother. This seems to fix the issue for now.

**Comment by ftk-sostupid** [comment]
That's an error because of: lib/output/cli_output.py, line 182

`def separation(self, config, x):`

Lack of a "self".

**Comment by Yashwanthd1998** [comment]
still same issue

**Comment by shelld3v** [comment]
Hi @Yashwanthd1998, this is a sooo old issue that has already been fixed in the latest version. Please re-install dirsearch
