### ISSUE TITLE
Is it possible to exit the dirsearch on 429 response code automatically

### ISSUE THREAD

**Issue by kotireddyaluri** [maurosoria/dirsearch#739]
Hi Guys,
Is it possible to exit the dirsearch automatically when it encounter 429 response code. for example like `exit-on-429 ` option
```
[00:20:30] Starting: 
[00:21:32] 403 -   21B  - /%0a%0a<script>alert(\"Vulnerable\")</script>.jsp
429 status code detected: Pausing threads, please wait...
[e]xit / [c]ontinue / [i]gnore: e

Canceled by the user
```

Thank you.

**Comment by bootyhunt3r** [comment]
I want it to skip the target when 429 code is achieved , it would be really helpful because yesterday I ran the script thinking it would be completed but today I saw it was struck on a subdomains because of 429. It would be really helpful if it skips the subdomain or targets out of many when the 429 code is achieved.

**Comment by bootyhunt3r** [comment]
Like skip-on-429

**Comment by kotireddyaluri** [comment]
Yes, skip-on-429 will be more helpful instead of exit-on-429

**Comment by shelld3v** [comment]
Hi, thanks for your suggestions. But I wanna ask a question: what if the user forgot to use that flag? The terminal will be flooded!!

**Comment by kotireddyaluri** [comment]
I mean if dirsearch is running with -l (--url-list) then skip the current url-target for 429 status and continue with next url-target.
if it is exit-on-429, I thought it may exit dirsearch completely without continue with the next url-target. 

I think like this ==> skip-current-target-on-429

**Comment by bootyhunt3r** [comment]
Yep , it can be skip-current-target-on-429

**Comment by shelld3v** [comment]
Hi, thanks! This will be implanted in the next release (after v0.4.2). But do you have a good error message for this? What I am thinking about: `Skipped the target due to 429 status code`

**Comment by shelld3v** [comment]
Also, should we set `skip-on-429` to True by default or to False?

**Comment by bootyhunt3r** [comment]
Yeah "Skipped the target due to 429 status code" is a good error response. 
And for the command , "skip-on-429" is good itself, you should set this to true by default.

**Comment by shelld3v** [comment]
I am seeing if I can add this to v0.4.2, because whenever there is a new update, there will be a delay for the new release

**Comment by bootyhunt3r** [comment]
Yeah man , please try to implant this feature in v0.4.2 , it would be really helpful.
Thank you.
