### ISSUE TITLE
New Suggestion 

### ISSUE THREAD

**Issue by bootyhunt3r** [maurosoria/dirsearch#753]
Hello Team , 
So I have a suggestion for the dirsearch , so from my experience , whenever I run run dirsearch on a target and it throws a file greater than 10-15 mbs , the bruteforced directories doesn't work , so can you add a feature to like discard the target if the file exceeds 10 mb ? That would be a really cool feature in my opinion , what do you think ?

**Comment by shelld3v** [comment]
Hmmm! Sounds good

**Comment by bootyhunt3r** [comment]
Yeah , it would be a really helpful feature.

**Comment by shelld3v** [comment]
We love new feature ideas!! Feel free to give us some ;) This seems like a bug rather than a feature request

**Comment by bootyhunt3r** [comment]
So , will you be doing something on this thing ? 
Thank you in advance tho.

**Comment by shelld3v** [comment]
Of course, this is our job =)

**Comment by bootyhunt3r** [comment]
Thanks , and any idea till when this update will be implemented ? Just a rough idea.

**Comment by shelld3v** [comment]
Idk, it usually takes a few minutes or an hour, rarely few days. But, it's almost Lunar New Year's Eve right now in my country, I can't fix it right now! I think it will be 3 days after

**Comment by shelld3v** [comment]
Hey @bootyhunt3r, did you see any error traceback? If yes, can u pls post it here?

**Comment by bootyhunt3r** [comment]
Did you implante this ?

**Comment by shelld3v** [comment]
Haven't yet.

**Comment by bootyhunt3r** [comment]
No, I have not seen any error ...

**Comment by shelld3v** [comment]
It only gets stuck?

**Comment by bootyhunt3r** [comment]
Yeah ..it's getting struck sometimes

**Comment by shelld3v** [comment]
Hey, I just forgot, you can currently use the `--maximal` flag. I don't know does it work or not, but, why don't give it a try? :)

**Comment by bootyhunt3r** [comment]
This is for the stuck issue ?

**Comment by shelld3v** [comment]
yeah

**Comment by bootyhunt3r** [comment]
Hello bro , I hope you are well !!
Have you started working on that issue ?

**Comment by shelld3v** [comment]
Sorry, forgot about that. I'm going to do it now!!

**Comment by bootyhunt3r** [comment]
COol !!!

**Comment by shelld3v** [comment]
But we also need to do some tests to find the root cause, do you have any website that can cause this stuck?

**Comment by shelld3v** [comment]
Can you do some screenshots?

**Comment by shelld3v** [comment]
Did the `--maximal` flag work?

**Comment by bootyhunt3r** [comment]
I am actually not really sure how to use maximal flag ..can you help ?

**Comment by shelld3v** [comment]
`python3 dirsearch.py -e php -u https://example.com --maximal 10000000`

**Comment by bootyhunt3r** [comment]
Hey man , i don't know why vut whenever I am using my dirsearch on my vps with the screen , it is automatically getting killed , what could be the reason , any idea ?

**Comment by shelld3v** [comment]
You can try to copy terminal output and paste it here!

**Comment by shelld3v** [comment]
Hmm, you didn't have that problem before?

**Comment by bootyhunt3r** [comment]
No actually, there was no problem earlier,  i don't whether it's the site or what , but am trring with less threads , let's see how it goes with it.

**Comment by bootyhunt3r** [comment]
Hey man , 
SO I think it's working good now , I turned down the threads to 50 , now waiting for that update of yours.

**Comment by shelld3v** [comment]
Well, I need to reproduce this! An example of a target?

**Comment by bootyhunt3r** [comment]
I was testing this on a private programme, but slso on un.org

**Comment by shelld3v** [comment]
What is the path cause stuck in **un.org**

**Comment by bootyhunt3r** [comment]
Hey sorry for the late reply , seems like it is working good now, no worries.

**Comment by shelld3v** [comment]
Close this?

**Comment by bootyhunt3r** [comment]
No i think you got somethin wrong , I want the update to like , if the file size exceeds 5 or 10 mb , stop it at 10 mb. You got it ?

**Comment by bootyhunt3r** [comment]
The issue that I told you at the beginning

**Comment by shelld3v** [comment]
What about that `--maximal` flag? Have you tried it?

**Comment by bootyhunt3r** [comment]
I tried but i don't think that works , can you also try that ?

**Comment by shelld3v** [comment]
I need the path that will cause the stuck on **un.org** to can reproduce!

**Comment by bootyhunt3r** [comment]
Hey sorry for the late reply , my laptop was broken :c 
I am not getting what are you asking , what do you mean by path ?

**Comment by shelld3v** [comment]
I mean, there is a path, for example `/download` that when you hit it: `http://un.org/download`, it will return a huge response body, and make dirsearch stuck! If you don't know that path, you can let me know the wordlist you used.

**Comment by bootyhunt3r** [comment]
I used your in tool's wordlist , nothing out of anywhere.

**Comment by shelld3v** [comment]
Okay, I will check this soon

**Comment by bootyhunt3r** [comment]
Hey man , hope you're okay !
Are you looking into the enhancement ? And any idea till when you would be able to give this feature ?

**Comment by shelld3v** [comment]
Hey, I was able to reproduce it, but will take time to fix this stuff, remember that I also have my personal life. You can now dirsearch other hosts, until I fix this

**Comment by shelld3v** [comment]
Hi there, my debugger shows that there is a connection error, not because of the response size. This is the server problem

**Comment by shelld3v** [comment]
Hey, can you check back? I believe that the server is delaying the response, not the response is too huge

**Comment by DarkRed777** [comment]
> Hello Team ,
> So I have a suggestion for the dirsearch , so from my experience , whenever I run run dirsearch on a target and it throws a file greater than 10-15 mbs , the bruteforced directories doesn't work , so can you add a feature to like discard the target if the file exceeds 10 mb ? That would be a really cool feature in my opinion , what do you think ?


BTW, in such scenarios you may try HEAD HTTP verb (default is GET). That may help, give a try anyways.
--http-method=HEAD

**Comment by shelld3v** [comment]
I am closing this, feel free to ask for re-opening if you believe the issue is still there

**Comment by shelld3v** [comment]
Hello @bootyhunt3r, I finally found the solution for this problem. The fix will be merged soon
