### ISSUE TITLE
I fixed this issue please give me my money

### ISSUE THREAD

**Issue by Lucifer733** [maurosoria/dirsearch#754]
Please close this if you fixed it!

_Originally posted by @shelld3v in https://github.com/maurosoria/dirsearch/issues/688#issuecomment-766743970_

**Comment by Lucifer733** [comment]
Yes I fixed  this issue  please  give me my money

**Comment by Lucifer733** [comment]
Do you hard work I support you

**Comment by shelld3v** [comment]
lol
