### ISSUE TITLE
proxy option VS http_proxy var in .bashrc

### ISSUE THREAD

**Issue by alfonsocaponi** [maurosoria/dirsearch#755]
If I specify option --proxy=1.1.1.1:1234 but I've "http_proxy=http://2.2.2.2:8888" var configured in .bashrc,
http_proxy var wins on proxy option... dirsearch will use 2.2.2.2 proxy :(

Is that correct or a bug?

**Comment by shelld3v** [comment]
That seems like a system behavior. Nothing we can do with this!

**Comment by shelld3v** [comment]
Close this if it has been done

**Comment by alfonsocaponi** [comment]
> 
> 
> That seems like a system behavior. Nothing we can do with this!

Mmhhh is there a chance to "unset var" inside python code and to use --proxy option value?

**Comment by shelld3v** [comment]
> > That seems like a system behavior. Nothing we can do with this!
> 
> Mmhhh is there a chance to "unset var" inside python code and to use --proxy option value?

I think no!

**Comment by shelld3v** [comment]
> > That seems like a system behavior. Nothing we can do with this!
> 
> Mmhhh is there a chance to "unset var" inside python code and to use --proxy option value?

Hi, actually we could, but we don't know if this is a good idea or not? Do users really like to see dirsearch overwrite the Linux system proxy?

**Comment by shelld3v** [comment]
Do you mind closing this if you don't have any further question?

**Comment by alfonsocaponi** [comment]
Close it. Thank you

**Comment by shelld3v** [comment]
> Close it. Thank you

Why didn't you close it?
