### ISSUE TITLE
python3 dirsearch.py -u https://target

### ISSUE THREAD

**Issue by magup007** [maurosoria/dirsearch#756]
### What is the current behavior?

What actually happens?

### What is the expected behavior?

What it should be instead?

### Any additional information?

OS, python version, screenshots, dirsearch command, console output, ...?

#### Checker:
 - [x] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
Spam

**Comment by shelld3v** [comment]
@maurosoria can you close this?
