### ISSUE TITLE
Batch Reports with Pretty Formatting

### ISSUE THREAD

**Issue by wdahlenburg** [maurosoria/dirsearch#762]
### What is the feature?

Dirsearch has several methods of ingesting multiple urls to run at one time (stdin or via a list). When these modes are used, there is an individual report written to reports/\<host>/ or reports/BATCH*/\<host>. A user can also specify a report type (simple, plain, json, xml, markdown, csv). 

It would be great if when you specified the report type that a single "pretty" report is written to the specified output file. Currently that file is either overwritten by the last url details or dirsearch writes an ugly report with duplicate metadata and inconsistent formatting.

### What is the workflow?

1. User submits multiple urls to be scanned with dirsearch and requests a report format
    ```
    $ dirsearch -l urls.txt --json-report my-report.json
    $ cat urls.txt | dirsearch --stdin --json-report my-report.json
    ```
2. Dirsearch performs regular content discovery
3. Dirsearch writes the standard plaintext report to reports/BATCH*/\<host>
4. Dirsearch writes a single report to my-report.json including the scan details from every target

How does it work?

A json example could look like the following

```json
{
    "info": {
        "time": "Sat Feb 20 00:00:00 2021"
    },
    "results": {
        "https://example.com": [
            {
                "content-length": 10,
                "path": "/index.html",
                "redirect": null,
                "status": 200
            }

        ],
        "https://foobar.com": [
            {
                "content-length": 150,
                "path": "/admin.php",
                "redirect": null,
                "status": 401
            }

        ],
    }
}
```

An xml example could look like the following:

```xml
<?xml version="1.0"?>
<dirsearchScan time="Sat Feb 20 00:00:00 2021">
    <target url="http://example.com">
        <info path="/index.html">
            <status>200</status>
            <contentLength>10</contentLength>
            <redirect>None</redirect>
        </info>
    </target>
    <target url="http://foobar.com">
        <info path="/admin.php">
            <status>404</status>
            <contentLength>150</contentLength>
            <redirect>None</redirect>
        </info>
    </target>
</dirsearchScan>
```

### What is the use case?

Batch input with reports currently append single reports to the desired output file. A user should be able to get a single report written in a consistent format that includes data from all scans.

When and who will use this?

Any users that submit multiple urls at once and request a single report will use this.

#### Checker:

- [ ] This feature is in scope for the dirsearch purpose
?  Unsure

**Comment by shelld3v** [comment]
Hi, currently there is a bug that I am trying to fix, is that when you use `--json-report report.json` with a list of URLs, you will only get the report for one host! I will try to fix this soon!

**Comment by shelld3v** [comment]
Hey, the fact that you can edit the batch reports format, by editing `default.conf`. But there is currently a bug: #766

**Comment by shelld3v** [comment]
You can close this now

**Comment by wdahlenburg** [comment]
Hey @shelld3v the ```default.conf``` is a great addition for common options, however this issue was intended to update reports with a common format when multiple hosts are requested. 

Currently with the first example I gave will get something like the following for a list of urls:

```json
{
    "time": "Sat Feb 20 00:00:00 2021",
    "https://example.com": [
            {
                "content-length": 10,
                "path": "/index.html",
                "redirect": null,
                "status": 200
            }
        ]
  }{
    "time": "Sat Feb 20 00:00:05 2021",
    "https://foobar.com": [
            {
                "content-length": 150,
                "path": "/admin.php",
                "redirect": null,
                "status": 401
            }
    ]
}
```

The format works fine for a single host, but is repetitive and unfriendly to parse for multiple hosts in a single report.

**Comment by shelld3v** [comment]
> Hey @shelld3v the `default.conf` is a great addition for common options, however this issue was intended to update reports with a common format when multiple hosts are requested.
> 
> Currently with the first example I gave will get something like the following for a list of urls:
> 
> ```json
> {
>     "time": "Sat Feb 20 00:00:00 2021",
>     "https://example.com": [
>             {
>                 "content-length": 10,
>                 "path": "/index.html",
>                 "redirect": null,
>                 "status": 200
>             }
>         ]
>   }{
>     "time": "Sat Feb 20 00:00:05 2021",
>     "https://foobar.com": [
>             {
>                 "content-length": 150,
>                 "path": "/admin.php",
>                 "redirect": null,
>                 "status": 401
>             }
>     ]
> }
> ```
> 
> The format works fine for a single host, but is repetitive and unfriendly to parse for multiple hosts in a single report.

I may not understand what do u mean, but please change the `autosave-report-format`

**Comment by wdahlenburg** [comment]
I'll draft up a PR in the next few days and tag it back to this. I'll include some comparisons with the output of the master branch vs the PR branch. 

The jist is that multiple json blobs are being written instead of a singular blob. Basically the batch report should loop through the results for each host and print them in a single report instead of multiple.

**Comment by wdahlenburg** [comment]
PR Merged. Closing
