### ISSUE TITLE
[bug] When calling dirsearch in other scripts, ‘The wordlist file does not exist’ error will be reported

### ISSUE THREAD

**Issue by zongdeiqianxing** [maurosoria/dirsearch#765]
![image](https://user-images.githubusercontent.com/34082644/109321543-37b07d80-788c-11eb-97e7-81c92fef2514.png)

![image](https://user-images.githubusercontent.com/34082644/109321315-fae48680-788b-11eb-9470-9c5a214bd7bc.png)

**Comment by shelld3v** [comment]
The wordlist is located at `db/dicc.txt`. Can you check if it's still there?

**Comment by zongdeiqianxing** [comment]
> The wordlist is located at `db/dicc.txt`. Can you check if it's still there?

The problem is that the dictionary path is a relative path, so that the dictionary path cannot be found when calling dirsearch in other projects.

for example , When I add this line of code, the program will continue to execute, but there will still be errors later
![image](https://user-images.githubusercontent.com/34082644/109370198-458cef80-78da-11eb-8b13-3d118262a000.png)

![image](https://user-images.githubusercontent.com/34082644/109370325-cd72f980-78da-11eb-9384-fe922e0c74d7.png)

**Comment by shelld3v** [comment]
First, I want to suggest u to update your dirsearch. Second, what would be the solution for this (do you think)?
