### ISSUE TITLE
--proxy option ignored in latest version?

### ISSUE THREAD

**Issue by halfluke** [maurosoria/dirsearch#771]
### What is the current behavior?
no request goes through burp when running for example
python3 dirsearch.py -u https://www.google.com  -e txt,log,bak,zip --proxy 127.0.0.1:8080

### What is the expected behavior?
I would expect to see requests logged in Burp...

### Any additional information?
https://github.com/maurosoria/dirsearch/issues/246 closed issue as a reference
running dirsearch as root, in case it matters
I tried different positions for the --proxy parameter, with and without =, with and without prepending "http://"
I'm sure it worked in the past with previous versions

OS, python version, screenshots, dirsearch command, console output, ...?

#### Checker:
 - [ x ] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
Hi, I tested a few minutes ago with the latest commit of dirsearch and everything worked fine! Can you give your command?

**Comment by halfluke** [comment]
Hmm exactly the one that I put on top. Could it be an environmental issue? It is a brand new kali...

**Comment by shelld3v** [comment]
Try these things:
- git clone dirsearch again
- Make sure there isn't `http_proxy` var in .bashrc
- Check the proxy config

If you don't mind: Did the scan work? Or it got stuck?

**Thanks**

**Comment by halfluke** [comment]
the scan worked ignoring the proxy, but look... I've found something:
latest version: the proxy is ignored if the url is with https, but not with http.
version 0.3.9: the proxy is never ignored.
Any chance you can repro this?

root@kali:~/dirsearch# python3 dirsearch.py -u https://www.google.com -e html,txt,log,bak,js --proxy 127.0.0.1:8080

  _|. _ _  _  _  _ _|_    v0.4.1                                                                                                                                      
 (_||| _) (/_(_|| (_| )                                                                                                                                               
                                                                                                                                                                      
Extensions: html, txt, log, bak, js | HTTP method: GET | Threads: 30 | Wordlist size: 10896

Error Log: /root/dirsearch/logs/errors-21-03-11_12-19-40.log

Target: https://www.google.com/                                                                                                                                       
                                                                                                                                                                      
Output File: /root/dirsearch/reports/www.google.com/_21-03-11_12-19-40.txt

[12:19:40] Starting: 
[12:19:41] 302 -  231B  - /%2e%2e//google.com  ->  https://www.google.com//google.com
[12:19:41] 400 -    2KB - /log              
CTRL+C detected: Pausing threads, please wait...                                                                                        
[e]xit / [c]ontinue: e                                         
 
Canceled by the user
root@kali:~/dirsearch# python3 dirsearch.py -u http://www.google.com -e html,txt,log,bak,js --proxy 127.0.0.1:8080

  _|. _ _  _  _  _ _|_    v0.4.1                                                                                                                                      
 (_||| _) (/_(_|| (_| )                                                                                                                                               
                                                                                                                                                                      
Extensions: html, txt, log, bak, js | HTTP method: GET | Threads: 30 | Wordlist size: 10896

Error Log: /root/dirsearch/logs/errors-21-03-11_12-19-59.log

Target: http://www.google.com/                                                                                                                                        
                                                                                                                                                                      
Error with the proxy: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: http://www.google.com:80/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ba1a17550>: Failed to establish a new connection: [Errno 111] Connection refused')))

Task Completed


-----------------------------------------

python3 dirsearch.py -u http://us.curopayequity.com -e html,txt,log,bak,js --proxy 127.0.0.1:8080

 _|. _ _  _  _  _ _|_    v0.3.9                                                                                                                                       
(_||| _) (/_(_|| (_| )                                                                                                                                                
                                                                                                                                                                      
Extensions: html, txt, log, bak, js | HTTP method: get | Threads: 10 | Wordlist size: 7568

Error Log: /root/Downloads/dirsearch/logs/errors-21-03-11_12-15-40.log

Target: http://us.curopayequity.com                                                                                                                                   
                                                                                                                                                                      
Error with the proxy: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: http://18.208.234.198:80/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionRefusedError(111, 'Connection refused')))

Task Completed                                                                                                                                                        
root@kali:~/Downloads/dirsearch# python3 dirsearch.py -u https://www.google.com -e html,txt,log,bak,js --proxy 127.0.0.1:8080

 _|. _ _  _  _  _ _|_    v0.3.9                                                                                                                                       
(_||| _) (/_(_|| (_| )                                                                                                                                                
                                                                                                                                                                      
Extensions: html, txt, log, bak, js | HTTP method: get | Threads: 10 | Wordlist size: 7568

Error Log: /root/Downloads/dirsearch/logs/errors-21-03-11_12-20-44.log

Target: https://www.google.com                                                                                                                                        
                                                                                                                                                                      
Error with the proxy: HTTPSConnectionPool(host='216.58.204.68', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionRefusedError(111, 'Connection refused')))

Task Completed

**Comment by shelld3v** [comment]
Hmm, the latest version is 0.4.2!

**Comment by halfluke** [comment]
Downloadable from where sorry? I've just cloned it again and:
root@kali:~/Downloads/dirsearch# python3 dirsearch.py --version
dirsearch v0.4.1

**Comment by shelld3v** [comment]
> Downloadable from where sorry? I've just cloned it again and:
> root@kali:~/Downloads/dirsearch# python3 dirsearch.py --version
> dirsearch v0.4.1

Ph, my bad, I thought we released v0.4.2! I will check back this soon

**Comment by shelld3v** [comment]
Hi @halfluke,

I checked back and the proxy feature is working well, can you try to git clone this again? Thank you!

**Comment by halfluke** [comment]
It looks good now. Did you fix it with a recent change in the code or .. no idea? :)

**Comment by shelld3v** [comment]
> It looks good now. Did you fix it with a recent change in the code or .. no idea? :)

I didn't do anything =) Can you close this issue?

**Comment by halfluke** [comment]
so weird... now it behaves properly and if Burp is not started I simply get
Error with the proxy: http://127.0.0.1:8080
in all cases.
Same Kali machine as before. Oh well...
