### ISSUE TITLE
dirsearch Can it be used with the burp suite?

### ISSUE THREAD

**Issue by Phoenix1112** [maurosoria/dirsearch#773]
hello. thanks for this project.. can we use dirseach with burp suite?? So can we proxy dirsearch results to the burp suite program?

**Comment by shelld3v** [comment]
Yeah, of course. You can use the `--proxy` option, set to `127.0.0.1:8080`. OR, you can use the `--replay-proxy`, to proxy only requests with paths that have been found interesting, not all requests. I strongly advise you to use the `--replay-proxy` (Set it to `127.0.0.1:8080` too)

**Comment by Phoenix1112** [comment]
thanks <3

**Comment by shelld3v** [comment]
You can close this now
