### ISSUE TITLE
Report Success on Errors

### ISSUE THREAD

**Issue by RocketNinja15** [maurosoria/dirsearch#775]
### What is the current behavior?
Example:  https://schoop.app/php 

It reported that as true, but if you visit it, it will say Error-Not Found

### What is the expected behavior?
It not display those as true.
What it should be instead?
Look for error or page not found
### Any additional information?

OS, python version, screenshots, dirsearch command, console output, ...?
```  _|. _ _  _  _  _ _|_    v0.4.1
 (_||| _) (/_(_|| (_| )

Extensions: php, aspx, jsp, html, js | HTTP method: GET | Threads: 30 | Wordlist size: 10848

Error Log: C:\Users\Rocket\dirsearch\logs\errors-21-03-16_11-54-18.log

Target: http://schoop.app/

Output File: C:\Users\Rocket\dirsearch\reports\schoop.app\_21-03-16_11-54-18.txt

[11:54:18] Starting:
[11:54:19] 301 -    0B  - /php  ->  https://schoop.app/php
[11:54:19] 301 -    0B  - /html  ->  https://schoop.app/html
[11:54:19] 301 -    0B  - /jsp  ->  https://schoop.app/jsp
[11:54:19] 301 -    0B  - /aspx  ->  https://schoop.app/aspx
[11:54:19] 301 -    0B  - /js  ->  https://schoop.app/js
[11:54:39] 301 -    0B  - /DocProject/Help/html  ->  https://schoop.app/DocProject/Help/html
[11:54:52] 301 -    0B  - /account/login.shtml  ->  https://schoop.app/account/login.shtml
[11:54:52] 301 -    0B  - /accounts/login.shtml  ->  https://schoop.app/accounts/login.shtml
[11:54:54] 301 -    0B  - /adm.shtml  ->  https://schoop.app/adm.shtml
[11:54:54] 301 -    0B  - /adminphp  ->  https://schoop.app/adminphp
[11:54:54] 301 -    0B  - /adminaspx  ->  https://schoop.app/adminaspx
[11:54:54] 301 -    0B  - /adminjsp  ->  https://schoop.app/adminjsp
[11:54:54] 301 -    0B  - /adminjs  ->  https://schoop.app/adminjs
[11:54:54] 301 -    0B  - /adminhtml  ->  https://schoop.app/adminhtml
[11:54:55] 301 -    0B  - /admin.shtml  ->  https://schoop.app/admin.shtml
[11:54:56] 301 -    0B  - /admin/portalcollect.php?f=http://xxx&t=js  ->  https://schoop.app/admin/portalcollect.php?f=http://xxx&t=js
[11:55:00] 301 -    0B  - /admin_js  ->  https://schoop.app/admin_js
[11:55:06] 301 -    0B  - /administrator.shtml  ->  https://schoop.app/administrator.shtml
[11:55:15] 301 -    0B  - /cache_html  ->  https://schoop.app/cache_html
[11:55:22] 301 -    0B  - /core/fragments/moduleInfo.phtml  ->  https://schoop.app/core/fragments/moduleInfo.phtml
[11:55:22] 301 -    0B  - /controlpanel.shtml  ->  https://schoop.app/controlpanel.shtml
[11:55:33] 301 -    0B  - /getfiles.php?f=http://xxx&t=js  ->  https://schoop.app/getfiles.php?f=http://xxx&t=js
[11:55:35] 301 -    0B  - /host-manager/html  ->  https://schoop.app/host-manager/html
[11:55:37] 301 -    0B  - /index.shtml  ->  https://schoop.app/index.shtml
[11:55:42] 301 -    0B  - /login.shtml  ->  https://schoop.app/login.shtml
[11:55:44] 301 -    0B  - /logon/logon.shtml  ->  https://schoop.app/logon/logon.shtml
[11:55:45] 301 -    0B  - /manager/html  ->  https://schoop.app/manager/html
[11:55:47] 301 -    0B  - /members.shtml  ->  https://schoop.app/members.shtml
[11:55:49] 301 -    0B  - /myadminphp  ->  https://schoop.app/myadminphp
[11:55:49] 301 -    0B  - /myadminaspx  ->  https://schoop.app/myadminaspx
[11:55:49] 301 -    0B  - /myadminjsp  ->  https://schoop.app/myadminjsp
[11:55:49] 301 -    0B  - /myadminhtml  ->  https://schoop.app/myadminhtml
[11:55:49] 301 -    0B  - /myadminjs  ->  https://schoop.app/myadminjs
[11:55:50] 301 -    0B  - /netadmin.shtml  ->  https://schoop.app/netadmin.shtml
[11:55:51] 301 -    0B  - /opa-debug-js  ->  https://schoop.app/opa-debug-js
[11:55:59] 301 -    0B  - /public_html  ->  https://schoop.app/public_html
[11:56:06] 301 -    0B  - /signin.shtml  ->  https://schoop.app/signin.shtml
```
#### Checker:
 - [x ] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
Hi, thanks for your issue. This is proof of how bad the current wildcard filter works. And 2 months ago, as soon as I saw this behavior, I sent the maintainer a PR with a really good wildcard check function as a replacement for the old one, but he said that it isn't reliable, and can't make sure it won't have any further issue. I and he are still having a conversation about that PR, but I believe it will be merged soon.

PR: #749
(*If you have time, you can git that PR and check if the update works well with your target. Command to install:* `git clone https://github.com/shelld3v/dirsearch -b wildcard-fix`)

**Comment by zane-programs** [comment]
> ### What is the current behavior?
> Example: https://schoop.app/php
> 
> It reported that as true, but if you visit it, it will say Error-Not Found
> 
> ### What is the expected behavior?
> It not display those as true.
> What it should be instead?
> Look for error or page not found
> 
> ### Any additional information?
> OS, python version, screenshots, dirsearch command, console output, ...?
> 
> ```
>  (_||| _) (/_(_|| (_| )
> 
> Extensions: php, aspx, jsp, html, js | HTTP method: GET | Threads: 30 | Wordlist size: 10848
> 
> Error Log: C:\Users\Rocket\dirsearch\logs\errors-21-03-16_11-54-18.log
> 
> Target: http://schoop.app/
> 
> Output File: C:\Users\Rocket\dirsearch\reports\schoop.app\_21-03-16_11-54-18.txt
> 
> [11:54:18] Starting:
> [11:54:19] 301 -    0B  - /php  ->  https://schoop.app/php
> [11:54:19] 301 -    0B  - /html  ->  https://schoop.app/html
> [11:54:19] 301 -    0B  - /jsp  ->  https://schoop.app/jsp
> [11:54:19] 301 -    0B  - /aspx  ->  https://schoop.app/aspx
> [11:54:19] 301 -    0B  - /js  ->  https://schoop.app/js
> [11:54:39] 301 -    0B  - /DocProject/Help/html  ->  https://schoop.app/DocProject/Help/html
> [11:54:52] 301 -    0B  - /account/login.shtml  ->  https://schoop.app/account/login.shtml
> [11:54:52] 301 -    0B  - /accounts/login.shtml  ->  https://schoop.app/accounts/login.shtml
> [11:54:54] 301 -    0B  - /adm.shtml  ->  https://schoop.app/adm.shtml
> [11:54:54] 301 -    0B  - /adminphp  ->  https://schoop.app/adminphp
> [11:54:54] 301 -    0B  - /adminaspx  ->  https://schoop.app/adminaspx
> [11:54:54] 301 -    0B  - /adminjsp  ->  https://schoop.app/adminjsp
> [11:54:54] 301 -    0B  - /adminjs  ->  https://schoop.app/adminjs
> [11:54:54] 301 -    0B  - /adminhtml  ->  https://schoop.app/adminhtml
> [11:54:55] 301 -    0B  - /admin.shtml  ->  https://schoop.app/admin.shtml
> [11:54:56] 301 -    0B  - /admin/portalcollect.php?f=http://xxx&t=js  ->  https://schoop.app/admin/portalcollect.php?f=http://xxx&t=js
> [11:55:00] 301 -    0B  - /admin_js  ->  https://schoop.app/admin_js
> [11:55:06] 301 -    0B  - /administrator.shtml  ->  https://schoop.app/administrator.shtml
> [11:55:15] 301 -    0B  - /cache_html  ->  https://schoop.app/cache_html
> [11:55:22] 301 -    0B  - /core/fragments/moduleInfo.phtml  ->  https://schoop.app/core/fragments/moduleInfo.phtml
> [11:55:22] 301 -    0B  - /controlpanel.shtml  ->  https://schoop.app/controlpanel.shtml
> [11:55:33] 301 -    0B  - /getfiles.php?f=http://xxx&t=js  ->  https://schoop.app/getfiles.php?f=http://xxx&t=js
> [11:55:35] 301 -    0B  - /host-manager/html  ->  https://schoop.app/host-manager/html
> [11:55:37] 301 -    0B  - /index.shtml  ->  https://schoop.app/index.shtml
> [11:55:42] 301 -    0B  - /login.shtml  ->  https://schoop.app/login.shtml
> [11:55:44] 301 -    0B  - /logon/logon.shtml  ->  https://schoop.app/logon/logon.shtml
> [11:55:45] 301 -    0B  - /manager/html  ->  https://schoop.app/manager/html
> [11:55:47] 301 -    0B  - /members.shtml  ->  https://schoop.app/members.shtml
> [11:55:49] 301 -    0B  - /myadminphp  ->  https://schoop.app/myadminphp
> [11:55:49] 301 -    0B  - /myadminaspx  ->  https://schoop.app/myadminaspx
> [11:55:49] 301 -    0B  - /myadminjsp  ->  https://schoop.app/myadminjsp
> [11:55:49] 301 -    0B  - /myadminhtml  ->  https://schoop.app/myadminhtml
> [11:55:49] 301 -    0B  - /myadminjs  ->  https://schoop.app/myadminjs
> [11:55:50] 301 -    0B  - /netadmin.shtml  ->  https://schoop.app/netadmin.shtml
> [11:55:51] 301 -    0B  - /opa-debug-js  ->  https://schoop.app/opa-debug-js
> [11:55:59] 301 -    0B  - /public_html  ->  https://schoop.app/public_html
> [11:56:06] 301 -    0B  - /signin.shtml  ->  https://schoop.app/signin.shtml
> ```
> 
> #### Checker:
> * [x ] I tested in the latest version of dirsearch

Dude, who are you and why are you trying to get into my stuff? If you want to talk about how it works, I'd be happy to chat, but it seems like you're intentionally trying to break into Schoop. What's your deal???

**Comment by shelld3v** [comment]
> ### What is the current behavior?
> Example: https://schoop.app/php
> 
> It reported that as true, but if you visit it, it will say Error-Not Found
> 
> ### What is the expected behavior?
> It not display those as true.
> What it should be instead?
> Look for error or page not found
> 
> ### Any additional information?
> OS, python version, screenshots, dirsearch command, console output, ...?
> 
> ```
>  (_||| _) (/_(_|| (_| )
> 
> Extensions: php, aspx, jsp, html, js | HTTP method: GET | Threads: 30 | Wordlist size: 10848
> 
> Error Log: C:\Users\Rocket\dirsearch\logs\errors-21-03-16_11-54-18.log
> 
> Target: http://schoop.app/
> 
> Output File: C:\Users\Rocket\dirsearch\reports\schoop.app\_21-03-16_11-54-18.txt
> 
> [11:54:18] Starting:
> [11:54:19] 301 -    0B  - /php  ->  https://schoop.app/php
> [11:54:19] 301 -    0B  - /html  ->  https://schoop.app/html
> [11:54:19] 301 -    0B  - /jsp  ->  https://schoop.app/jsp
> [11:54:19] 301 -    0B  - /aspx  ->  https://schoop.app/aspx
> [11:54:19] 301 -    0B  - /js  ->  https://schoop.app/js
> [11:54:39] 301 -    0B  - /DocProject/Help/html  ->  https://schoop.app/DocProject/Help/html
> [11:54:52] 301 -    0B  - /account/login.shtml  ->  https://schoop.app/account/login.shtml
> [11:54:52] 301 -    0B  - /accounts/login.shtml  ->  https://schoop.app/accounts/login.shtml
> [11:54:54] 301 -    0B  - /adm.shtml  ->  https://schoop.app/adm.shtml
> [11:54:54] 301 -    0B  - /adminphp  ->  https://schoop.app/adminphp
> [11:54:54] 301 -    0B  - /adminaspx  ->  https://schoop.app/adminaspx
> [11:54:54] 301 -    0B  - /adminjsp  ->  https://schoop.app/adminjsp
> [11:54:54] 301 -    0B  - /adminjs  ->  https://schoop.app/adminjs
> [11:54:54] 301 -    0B  - /adminhtml  ->  https://schoop.app/adminhtml
> [11:54:55] 301 -    0B  - /admin.shtml  ->  https://schoop.app/admin.shtml
> [11:54:56] 301 -    0B  - /admin/portalcollect.php?f=http://xxx&t=js  ->  https://schoop.app/admin/portalcollect.php?f=http://xxx&t=js
> [11:55:00] 301 -    0B  - /admin_js  ->  https://schoop.app/admin_js
> [11:55:06] 301 -    0B  - /administrator.shtml  ->  https://schoop.app/administrator.shtml
> [11:55:15] 301 -    0B  - /cache_html  ->  https://schoop.app/cache_html
> [11:55:22] 301 -    0B  - /core/fragments/moduleInfo.phtml  ->  https://schoop.app/core/fragments/moduleInfo.phtml
> [11:55:22] 301 -    0B  - /controlpanel.shtml  ->  https://schoop.app/controlpanel.shtml
> [11:55:33] 301 -    0B  - /getfiles.php?f=http://xxx&t=js  ->  https://schoop.app/getfiles.php?f=http://xxx&t=js
> [11:55:35] 301 -    0B  - /host-manager/html  ->  https://schoop.app/host-manager/html
> [11:55:37] 301 -    0B  - /index.shtml  ->  https://schoop.app/index.shtml
> [11:55:42] 301 -    0B  - /login.shtml  ->  https://schoop.app/login.shtml
> [11:55:44] 301 -    0B  - /logon/logon.shtml  ->  https://schoop.app/logon/logon.shtml
> [11:55:45] 301 -    0B  - /manager/html  ->  https://schoop.app/manager/html
> [11:55:47] 301 -    0B  - /members.shtml  ->  https://schoop.app/members.shtml
> [11:55:49] 301 -    0B  - /myadminphp  ->  https://schoop.app/myadminphp
> [11:55:49] 301 -    0B  - /myadminaspx  ->  https://schoop.app/myadminaspx
> [11:55:49] 301 -    0B  - /myadminjsp  ->  https://schoop.app/myadminjsp
> [11:55:49] 301 -    0B  - /myadminhtml  ->  https://schoop.app/myadminhtml
> [11:55:49] 301 -    0B  - /myadminjs  ->  https://schoop.app/myadminjs
> [11:55:50] 301 -    0B  - /netadmin.shtml  ->  https://schoop.app/netadmin.shtml
> [11:55:51] 301 -    0B  - /opa-debug-js  ->  https://schoop.app/opa-debug-js
> [11:55:59] 301 -    0B  - /public_html  ->  https://schoop.app/public_html
> [11:56:06] 301 -    0B  - /signin.shtml  ->  https://schoop.app/signin.shtml
> ```
> 
> #### Checker:
> * [x ] I tested in the latest version of dirsearch

Btw, you are doing this in the wrong way, must be: `python dirsearch.py -u https://schoop.app/ ...` (`https`, not `http`)
