### ISSUE TITLE
recursion

### ISSUE THREAD

**Issue by L10nK1n6** [maurosoria/dirsearch#776]
The alpha version of recursion seems to have some problems. The -r option is now turned on by default?

**Comment by shelld3v** [comment]
Yeah, I advice you to install dirsearch with this command: `git clone https://github.com/maurosoria/dirsearch`, not install dirsearch by release.

**Comment by shelld3v** [comment]
Hi @L10nK1n6,

This is an old bug, please update your dirsearch

**Comment by shelld3v** [comment]
Have you fixed this?
