### ISSUE TITLE
dirsearch v0.4.1 user-agent config seems broken

### ISSUE THREAD

**Issue by benjgos** [maurosoria/dirsearch#778]
### What is the current behavior?

Trying to change the user agent from either command line --user-agent= or from the default.conf file doesn't actually change the user-agent. It's always "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
note that using --random-agent also doesn't seem to change anything. i would assume it would go through db/user-agents.txt, but it doesn't seem to do anything but send the same as above.

### What is the expected behavior?

The defined user-agent should be sent.

### Any additional information?

Running on Kali, python 3.9.1

#### Checker:
 - [X] I tested in the latest version of dirsearch

**Comment by shelld3v** [comment]
Hi, the fix has been submitted in my PR #749. It will take several days more to get it merged, because @maurosoria is currently busy now. Thank you for your patient
