### ISSUE TITLE
Ever File in lib comes with UpperCase in the first letter

### ISSUE THREAD

**Issue by lealcb** [maurosoria/dirsearch#779]
With that comes some error like

  File "dirsearch.py", line 28, in <module>
    from lib.controller import Controller
  File "D:\dirsearch-master\lib\controller\__init__.py", line 1, in <module>
    from .controller import *  # noqa: F401
ModuleNotFoundError: No module named 'lib.controller.controller'

I just rename it all to lowerCase and fix the issue.

**Comment by shelld3v** [comment]
Hi, what version are you using?
