### ISSUE TITLE
exit on -max-time

### ISSUE THREAD

**Issue by benjgos** [maurosoria/dirsearch#781]
### What is the feature?

Would be great if dirsearch could exit after an x amount of minutes.

### What is the workflow?

if dirsearch hasn't exited by X it exits with a message stating exited due to max-time reached (or whatever)

### What is the use case?

there are web servers that have rate limiting set so dirsearch will scan a batch, pause for a few seconds, scan a batch, etc... on local network i've seen this take upwards of 6 hours on the 1 server.

#### Checker:

- [X] This feature is in scope for the dirsearch purpose

**Comment by shelld3v** [comment]
Hi, that has already in my TODO list, and can easily be implemented with some lines of code. But I want to release dirsearch v0.4.2 first

**Comment by benjgos** [comment]
excellent thanks. currently i'm doing it with the timeout command in bash, but it's not quite as graceful as it could be.

**Comment by shelld3v** [comment]
This is our TODO list: https://github.com/maurosoria/dirsearch/issues/384
