### ISSUE TITLE
Request timeout:

### ISSUE THREAD

**Issue by OldMohamm** [maurosoria/dirsearch#783]
### What is the current behavior?

  _|. _ _  _  _  _ _|_    v0.4.1
 (_||| _) (/_(_|| (_| )

Extensions: php, aspx, jsp, html, js | HTTP method: GET | Threads: 30 | Wordlist size: 10861

Error Log: C:\Users\asus\Desktop\dirsearch\logs\errors-21-04-10_01-53-51.log

Target: https://www.example.com/

Output File: C:\Users\asus\Desktop\dirsearch\reports\www.example.com\_21-04-10_01-54-13.txt

[01:54:13] Starting:
Request timeout: https://151.101.113.140:443/iHfC1hWhuAJ3

Task Completed
PS C:\Users\asus\desktop\dirsearch>

OS, python version, screenshots, dirsearch command, console output, ...?

Windows 10 Python 3.9
#### Checker: 
 - [x] I tested in the latest version of dirsearch
![Screenshot (1986)](https://user-images.githubusercontent.com/53377619/114248460-66983400-99a0-11eb-8683-7ac13d7bd33a.png)

**Comment by shelld3v** [comment]
Hi, we have nothing to do with this, this is the server-side problem, the website server didn't respond in time. First, please check if you still can access the web page from your browser, if the webserver is up, then try running dirsearch again with a bigger timeout (using the `--timeout` flag)

Thanks,
Minh

**Comment by OldMohamm** [comment]
Thanks
