### ISSUE TITLE
Reason for Killed

### ISSUE THREAD

**Issue by arbazkiraak** [maurosoria/dirsearch#79]
I See Dirsearch Throwing Out Killed on Passing 35MB of Wordlists .

What could be the Reasons of "Killed" Status?

**Comment by hakluke** [comment]
@arbazkiraak that is a very large wordlist. Perhaps it was using too much memory?

**Comment by mzfr** [comment]
@maurosoria I don't see this issue anymore. I've tested this with 134MB rockyou list and dirsearch works fine. I think we can close this issue.

**Comment by arbazkiraak** [comment]
* I understood,This issue is related to memory

**Comment by normface** [comment]
Learn how to work Out-Of-Memory Killer. It's simple Linux Kernel, kill randomly hunter of big memory process.
