### ISSUE TITLE
Potential bug when specifying a subdirectory with caps in it?

### ISSUE THREAD

**Issue by blinddn0va** [maurosoria/dirsearch#792]
### What is the current behavior?
Currently, when dirsearching "http://localhost:8080/WebGoat" the app will break (see below). But it will work with "http://localhost:8080/webgoat". Unfortunately for me WebGoat only works camelcase style. You cannot access the app with "webgoat". Only WebGoat. 

### Any additional information?

OS, python version, screenshots, dirsearch command, console output, ...?
Kali, latest python
OUTPUT:
──(kali㉿kali)-[~/dirsearch]
└─$ ./dirsearch.py --debug -u http://localhost:8080/WebGoat

  _|. _ _  _  _  _ _|_    v0.4.1
 (_||| _) (/_(_|| (_| )

Extensions: php, aspx, jsp, html, js | HTTP method: GET | Threads: 30 | Wordlist size: 10861

Error Log: /home/kali/dirsearch/logs/errors-21-04-14_22-41-57.log

Target: http://localhost:8080/WebGoat/

Output File: /home/kali/dirsearch/reports/localhost/WebGoat_21-04-14_22-41-57.txt

[22:41:57] Starting: 
Traceback (most recent call last):
  File "/home/kali/dirsearch/./dirsearch.py", line 47, in <module>
    main = Program()
  File "/home/kali/dirsearch/./dirsearch.py", line 43, in __init__
    self.controller = Controller(self.script_path, self.arguments, self.output)
  File "/home/kali/dirsearch/lib/controller/controller.py", line 249, in __init__
    self.prepare()
  File "/home/kali/dirsearch/lib/controller/controller.py", line 698, in prepare
    self.fuzzer.start()
  File "/home/kali/dirsearch/lib/core/fuzzer.py", line 140, in start
    self.setupScanners()
  File "/home/kali/dirsearch/lib/core/fuzzer.py", line 83, in setupScanners
    self.defaultScanner = Scanner(self.requester)
  File "/home/kali/dirsearch/lib/core/scanner.py", line 42, in __init__
    self.setup()
  File "/home/kali/dirsearch/lib/core/scanner.py", line 62, in setup
    self.redirectRegExp = self.generateRedirectRegExp(
TypeError: generateRedirectRegExp() missing 2 required positional arguments: 'secondLoc' and 'secondPath'
                                                                                                                                                                                                   
┌──(kali㉿kali)-[~/dirsearch]
└─$ ./dirsearch.py --debug -u http://localhost:8080/webgoat                                                                                                                                    1 ⨯

  _|. _ _  _  _  _ _|_    v0.4.1
 (_||| _) (/_(_|| (_| )

Extensions: php, aspx, jsp, html, js | HTTP method: GET | Threads: 30 | Wordlist size: 10861

Error Log: /home/kali/dirsearch/logs/errors-21-04-14_22-42-33.log

Target: http://localhost:8080/webgoat/
                                                                                                                                                                                                   
Output File: /home/kali/dirsearch/reports/localhost/webgoat_21-04-14_22-42-33.txt

[22:42:33] Starting: 
                                                                                                                                        
Task Complete

#### Checker:
 - [x ] I tested in the latest version of dirsearch
I pulled the latest version today and also tried with the docker image I built using the dockerfile. 

Hopefully I included helpful info. Let me know if you need anything else from me.

**Comment by shelld3v** [comment]
Hi, this will be fixed soon (after my PR gets merged)!

**Comment by blinddn0va** [comment]
Well that was fast. You fixed it before I even reported it :)

**Comment by gprime31** [comment]
> Well that was fast. You fixed it before I even reported it :)

It's not fixed

**Comment by shelld3v** [comment]
> > Well that was fast. You fixed it before I even reported it :)
> 
> It's not fixed

I sent the fix, waiting to be approved by @maurosoria

**Comment by gprime31** [comment]
> > > Well that was fast. You fixed it before I even reported it :)
> > 
> > 
> > It's not fixed
> 
> I sent the fix, waiting to be approved by @maurosoria

Ok, awesome.
