### ISSUE TITLE
[Feature request] req/s counter

### ISSUE THREAD

**Issue by gprime31** [maurosoria/dirsearch#800]
Hi, first of all great tool !!!
could you put a request per second counter along side the % done and Error counters? because with 200 threads i'd like to know how many req/s are happening.
Thanks, keep up the great work!!!!

**Comment by shelld3v** [comment]
Not a bad idea, I have already thought about it, but the progress bar will be longer and more complex, while I am trying to keep it simple. I will take a look at this to see if it's possible. Thank you for your contribution! Feel free to submit more ideas, I love them, and our tool needs them 👍

**Comment by gprime31** [comment]
> Not a bad idea, I have already thought about it, but the progress bar will be longer and more complex, while I am trying to keep it simple. I will take a look at this to see if it's possible. Thank you for your contribution! Feel free to submit more ideas, I love them, and our tool needs them 👍

No problem, keep up the amazing work!!!!

**Comment by shelld3v** [comment]
Well, I did it. This is the output, what do you think?

```
[20:39:06] Starting:
[20:39:07] 200 -    1KB - /../
[20:39:16] 403 -  345B  - /admin/includes/configure.php~
[20:39:22] 403 -  345B  - /app/config/database.yml~
10.35% | 63 req/s - Last request to: archive.sql
```

**Comment by gprime31** [comment]
I like it!! thank you.

**Comment by shelld3v** [comment]
I am still thinking more before making the decision

**Comment by maurosoria** [comment]
Maybe is time to erase "Last request to:" ...

**Comment by shelld3v** [comment]
> Maybe is time to erase "Last request to:" ...

But it looks good!

**Comment by gprime31** [comment]
Perhaps a flag then?? -req

**Comment by shelld3v** [comment]
> Perhaps a flag then?? -req

I think it's okay to add it to the progress bar

**Comment by gprime31** [comment]
> > Perhaps a flag then?? -req
> 
> I think it's okay to add it to the progress bar

Awesome, can't wait to try it!!!
