### ISSUE TITLE
Some URLs can be scanned and some will report errors

### ISSUE THREAD

**Issue by hanchen666** [maurosoria/dirsearch#813]
![图片](https://user-images.githubusercontent.com/35289748/116035962-78fcb800-a698-11eb-9e11-b19882cc57fd.png)

**Comment by maurosoria** [comment]
Hello @hanchen666 ,

Can you update to last version? There was a similar issue recently that was already patched. If the problem persist, please inform us.

Regards,
Mauro

**Comment by hanchen666** [comment]
I downloaded dirsearch-0.4.1-alpha, but the problem still exists
<img width="1011" alt="图片" src="https://user-images.githubusercontent.com/35289748/116036480-5ae38780-a699-11eb-86eb-57cf52391239.png">

**Comment by maurosoria** [comment]
Download the last version from git:

https://github.com/maurosoria/dirsearch/archive/refs/heads/master.zip

**Comment by hanchen666** [comment]
Thank you. My problem is solved
