### ISSUE TITLE
HTTPS Scan SSL Warning

### ISSUE THREAD

**Issue by DeC1pher** [maurosoria/dirsearch#814]
### What is the current behavior?

While Scanning a https-Site I get following Error

```
[04:17:18] Starting: 
/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host ''. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host ''. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host ''. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```

### What is the expected behavior?

Running without errors.

Cheers

**Comment by shelld3v** [comment]
Hi, have you installed dirsearch with the latest commit?

**Comment by DeC1pher** [comment]
Hello @shelld3v ,

yes, just cloned to another vm today.
`git pull` shows me up2date.

**Comment by shelld3v** [comment]
Hi, thanks! I got it, do u mind give me a target for testing? So I can confirm the fix

**Comment by DeC1pher** [comment]
Hello @shelld3v,

sounds great, unfortunately I have no special https target but you can see the issue on every request it doesn't matter which site.

**Comment by Horridge** [comment]
Came to report the same issue using latest release, but it looks like you're already on it. Agree with the above that any target has the same result;
/home/USER/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.facebook.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings`

**Comment by soapffz** [comment]
Same situation as using the latest version
`python dirsearch.py -t 50 -u https://xxxx --random-agent -e * -f -x 400,404,500,503,514,564`

`C:\Miniconda\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ip.ip.ip.ip'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings`

**Comment by gprime31** [comment]
easy fix:
https://devnote.in/insecurerequestwarning-unverified-https-request/
add to dirsearch.py:

from urllib3.exceptions import InsecureRequestWarning #added
import requests
import urllib3

requests.packages.urllib3.disable_warnings(category=InsecureRequestWarning) #added

save and enjoy no errors!!!!!

**Comment by git-oaktree** [comment]
The above works. Submitted a Pull Request using gprim31's comments above. If you want to copy and paste the code, here is the code: 

Begin under the author's name ( Mauro Soria) and end before the  Program Class declaration.

**Comment by gprime31** [comment]
![2021-04-26_15-57](https://user-images.githubusercontent.com/44535257/116142610-1b706780-a6a8-11eb-8af1-c5861881bdde.png)

**Comment by gprime31** [comment]
just copy this ^^^^
