### ISSUE TITLE
Some URLs of HTTPS report errors

### ISSUE THREAD

**Issue by hanchen666** [maurosoria/dirsearch#817]
<img width="1045" alt="图片" src="https://user-images.githubusercontent.com/35289748/116355051-dffea600-a82b-11eb-909c-618a8ac2b4a1.png">

**Comment by shelld3v** [comment]
Hi, this has been fixed in the latest commit!

**Comment by hanchen666** [comment]
Problem solved, thank you

**Comment by shelld3v** [comment]
Close this?

**Comment by hanchen666** [comment]
yes

**Comment by shelld3v** [comment]
lol there is a **Close** button

**Comment by shelld3v** [comment]
Close?
