### ISSUE TITLE
win bug

### ISSUE THREAD

**Issue by M4ng0sec** [maurosoria/dirsearch#820]
![image](https://user-images.githubusercontent.com/34777745/116880478-a7f4ca00-ac54-11eb-83cf-076bce00ab6d.png)

os：win server 2012 r2
python：3.8.1

**Comment by shelld3v** [comment]
Hi, can you try re-installing dirsearch (https://github.com/maurosoria/dirsearch/archive/master.zip)? Seems like an old bug

**Comment by M4ng0sec** [comment]
Reinstalled many times.

C:\dirsearchwin>python dirsearch.py --version
dirsearch v0.4.1

Whether it is git cloe or download, it is invalid.

Windows server 2012 r2 is not supported?

**Comment by shelld3v** [comment]
Hi, can I know the target for testing? (Feel free to refuse)

**Comment by M4ng0sec** [comment]
aHR0cHM6Ly9wLnNwYW0uc2hvdWppLnFoLWxiLmNvbS8=

**Comment by shelld3v** [comment]
It works as expected

```
$ python3 dirsearch.py -u aHR0cHM6Ly9wLnNwYW0uc2hvdWppLnFoLWxiLmNvbS8= -e "*"

  _|. _ _  _  _  _ _|_    v0.4.1
 (_||| _) (/_(_|| (_| )

Extensions: php, jsp, jsf, asp, aspx, do, action, cgi, pl, html, htm, js, json, json, tar.gz, tgz
HTTP method: GET | Threads: 30 | Wordlist size: 15897

Error Log: /home/minh/dirsearch/logs/errors-21-05-03_21-45-54.log

Target: aHR0cHM6Ly9wLnNwYW0uc2hvdWppLnFoLWxiLmNvbS8=

Output File: /home/minh/dirsearch/reports/aHR0cHM6Ly9wLnNwYW0uc2hvdWppLnFoLWxiLmNvbS8=/_21-05-03_21-45-55.txt

[21:45:55] Starting: 
CTRL+C detected: Pausing threads, please wait...
[e]xit / [c]ontinue: e

Canceled by the user
```

**Comment by M4ng0sec** [comment]
The strange thing is that for the same test target, another windwos 2012 R2 has no BUG

**Comment by M4ng0sec** [comment]
The test target needs to be decrypted and run on Windows 2012.

**Comment by shelld3v** [comment]
> The strange thing is that for the same test target, another windwos 2012 R2 has no BUG

From my view, this is not a bug with OS, but with the code. Are you sure you just re-installed dirsearch with the latest commit? If yes, can you please copy the content of `dirsearch/lib/core/scanner.py` and paste it here? (use ``` to quote it)

**Comment by shelld3v** [comment]
> The test target needs to be decrypted and run on Windows 2012.

I know ;)

**Comment by M4ng0sec** [comment]
`# -*- coding: utf-8 -*-
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#  Author: Mauro Soria

import re

from urllib.parse import unquote
from lib.utils import RandomUtils
from thirdparty.sqlmap import DynamicContentParser


class ScannerException(Exception):
    pass


class Scanner(object):
    def __init__(self, requester, calibration=None, suffix=None, prefix=None):
        self.calibration = calibration
        self.suffix = suffix if suffix else ""
        self.prefix = prefix if prefix else ""
        self.requester = requester
        self.tester = None
        self.redirectRegExp = None
        self.invalidStatus = None
        self.dynamicParser = None
        self.sign = None
        self.ratio = 0.98
        self.setup()

    def setup(self):
        firstPath = self.prefix + (
            self.calibration if self.calibration else RandomUtils.randString()
        ) + self.suffix
        firstResponse = self.requester.request(firstPath)
        self.invalidStatus = firstResponse.status

        if self.invalidStatus == 404:
            # Using the response status code is enough :-}
            return

        secondPath = self.prefix + (
            self.calibration if self.calibration else RandomUtils.randString(omit=firstPath)
        ) + self.suffix
        secondResponse = self.requester.request(secondPath)

        # Look for redirects
        if firstResponse.redirect and secondResponse.redirect:
            self.redirectRegExp = self.generateRedirectRegExp(
                firstResponse.redirect, firstPath,
                secondResponse.redirect, secondPath,
            )

        # Analyze response bodies
        if firstResponse.body is not None and secondResponse.body is not None:
            self.dynamicParser = DynamicContentParser(
                self.requester, firstPath, firstResponse.body, secondResponse.body
            )
        else:
            self.dynamicParser = None

        baseRatio = float(
            "{0:.2f}".format(self.dynamicParser.comparisonRatio)
        )  # Rounding to 2 decimals

        # If response length is small, adjust ratio
        if len(firstResponse) < 2000:
            baseRatio -= 0.1

        if baseRatio < self.ratio:
            self.ratio = baseRatio

    def generateRedirectRegExp(self, firstLoc, firstPath, secondLoc, secondPath):
        # Use a unique sign to locate where the path gets reflected in the redirect
        self.sign = RandomUtils.randString(n=20)
        firstLoc = firstLoc.replace(firstPath, self.sign)
        secondLoc = secondLoc.replace(secondPath, self.sign)
        regExpStart = "^"
        regExpEnd = "$"

        for f, s in zip(firstLoc, secondLoc):
            if f == s:
                regExpStart += re.escape(f)
            else:
                regExpStart += ".*"
                break

        if regExpStart.endswith(".*"):
            for f, s in zip(firstLoc[::-1], secondLoc[::-1]):
                if f == s:
                    regExpEnd = re.escape(f) + regExpEnd
                else:
                    break

        return unquote(regExpStart + regExpEnd)

    def scan(self, path, response):
        if self.invalidStatus == response.status == 404:
            return False

        if self.invalidStatus != response.status:
            return True

        if self.redirectRegExp and response.redirect:
            path = re.escape(unquote(path))
            # A lot of times, '#' or '?' will be removed in the redirect, cause false positives
            for char in ["\\#", "\\?"]:
                if char in path:
                    path = path.replace(char, "(|" + char) + ")"

            redirectRegExp = self.redirectRegExp.replace(self.sign, path)

            # Redirect sometimes encodes/decodes characters in URL, which may confuse the
            # rule check and make noise in the output, so we need to unquote() everything
            redirectToInvalid = re.match(redirectRegExp, unquote(response.redirect))

            # If redirection doesn't match the rule, mark as found
            if redirectToInvalid is None:
                return True

        ratio = self.dynamicParser.compareTo(response.body)

        if ratio >= self.ratio:
            return False

        elif "redirectToInvalid" in locals() and ratio >= (self.ratio - 0.15):
            return False

        return True
`

**Comment by M4ng0sec** [comment]
```# -*- coding: utf-8 -*-
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#  Author: Mauro Soria

import re

from urllib.parse import unquote
from lib.utils import RandomUtils
from thirdparty.sqlmap import DynamicContentParser


class ScannerException(Exception):
    pass


class Scanner(object):
    def __init__(self, requester, calibration=None, suffix=None, prefix=None):
        self.calibration = calibration
        self.suffix = suffix if suffix else ""
        self.prefix = prefix if prefix else ""
        self.requester = requester
        self.tester = None
        self.redirectRegExp = None
        self.invalidStatus = None
        self.dynamicParser = None
        self.sign = None
        self.ratio = 0.98
        self.setup()

    def setup(self):
        firstPath = self.prefix + (
            self.calibration if self.calibration else RandomUtils.randString()
        ) + self.suffix
        firstResponse = self.requester.request(firstPath)
        self.invalidStatus = firstResponse.status

        if self.invalidStatus == 404:
            # Using the response status code is enough :-}
            return

        secondPath = self.prefix + (
            self.calibration if self.calibration else RandomUtils.randString(omit=firstPath)
        ) + self.suffix
        secondResponse = self.requester.request(secondPath)

        # Look for redirects
        if firstResponse.redirect and secondResponse.redirect:
            self.redirectRegExp = self.generateRedirectRegExp(
                firstResponse.redirect, firstPath,
                secondResponse.redirect, secondPath,
            )

        # Analyze response bodies
        if firstResponse.body is not None and secondResponse.body is not None:
            self.dynamicParser = DynamicContentParser(
                self.requester, firstPath, firstResponse.body, secondResponse.body
            )
        else:
            self.dynamicParser = None

        baseRatio = float(
            "{0:.2f}".format(self.dynamicParser.comparisonRatio)
        )  # Rounding to 2 decimals

        # If response length is small, adjust ratio
        if len(firstResponse) < 2000:
            baseRatio -= 0.1

        if baseRatio < self.ratio:
            self.ratio = baseRatio

    def generateRedirectRegExp(self, firstLoc, firstPath, secondLoc, secondPath):
        # Use a unique sign to locate where the path gets reflected in the redirect
        self.sign = RandomUtils.randString(n=20)
        firstLoc = firstLoc.replace(firstPath, self.sign)
        secondLoc = secondLoc.replace(secondPath, self.sign)
        regExpStart = "^"
        regExpEnd = "$"

        for f, s in zip(firstLoc, secondLoc):
            if f == s:
                regExpStart += re.escape(f)
            else:
                regExpStart += ".*"
                break

        if regExpStart.endswith(".*"):
            for f, s in zip(firstLoc[::-1], secondLoc[::-1]):
                if f == s:
                    regExpEnd = re.escape(f) + regExpEnd
                else:
                    break

        return unquote(regExpStart + regExpEnd)

    def scan(self, path, response):
        if self.invalidStatus == response.status == 404:
            return False

        if self.invalidStatus != response.status:
            return True

        if self.redirectRegExp and response.redirect:
            path = re.escape(unquote(path))
            # A lot of times, '#' or '?' will be removed in the redirect, cause false positives
            for char in ["\\#", "\\?"]:
                if char in path:
                    path = path.replace(char, "(|" + char) + ")"

            redirectRegExp = self.redirectRegExp.replace(self.sign, path)

            # Redirect sometimes encodes/decodes characters in URL, which may confuse the
            # rule check and make noise in the output, so we need to unquote() everything
            redirectToInvalid = re.match(redirectRegExp, unquote(response.redirect))

            # If redirection doesn't match the rule, mark as found
            if redirectToInvalid is None:
                return True

        ratio = self.dynamicParser.compareTo(response.body)

        if ratio >= self.ratio:
            return False

        elif "redirectToInvalid" in locals() and ratio >= (self.ratio - 0.15):
            return False

        return True
```

**Comment by M4ng0sec** [comment]
The same bug appeared on another host.

aHR0cHM6Ly8yMTguNjUuMjM2LjIwMzo5MDgx

**Comment by M4ng0sec** [comment]
The same bug appeared on another host.

aHR0cHM6Ly8yMTguNjUuMjM2LjIwMzo5MDgx

**Comment by shelld3v** [comment]
Hi, can you check if your internet connection is working?

**Comment by shelld3v** [comment]
> Hi, can you check if your internet connection is working?

Oh I'm sorry, if you didn't have an internet connection, you couldn't post any comment. 

I will work on this tomorrow! Sorry but I can't work right now

**Comment by M4ng0sec** [comment]
Network connection is normal.

**Comment by M4ng0sec** [comment]
I guess it is related to ssl encryption?

**Comment by M4ng0sec** [comment]
It should be an ssl problem, can you give a function similar to wget(--no-check-certificate)?

**Comment by shelld3v** [comment]
Hi, dirsearch doesn't check the certificate at all, it ignores that silly cert.

**Comment by M4ng0sec** [comment]
Well, this error should be caused by some fixes in Windows 2012, which may change some TLS/SSL configurations. It seems that the only solution to the problem is to change the OS.

**Comment by shelld3v** [comment]
> Well, this error should be caused by some fixes in Windows 2012, which may change some TLS/SSL configurations. It seems that the only solution to the problem is to change the OS.

I think so! Can you run dirsearch on other OS? If yes, then sorry, I think I don't I have time to look at this (I did some searchs but couldn't find anything), let just say **Windows 2012** is not in supported OS versions of dirsearch. If you really want to fix this, tell me, I will try my best!
