### ISSUE TITLE
Monitor the frequency of appearance of paths

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#832]
### What is the feature?

Monitor the frequency of appearance of paths for further actions with that metrics

### What is the use case?

Make a good dictionary based on the stat, ...

#### Checker:

- [x] This feature is in scope for the dirsearch purpose

**Comment by nairanu9888** [comment]
Hey !! Can you describe more about this feature?

**Comment by shelld3v** [comment]
Hi @nairanu9888, this is an advanced feature, I want dirsearch to save information of all scans and create a summary report for it, like how many paths have dirsearch found in all scans, how many times each path was found, on which root domain, what extensions were found on this root domain (`*.example.com`), ... Such things can be used for analysis and reference. I think this feature is kinda too complex so we shouldn't work on this yet

**Comment by shelld3v** [comment]
Also @nairanu9888, can you join our slack: https://join.slack.com/t/dirsearch/shared_invite/zt-10fpu2k7k-IHbB8PN9G23pcwpoE4mapg

**Comment by nairanu9888** [comment]
Okay thankyou @shelld3v
