### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by Ppsoft1991** [maurosoria/dirsearch#838]
I installed requirements.txt and run python3 dirsearch.py

Traceback (most recent call last):
  File "dirsearch.py", line 27, in <module>
    from lib.core import ArgumentParser
  File "/root/dirsearch/lib/core/__init__.py", line 3, in <module>
    from .fuzzer import *  # noqa: F401
  File "/root/dirsearch/lib/core/fuzzer.py", line 22, in <module>
    from lib.connection.request_exception import RequestException
  File "/root/dirsearch/lib/connection/__init__.py", line 2, in <module>
    from .requester import *  # noqa: F401
  File "/root/dirsearch/lib/connection/requester.py", line 28, in <module>
    from thirdparty.requests_ntlm import HttpNtlmAuth
  File "/root/dirsearch/thirdparty/requests_ntlm/__init__.py", line 1, in <module>
    from .requests_ntlm import HttpNtlmAuth
  File "/root/dirsearch/thirdparty/requests_ntlm/requests_ntlm.py", line 11, in <module>
    from thirdparty.ntlm_auth import ntlm
  File "/root/dirsearch/thirdparty/ntlm_auth/__init__.py", line 4, in <module>
    from . import ntlm, session_security
  File "/root/dirsearch/thirdparty/ntlm_auth/ntlm.py", line 9, in <module>
    from thirdparty.ntlm_auth.messages import AuthenticateMessage, ChallengeMessage, \
  File "/root/dirsearch/thirdparty/ntlm_auth/messages.py", line 9, in <module>
    from thirdparty.ntlm_auth.compute_response import ComputeResponse
  File "/root/dirsearch/thirdparty/ntlm_auth/compute_response.py", line 12, in <module>
    import thirdparty.ntlm_auth.compute_hash as comphash
AttributeError: module 'thirdparty' has no attribute 'ntlm_auth'

![image](https://user-images.githubusercontent.com/18442117/118397074-e6db4480-b684-11eb-8952-379db39859fe.png)

system version: ubuntu-server-18.04
python verison: python3.6

**Comment by u21h2** [comment]
I have met the same bug.

**Comment by shelld3v** [comment]
Hi, I can't reproduce this:

```
$ python3 dirsearch.py
URL target is missing, try using -u <url>
```

**Comment by shelld3v** [comment]
Can you edit the file `thirdparty/ntlm_auth/compute_response.py` and change from:

```python
import thirdparty.ntlm_auth.compute_hash as comphash
import thirdparty.ntlm_auth.compute_keys as compkeys
import thirdparty.ntlm_auth.messages
```
To:

```python
from thirdparty.ntlm_auth import compute_hash as comphash
from thirdparty.ntlm_auth import compute_keys as compkeys
from thirdparty.ntlm_auth import messages
```

And see if it works?

**Comment by shelld3v** [comment]
Btw, try python 3.9, I don't know if python version is the root cause, but let give it a try

**Comment by Ppsoft1991** [comment]
In my laptop, I use ubuntu 1804,python 3.8,no such problem

**Comment by Ppsoft1991** [comment]
Thanks,It's a awsome project, When I use python3.8,it running.
![image](https://user-images.githubusercontent.com/18442117/118403932-6710a280-b6a3-11eb-9285-5a8b87755bdd.png)

**Comment by shelld3v** [comment]
Cool, I will need to update the README

**Comment by shelld3v** [comment]
Does python 3.7 work?

**Comment by Ppsoft1991** [comment]
no,I used python3.8

**Comment by shelld3v** [comment]
Can you try with python3.7? I want to know the lowest requirement of python version for dirsearch

**Comment by d3mondev** [comment]
FYI I've experienced the same issue. It works with Python 3.7, but it doesn't work with Python 3.6.

Ubuntu 18.04 LTS ships with Python 3.6 by default and since a few days ago Python needs to be upgraded to run dirsearch on that platform.

Reproducible in docker:

```bash
sudo docker run -it --rm ubuntu:18.04 /bin/bash

apt update && apt install -y git python3 python3-pip
python3 -m pip install --upgrade pip setuptools

git clone https://github.com/maurosoria/dirsearch.git
pip3 install -r dirsearch/requirements.txt
python3 dirsearch/dirsearch.py
```

Thought you'd want to know!

**Comment by shelld3v** [comment]
Thanks @d3mondev, that's what I wanted to know
