### ISSUE TITLE
Please add as reference 

### ISSUE THREAD

**Issue by Ignitetch** [maurosoria/dirsearch#855]
Please add this one also as reference on your reop : 
https://secnhack.in/multiple-ways-to-find-hidden-directory-on-web-server/

**Comment by shelld3v** [comment]
Hi, can you submit a pull request?

**Comment by Ignitetch** [comment]
Sure !
I have done it.

**Comment by shelld3v** [comment]
I haven't seen it yet: https://github.com/maurosoria/dirsearch/pulls

**Comment by Ignitetch** [comment]
Could you check it once 👍🏻

**Comment by Ignitetch** [comment]
Did you got it ?
