### ISSUE TITLE
AttributeError: module 'thirdparty' has no attribute 'ntlm_auth'

### ISSUE THREAD

**Issue by il0v3y0uu** [maurosoria/dirsearch#858]
I have installed the requirements and have followed the installation instructions, but I have a problem. Can you help me ?
![image](https://user-images.githubusercontent.com/45809257/119495987-36102c00-bd8d-11eb-9ee3-e1291861bc77.png)

**Comment by xufengnian** [comment]
I have same question and I have solved it,because the python3 version is old
my python3 version is 3.6.3,I try to download python3 3.8.6 and pip 20.1 then install it,there is no error

**Comment by shelld3v** [comment]
The answer from @xufengnian is the same as mine, please update your python version

**Comment by il0v3y0uu** [comment]
![image](https://user-images.githubusercontent.com/45809257/119646748-b4ca9f00-be49-11eb-950d-a7e994f9bb3f.png)
I've upgraded my python, but it's still an error.

**Comment by shelld3v** [comment]
Hi @il0v3y0uu, this is another issue.

Issue link: https://github.com/pyca/cryptography/issues/4403
Solution: `pip3 install -U cffi`
