### ISSUE TITLE
AUTH Basic authentication

### ISSUE THREAD

**Issue by abokareem** [maurosoria/dirsearch#86]
How to Enter User Name and Password in Password
AUTH Basic authentication
**dirsearch** / thirdparty / requests / **auth.py**
The script is in the folders
But there is none
Run command

**Comment by maurosoria** [comment]
There is no argument for that yet. But you can use --header "WWW-Authenticate: Basic " with the user and password base64 encoded.

**Comment by shelld3v** [comment]
I will try to make this!

**Comment by shelld3v** [comment]
Hi, I found that you can do basic HTTP auth just by adding the credentials before the host, like this: 
`-u https://admin:password@example.com`.

It's solved now!

**Comment by Zeecka** [comment]
-u option with `user:passwd@domain` doesn't work for me, I got `Invalid port number: <passwd>@<domain>`. 
Test case: `dirsearch -u "http://user:passwd@httpbin.org/basic-auth/user/passwd"`

I think that WWW-Authenticate should be sufficient.

What about Digest Auth / NTLM Auth ? (thirdparty requests package seems to support such authentication).

**Comment by shelld3v** [comment]
@Zeecka You say right! My bad, need to check again and add this option!

**Comment by barrett092** [comment]
Would love to see this feature.

**Comment by shelld3v** [comment]
> Would love to see this feature.

The maintainer of the project is busy now, so my PR can't be merged. It will take a couple of days, please be patient

**Comment by Teicu** [comment]
Hi, and finally, what is the correct command to run a test on a site that is protected by basic auth? thank you
