### ISSUE TITLE
Bug with --remove-extensions

### ISSUE THREAD

**Issue by shelld3v** [maurosoria/dirsearch#874]
### What is the current behavior?

Recently, I discovered an issue with the `--remove-extensions` flag: using `--remove-extensions`, whenever a path is found as valid, a thread will be broken for no reason.

Reproduce:
- `./dirsearch.py -u example.com -t 1 --remove-extensions`
- `./dirsearch.py -u example.com -t 2 --remove-extensions`

**Comment by maurosoria** [comment]
Hello @shelld3v , this still as a bug?

**Comment by shelld3v** [comment]
I believe so

**Comment by Yash07700** [comment]
STILL IT IS A BUG
