### ISSUE TITLE
Bug -o options

### ISSUE THREAD

**Issue by ltfafei** [maurosoria/dirsearch#879]
python dirsearch.py -u http://url/ -o res.html

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
                                                                   self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
...

**Comment by shelld3v** [comment]
Hi, can you post the FULL traceback?

**Comment by shelld3v** [comment]
Hi @ltfafei, can you please post the full error message (嗨，你能把完整的错误信息贴出来吗)

**Comment by shelld3v** [comment]
Btw, `python3 dirsearch.py -u http://url/ -o res.html --format html`

**Comment by ltfafei** [comment]
Oh, add --format html no problem. Thanks.

> Hi, can you post the FULL traceback?

**Comment by ltfafei** [comment]
> Oh, add --format html no problem. Thanks.
> 
> > Hi, can you post the FULL traceback?

Oh, add --format html no problem. Thanks.

**Comment by shelld3v** [comment]
@ltfafei I still need the traceback, please!
