### ISSUE TITLE
PEP8 compliance

### ISSUE THREAD

**Issue by amalmurali47** [maurosoria/dirsearch#88]
The project is growing so fast. It would make sense to introduce PEP8 guidelines as a coding standard for the project so that everything is uniform.

What are your thoughts on this?

**Comment by maurosoria** [comment]
Hi amalmurali47,

I think you are right. I haven't done yet but maybe with some help it would be faster.

**Comment by amalmurali47** [comment]
I may have some free time this weekend.

**Comment by maurosoria** [comment]
Great! I'm on vacations until next month. Anything you can do is welcome.
