### ISSUE TITLE
Something prints `dirsearch.Program object` repr in the end.

### ISSUE THREAD

**Issue by qumusabel** [maurosoria/dirsearch#881]
![image](https://user-images.githubusercontent.com/18624304/120833903-c6afee80-c57b-11eb-848c-d425b41b4650.png)
Can't figure out where this message comes from. Latest commit.

**Comment by shelld3v** [comment]
How did you run it? Git, pip, kali package or what?

**Comment by qumusabel** [comment]
git clone, then pip install

**Comment by ikka7895** [comment]
# If you want to edit dirsearch default configurations, you can
# edit values in this file. Everything after `#` is a comment
# and won't be applied

[mandatory]
default-extensions = php,aspx,jsp,html,js
force-extensions = False
# exclude-extensions = old,log

[general]
threads = 30
recursive = False
deep-recursive = False
force-recursive = False
recursion-depth = 0
exclude-subdirs = %%ff/
random-user-agents = False
max-time = 0
full-url = False
quiet-mode = False
color = True
recursion-status = 200-399,401,403
# include-status = 200-299,401
# exclude-status = 400,500-999
# exclude-sizes = 0b,123gb
# exclude-texts = "Not found"
# exclude-regexps = "403 [a-z]{1,25}"
# exclude-content = 404.html
# skip-on-status = 429,999

[reports]
report-format = plain
autosave-report = True
# report-output-folder = /home/user
# logs-location = /tmp
## Supported: plain, simple, json, xml, md, csv, html

[dictionary]
lowercase = False
uppercase = False
capitalization = False
# prefixes = .,admin
# suffixes = ~,.bak
# wordlist = db/dicc.txt

[request]
httpmethod = get
## Lowercase only
follow-redirects = False
# headers-file = headers.txt
# user-agent = MyUserAgent
# cookie = SESSIONID=123

[connection]
timeout = 5
delay = 0
scheme = http
maxrate = 0
retries = 2
request-by-hostname = False
exit-on-error = False
# proxy = localhost:8080
# proxy-list = proxies.txt
# replay-proxy = localhost:8000

**Comment by qumusabel** [comment]
what?

**Comment by ikka78** [comment]
Bhai can u contact me please

**Comment by nairanu9888** [comment]
Hey! I would like to take up this issue and try to resolve this matter.

**Comment by shelld3v** [comment]
> Hey! I would like to take up this issue and try to resolve this matter.

Hello @nairanu9888, thank you a lot for your help, feel free to submit a PR to fix this issue, I will approve and merge it

**Comment by nairanu9888** [comment]
@qumusabel Can I know more about the issue? Does it still persist? How exactly you installed dirsearch? And could you share the command that you ran which caused this error? Such error is caused when we try to print the object of the class Program , which is totally indecipherable.

**Comment by shelld3v** [comment]
@nairanu9888 I was able to reproduce his issue using those commands:
```
git clone https://github.com/maurosoria/dirsearch
cd dirsearch
pip3 install .
```

Then you can easily run `dirsearch -u <target>`

**Comment by nairanu9888** [comment]
Okay! I tried out the same commands, unable to reproduce his issue. What about upgrading to the latest pip version?

**Comment by qumusabel** [comment]
Did a clean install with venv and `pip install --no-cache-dir`, the issue is still there, both in PyPI and in the current commit.
