### ISSUE TITLE
os.environ['http_proxy']

### ISSUE THREAD

**Issue by yhy0** [maurosoria/dirsearch#886]
I now have a program in which a thread is opened to continuously change the value of os.environ['http_proxy'], and now dirsearch cannot pass the proxy through the variable os.environ['http_proxy'] I set

**Comment by shelld3v** [comment]
Do you mean that you were having a dirsearch scan in progress and you changed the `http_proxy` variable but the proxy of the scan didn't change? I don't think I can do anything with this

**Comment by yhy0** [comment]
Yes, then how should I set up the proxy pool ？

**Comment by shelld3v** [comment]
> Yes, then how should I set up the proxy pool ？

`--proxy` flag? Or `proxy` variable inside `default.conf`

**Comment by shelld3v** [comment]
> Yes, then how should I set up the proxy pool ？

If you are scanning, the scan hasn't finished yet, you can't change the proxy. I am working on a feature that allows you to change all your settings of a scan while the scan's still in progress. Will be after the release of 0.4.2 😉

**Comment by yhy0** [comment]
No, no, I use the thread to constantly change the proxy, my proxy is always changing, using --proxy will only have one proxy

**Comment by shelld3v** [comment]
> No, no, I use the thread to constantly change the proxy, my proxy is always changing, using --proxy will only have one proxy

Oh, you can try `--proxy-list`, or `proxy-list` variable in `default.conf`. It will randomize the proxy from a list of proxies

**Comment by shelld3v** [comment]
Done yet?

**Comment by yhy0** [comment]
Because my proxy is obtained through an interface, each proxy will only exist for a few minutes, so I don’t have a proxy list. How should I use it in this case?

**Comment by shelld3v** [comment]
That's really hard, try editing the `http_proxy` var in `.bashrc`, remember to `$ source .bashrc` after changing it

**Comment by yhy0** [comment]
Okay, thanks, I’m seeing if there are other solutions

**Comment by shelld3v** [comment]
I'm not an expert tho, so Idk if there are any. But try making a script, that auto-executes those commands, so you won't have to keep texting manually the commands after each few minutes

**Comment by shelld3v** [comment]
I'm closing this now, but we can keep on the discussion
