### ISSUE TITLE
add more check for writble logs and report dest part

### ISSUE THREAD

**Issue by dmknght** [maurosoria/dirsearch#899]
### What is the feature?

When program starts, it checks for writable `logs` and `reports` folder. At first, it tries location that user passes to arguments, then check writable root dir of project
https://github.com/maurosoria/dirsearch/blob/master/lib/controller/controller.py#L105
I'd suggest add `elif` lines like this
```
 elif self.validate_path(self.script_path + "/logs"):
```
and 
```
 elif self.validate_path(self.script_path + "reports"):
```
### What is the use case?

I'm doing packaging `dirsearch` for Parrot OS and i noticed user needs write permission for `$(DestDir)/logs/` and `$DestDir/reports/` to write logs and reports. But with current logic, the whole `$(DestDir)/` must be writable or program exits. Meanwhile i created writable `logs` and `reports` directories and user doesn't need to be run the program as root. This also means
1. User doesn't need to run the tool as root or use sudo, no password is needed
2. No pycache files will be generated
3. Program runs fine when `$(DestDir)` is not writable

So i really hope devs can add a patch to add this idea. I tested on my system and everything works fine with writable `logs` and `reports` but not whole `dirsearch` (I commented `exit` at `validate_path`)

**Comment by shelld3v** [comment]
Thanks, I will do it soon. Btw, why don't you edit `default.conf` to specify logs and reports location?

**Comment by dmknght** [comment]
> Btw, why don't you edit default.conf to specify logs and reports location?

Well i don't know how to give the good answer for this. It is all about Debian's standard and i have to follow it. And the solution for the "Standards" is using directories at global paths instead of `$HOME`

**Comment by shelld3v** [comment]
@dmknght I just realized something: the reason I check for `script_path` instead of the full path is that if you install dirsearch with pip `git clone https://github.com/maurosoria/dirsearch && cd dirsearch && pip3 install .`, `/logs` and `/reports` folders won't be created inside the PyPi package folder (`.local/lib/python3.9/site-packages`) where the dirsearch script is saved and run (why? https://github.com/maurosoria/dirsearch/issues/736#issuecomment-838595121). So I will soon find a flexible solution (actually had it) and fix all these messes

**Comment by dmknght** [comment]
> /logs and /reports folders won't be created inside the PyPi package folder (.local/lib/python3.9/site-packages)

I know because those are empty folders :D . Luckily i handled it by with Debian packaging :D Cheers!

> So I will soon find a flexible solution (actually had it) and fix all these messes

Maybe add empty `__init__.py` could be solution? I think it does. Meanwhile i think add an other `elif` is a good solution for both cases 1. missing `logs` and `reports`) and 2. 2 folders were created with writable permission

**Comment by shelld3v** [comment]
> Maybe add empty __init__.py could be solution? I think it does. Meanwhile i think add an other elif is a good solution for both cases 1. missing logs and reports) and 2. 2 folders were created with writable permission

If you wish to know, we SHOULDN'T add those folders to the `site-packages` because any file/folder inside `site-packages` is recognized as a PyPi package (`import package`), which is unintended. My solution is that we will create another config file that will only be applied for people who install dirsearch with pip, and in that config we will specify locations for logs and reports

**Comment by dmknght** [comment]
> If you wish to know, we SHOULDN'T add those folders to the site-packages because any file/folder inside site-packages is recognized as a PyPi package (import package)

Oh good to know. I mean i am not very familiar with `PyPi` standard.

> My solution is that we will create another config file that will only be applied for people who install dirsearch with pip, and in that config we will specify locations for logs and reports

I mean when the project is installed, and maybe the `logs` and `reports` were created. And then the permission is not writable for some reasons -> it is worth to check the full path again. So in this case we'll have logic like this
1. Check arguments and config file
2. Check if `logs` and `reports` is created and writable
3. No `logs` and `reports`, we check if `dirsearch` is writable so we create 2 folders.

**Comment by shelld3v** [comment]
>I mean when the project is installed, and maybe the logs and reports were created. And then the permission is not writable for some reasons -> it is worth to check the full path again. So in this case we'll have logic like this

Hmmmm, probably keep them in `site-packages`, but saved inside another folder like `.dirsearch`
