### ISSUE TITLE
Threads limits in dirsearch v0.4.2

### ISSUE THREAD

**Issue by my123px** [maurosoria/dirsearch#910]
In dirsearch v0.4.2, when I set the -t option, if I set a value greater than 30, dirsearch will only execute in 30 threads when it is executed. Does this version set a limit on the maximum number of threads? I did not find the relevant maximum value description in the -h description, this parameter can be used normally in the previous version.

![image](https://user-images.githubusercontent.com/33975676/124214190-6c775e80-db24-11eb-9d26-ec62c63fd071.png)
![image](https://user-images.githubusercontent.com/33975676/124214319-9892df80-db24-11eb-8b21-6ca5e236ce12.png)
![image](https://user-images.githubusercontent.com/33975676/124214353-a5afce80-db24-11eb-911c-05a058029587.png)

**Comment by shelld3v** [comment]
Hi @my123px, I can easily see there is a `-X` flag before it, and the `-X` switch is for excluding extensions. dirsearch actually thought `-t` is the value for the `-X` flag. So the solution is: 
```
dirsearch.py -u xxx.xxx.xxx.xxx -t 100 -w directory-list-2.3-medium.txt
```

**Comment by my123px** [comment]
> Hi @my123px, I can easily see there is a `-X` flag before it, and the `-X` switch is for excluding extensions. dirsearch actually thought `-t` is the value for the `-X` flag. So the solution is:
> 
> ```
> dirsearch.py -u xxx.xxx.xxx.xxx -t 100 -w directory-list-2.3-medium.txt
> ```


The problem is solved, thank you very much~
