### ISSUE TITLE
/usr/share/dirsearch is owned by root

### ISSUE THREAD

**Issue by Hritik14** [maurosoria/dirsearch#92]
So a non root user trying to run gets a permission denied due to no write access to log folder and reports dir. 
Either the folder should be writable by others (the log and reports) or those files should be created somewhere in $HOME

**Comment by maurosoria** [comment]
decomment the 'save-logs-home' in default.conf for dirsearch to save logs and reports in your home folder.

**Comment by noraj** [comment]
@Hritik14 Is there an option (config) or arg to get logs in the working directory rather than the install dir or in home ?
