### ISSUE TITLE
dirsearch don't find extensions

### ISSUE THREAD

**Issue by No0ob1e** [maurosoria/dirsearch#930]
Passing "`[Tryhackme CC: Pen Testing](https://tryhackme.com/room/ccpentesting)`" room "final exam" I noticed that "dirsearch" can't find a "secret.txt" file compared to "gobuster"
I tried with "-e" flag, also add "txt" to config file but still no results.
Tried standard dictionary, also tried the same dictionary for "gobuster" and "dirsearch" but with "dirsearch" still no results

![Screenshot 2021-07-24 115540](https://user-images.githubusercontent.com/62214984/126863281-e1616f78-45e4-479a-8c24-223fde4cd679.png)

**Comment by shelld3v** [comment]
Hi @No0ob1e, you didn't use the same wordlist for both scans, what did you expect? Try running dirsearch again with this command and see the result: 
```
dirsearch.py -u http://target -w /usr/share/wordlists/dirb/common.txt -r
```

**Comment by No0ob1e** [comment]
Hi @shelld3v, as I mentioned earlier I also tried using the same wordlist for both of them, and the detection is even worse,

![Screenshot 2021-07-25 121706](https://user-images.githubusercontent.com/62214984/126894244-8ac83148-a593-4a2d-9ffa-8d7a10eb46c6.png)

**Comment by shelld3v** [comment]
Hi @No0ob1e, please read the documentation carefully before using dirsearch: https://github.com/maurosoria/dirsearch#wordlists-important

The wordlist you used contains `secret`, so to find `secret.txt`, you need the extension `txt`. As the document part I linked above (please read it), you need the flag `-f`
