### ISSUE TITLE
Sorry, dirsearch requires Python 3.7 or higher

### ISSUE THREAD

**Issue by xNu7** [maurosoria/dirsearch#936]
I have a problem running dirsearch, python3 dirsearch.py ​​-u {url} -e {ext}, here the message Sorry, dirsearch requires Python 3.7 or higher appears. then i installed python3.7, this problem persists.

please help me,.

**Comment by shelld3v** [comment]
I can't reproduce the issue or see any problem in the code here, can you re-check with `python3 --version`?

Thanks!

**Comment by xNu7** [comment]
Version python 3.6.9, how to replace this ?

**Comment by shelld3v** [comment]
You can search for resources from the Internet. Here is one I found: https://dev.to/serhatteker/how-to-upgrade-to-python-3-7-on-ubuntu-18-04-18-10-5hab

Closing this now
