### ISSUE TITLE
macos issue

### ISSUE THREAD

**Issue by meichengg** [maurosoria/dirsearch#939]
Hi, i just updated to this commit: 97fa0a0 and i got this issue as below. Please have a check.

![image](https://user-images.githubusercontent.com/25204246/127480937-60b523a4-7b22-4983-8c3e-26ec092431c4.png)

**Comment by shelld3v** [comment]
Hi, sorry for the issue, it will be fixed soon. A temporary way to fix this is:

```
git clone https://github.com/maurosoria/dirsearch.git -b shelld3v-patch-2
```

**Comment by shelld3v** [comment]
Btw, I can see that you selected a really weird extension, can you recheck your command?

**Comment by meichengg** [comment]
> Btw, I can see that you selected a really weird extension, can you recheck your command?

That doesn't affect the workflow, i used those for long time and all went smooth.

**Comment by shelld3v** [comment]
>That doesn't affect the workflow, i used those for long time and all went smooth.

It would affect the result if you used a dirsearch-style wordlist (`%EXT%` keyword) or did extension-forcing (`-f` flag). Doc here: https://github.com/maurosoria/dirsearch#wordlists-important

**Comment by meichengg** [comment]
> Hi, sorry for the issue, it will be fixed soon. A temporary way to fix this is:
> 
> ```
> git clone https://github.com/maurosoria/dirsearch.git -b shelld3v-patch-2
> ```

May i know why don't you merge it to master branch?

**Comment by shelld3v** [comment]
>May i know why you didn't merge it to master branch?

It's because I don't have permission to do that. @maurosoria is the only person who can push commits to the master branch, even though I still can bypass it by merging pull requests targeting the branch `master`, but only after submitting a review to that PR, and Github doesn't allow you to review your own PR so I can't merge PRs created by myself ;(

**Comment by shelld3v** [comment]
Note that review not by a project member can't help me to have permission to merge the PR too (project members are me and mauro), if you want to help me out, feel free to submit a PR for my branch and I will merge it :)
