### ISSUE TITLE
Switch default behavior of the search (by hostname instead of IP)

### ISSUE THREAD

**Issue by Themercee** [maurosoria/dirsearch#94]
Dirsearch has an option that will force the use of hostname and by default it search by IP. I think it should be the opposite. It should search by hostname by default and an option could be used to search by IP.

This behavior is not expected by user that briefly read the help and this may result in not finding files or directories on server using vhost.

**Comment by Lucifer733** [comment]
Please switch of your phone and wait few mints and I I fixed your problems

**Comment by shelld3v** [comment]
> Dirsearch has an option that will force the use of hostname and by default it search by IP. I think it should be the opposite. It should search by hostname by default and an option could be used to search by IP.
> 
> This behavior is not expected by user that briefly read the help and this may result in not finding files or directories on server using vhost.

You can edit `default.conf`

**Comment by Themercee** [comment]
The default behavior is the problem I think. Some new user may be unaware of this and they may get missing results or thinking the tools does not works properly. Also, If I used `-u http://www.example.com`, I expect it to be run against `www.example.com`, not the IP address.

**Comment by shelld3v** [comment]
>and they may get missing results

I don't think so. Connect to the hostname or directly to the IP address are the same, the only differences are problems with certificate (solved by ignoring it) and the `Host` header (dirsearch solved this problem too). 

Connect to hostname == get IP for the website from the DNS server then connect to it

**Comment by Themercee** [comment]
Ok, when I created the ticket, the host header was not added and we were in fact missing results. If dirsearch add the Host header even if it requests the IP, then this is solved.

**Comment by shelld3v** [comment]
> Ok, when I created the ticket, the host header was not added and we were in fact missing results. If dirsearch now add the Host header even if it requests the IP, then this is solved.

Oh yeah! There used to be a bug with VHost. This bug that has been fixed, but used to be a reason that made a lot of our users left our tool (including top hackers). Sadly I fixed it too late:(
