### ISSUE TITLE
About --force-extensions

### ISSUE THREAD

**Issue by Yami-Kira** [maurosoria/dirsearch#946]
Hey,
Have been using dirsearch for a while, noticed that even when providing extensions somehow as if I didn't (for normal wordlists without %EXT%), then had to use -f(--force-extensions), but then as if there is an extra extensions added , for example if a wordlist is 50 K word ... adding an extension like php   the programm wordlist should be like 100 K (like gobuster)  but no  it becomes 150 K).
As the documentation "For wordlists without %EXT% (like SecLists), -f | --force-extensions switch is required to append extensions to every word in wordlist, as well as the / "
And also as the documentation (for a wordlist of the word  "admin"): 
"Passing "php" and "html" extensions with -f/--force-extensions flag will generate the following dictionary:
admin
admin.php
admin.html
admin/
"
and that happens for every word in the wordlist, for example  having one of the words [admin,login,secret] will result in
200 - /admin/
301 - /admin 
200 - /login/
301 - /login
200 - /secret/
301 - /secret

# Hopes I made it clear, now how to disable that, how to use --force-extensions without "/" added as an extension
# And why even bother, could you please explain why it was there from the very beginning
And definitely thanks for dirsearch

**Comment by shelld3v** [comment]
>Hopes I made it clear, now how to disable that, how to use --force-extensions without "/" added as an extension
>
>And why even bother, could you please explain why it was there from the very beginning

I wish I could change that noisy addition too, but have already asked/requested @maurosoria and received a refusion. Until now, the only way to do it is to use `--suffixes` instead of `-e`. Here is an example:

```
python3 dirsearch.py -u target --suffixes .php,
```

Notice the `,`, without adding that `,`, your result will be:

```
admin.php
```

But not:

```
admin
admin.php
```

Feel free to convince him to change it :)

**Comment by Yami-Kira** [comment]
It became even more wired, tried your solution which looked simple , but didn't work , at least for me
using   --suffixes, and yeah I assure you that I added ","  , tried : ....
--suffixes .php,     &     ,.php     &     .php, ,      &     .php,''     &      .php,' '       & .php,""
And even forms like:
--suffixes=.php,         &  --suffixes=".php,"        &  --suffixes="php,'' "

I do understand the use of ","  saying that also add "nothing" meaning will return the a directory name  so that , well, the search won't include extensions only, but extensions and directories , but somehow  when I specify both an extension and ",' using  --suffixes   I only get extensions searching, as if I did'nt add the ",".

I even did something I never do which is  copying and pasting some code even if I know nothing about, I copied your code 
"python3 dirsearch.py -u target --suffixes .php, "  , replacing  "target" with a target of course, and the same , it only searches for extensions (.php here)

**Comment by shelld3v** [comment]
Hi @Yami-Kira, how did you know if the result wordlist doesn't contain both `endpoint` and `endpoint.ext`?

**Comment by Yami-Kira** [comment]
@shelld3v 
-Worldlist Size
and while it's running you see the actual words it's trying (I know sneaking fast, but no it was all extensions)
I even waited until it finishes but no, it doesn't come back to enumerate directories
AND of course no directories in the output, while there IS (normal scan before trying)

**Comment by shelld3v** [comment]
Hello @Yami-Kira,

It looks like you are using an old version of dirsearch, please update it and so you won't even need the `,`. Btw, after updating it, tell me what do you think about our new progress bar;)

**Comment by Yami-Kira** [comment]
@shelld3v 
Wired !!!!!
I have always been using the latest version(0.4.2), installed via pip (python3 -m pip install dirsearch).
After your last replay saying to use the latest version frankly I said "WTF" I am already using it,  then said let's just use the GitHub version, and I did, and some how it worked , I even saw the new progress bar you talked about.

# You may want to recheck the pypi.org version

**Comment by shelld3v** [comment]
pypi.org creates releases by tag, and since I have already uploaded a release for dirsearch with tag `v0.4.2`, I can't re-upload it now. Now we will wait for `v0.4.3` :)

**Comment by Yami-Kira** [comment]
@shelld3v 
Good luck, and thanks a lot for replaying and solving the problem
And for dirsearch of course
