### ISSUE TITLE
Windows mkdir 如果目标非常规端口 在创建目录时会无法创建 因为带有特殊字符“：”

### ISSUE THREAD

**Issue by jhalx** [maurosoria/dirsearch#949]
![image](https://user-images.githubusercontent.com/70245898/128671920-a3450fc1-1bb4-47dd-b1e9-e03f8b588df1.png)
具体在
dirsearch-0.4.2-beta1\lib\utils\file_utils.py", line 130, in create_directory
os.makedirs(directory)

**Comment by killpi** [comment]
你可以指定输出，-o 或 --outfile

**Comment by jhalx** [comment]
> 你可以指定输出，-o 或 --outfile
这是一个挺不错的临时解决办法，
但是如果在指定大量任务的时候，会不会出现其他问题呢，因为我不同机器上安装的版本应该是不一样的，另一台机器似乎没有这种问题

**Comment by wk0ng** [comment]
/lib/controller/controller.py第327行及335行后面给directory_path变量加一句

directory_path = directory_path.replace(':', '_')

**Comment by shelld3v** [comment]
> /lib/controller/controller.py第327行及335行后面给directory_path变量加一句
> 
> directory_path = directory_path.replace(':', '_')

We have already replaced all invalid characters in the directory path in the latest version of dirsearch, please update it
