### ISSUE TITLE
Cannot read large wordlist from stdin

### ISSUE THREAD

**Issue by DaleMitchell** [maurosoria/dirsearch#95]

**Comment by maurosoria** [comment]
dirsearch doesn't support reading wordlist from stdin, so it doesn't care if it is short or large.

Please explain

**Comment by SuperN1nja** [comment]
Hi, i encountered MemoryError while loading large dictionry file like 24mb
![image](https://github.com/maurosoria/dirsearch/assets/36119780/869f1942-96d2-43b9-9804-ddd146e84a74)
