### ISSUE TITLE
error while using -l option

### ISSUE THREAD

**Issue by ghost** [maurosoria/dirsearch#950]
when i try to pass list of subdomains to the program like this.
dirsearch -l subdomains.txt

its is showing me a message like-
The file with URLs does not exist

**Comment by shelld3v** [comment]
Can you try `dirsearch -l /path/to/subdomains.txt`?

**Comment by bugknr** [comment]
yes i did and got the same result
dirsearch -l Desktop/woilaout/all_subdomains                                                                                                              148 ⨯ 1 ⚙
The file with URLs does not exist

**Comment by shelld3v** [comment]
I mean full path, like `C:\Usr\...`

**Comment by bugknr** [comment]
its working thanks mate
why i did not think about it.
i always use -o option with full path

**Comment by shelld3v** [comment]
The reason is that your dirsearch is run inside the pip packages folder, so it won't open the file inside your current directory. Whenever I have time, I will fix this behavior!

**Comment by ByteBend3r** [comment]
sometimes on kali linux or ubuntu hard to write all path u can do it easily like $(pwd)/subdomain.txt
