### ISSUE TITLE
Different output same version

### ISSUE THREAD

**Issue by Sicks3c** [maurosoria/dirsearch#951]
### What is the question?

I would like to know how the same version can have different output and how to control it 
In fedora VPS I have this output which is better
![Here](https://i.imgur.com/qguRvM9.png)
and for Windows WSL I have this (Using python3.7 for both)
![Here](https://i.imgur.com/Ftv50Xk.png)

**Comment by shelld3v** [comment]
Hi, are you sure both dirsearch commands are absolutely the same including the target URL? You can try reducing the threads number, servers sometimes work differently because of a lag from dirsearch heavy traffic

**Comment by Sicks3c** [comment]
Hello @shelld3v 

Tried with the same `Threads` the output is still different
`Firs box is VPS fedora` 
`Second is WSL`

Regards

**Comment by shelld3v** [comment]
@Sicks3c Try 3 threads only:)

**Comment by Sicks3c** [comment]
It has the same behavior
![Here](https://i.imgur.com/gcECDQI.png)

**Comment by shelld3v** [comment]
I can see both have the same results (from your screenshots)

**Comment by Sicks3c** [comment]
True they have the same results but not the same Decoration
The second one has `[]` and Progress is shown in a bar but the other one doesn't have that

**Comment by shelld3v** [comment]
@Sicks3c Ohh I misunderstood you! Well the progress bar was released recently in the git version, your first terminal is using the version from `pip`, which doesn't have that implementation yet. Try `git clone https://github.com/maurosoria/dirsearch.git`, and if you like the current short command (`dirsearch -u target ...`), you can run `pip3 install .` inside the dirsearch directory

Btw, which is your favorite decoration? :)

**Comment by Sicks3c** [comment]
Oh I see the one with the progress one is the best :)
![This](https://camo.githubusercontent.com/06438cb72c37ab492ba3f9e777665b9cac90460bf0d6acf0af2b863412f6b9d3/68747470733a2f2f692e696d6775722e636f6d2f71677552764d392e706e67)
Yeah now from the git one it works fine <3

Thank you
