### ISSUE TITLE
Brute force numbers

### ISSUE THREAD

**Issue by cgarrovillo** [maurosoria/dirsearch#953]
### What is the question?
Is it possible to brute force numbers?

### Any additional information?

OS, dirsearch version, python version, screenshots, dirsearch command, console output, ...?

#### Checker:
 - [X] I read the documentation (README)

**Comment by shelld3v** [comment]
Hi, it's not possible for dirsearch, there are tools out there that can finish this task for you (turbo intruder, ...). We are also considering this feature because some people have already requested it, but have not decided yet

**Comment by cgarrovillo** [comment]
Thats alright, I just made a simple nodejs that wrote to a file stream in a for loop and used it as a wordlist. Thanks!
