### ISSUE TITLE
It is recommended to add the function of obtaining website title

### ISSUE THREAD

**Issue by anbol** [maurosoria/dirsearch#955]
### What is the feature?

What is it?

### What is the use case?

When and who will use this? Why this matters?

**Comment by shelld3v** [comment]
Hi, thank you for your suggestion, this has been requested by a lot of people for a while, but printing out the title is just really annoying in the output. However, I will do a feature that allows people to write their own scripts and do whatever they want

**Comment by shelld3v** [comment]
Duplicate of #764
