### ISSUE TITLE
Enhancing the coverage of the dictionary

### ISSUE THREAD

**Issue by M1k0er** [maurosoria/dirsearch#965]
Can you generate a dictionary based on url characteristics, such as http://www.google.com, it can automatically generate:
```
/google/
/google1/
/google.tar
/google-admin/
/www/
/www1/
```

**Comment by shelld3v** [comment]
I don't think this should be done by dirsearch, as it doesn't fit the purpose of the tool. I believe there are some tools out there for this (I don't remember the name)

**Comment by shelld3v** [comment]
Decided not to implement this feature
