### ISSUE TITLE
how to load all extensions dict when scan start?

### ISSUE THREAD

**Issue by jasonwchn** [maurosoria/dirsearch#967]
Hello:

I'm using dirsearch on kali when I use paramrter "-e *".but I'v got a message.

The message is :
```
A weird extension was provided: 'banner.txt'. Please do not use * as the extension or enclose it in double quotes
```
I want to load all extensions when I beggin scan,How to do it?

**Comment by shelld3v** [comment]
@jasonwchn Try `-e "*"` instead of `-e *`
