### ISSUE TITLE
can't create direcroty!!

### ISSUE THREAD

**Issue by wudifengz** [maurosoria/dirsearch#968]
### What is the current behavior?

What actually happens?

### What is the expected behavior?

What it should be instead?

### Any additional information?

OS, python version, screenshots, dirsearch command, console output, ...?

#### Checker:
 - [x] I tested in the latest version of dirsearch

when I use it to scan a website with IP and PORT on windows OS. There is a Error:
NotADirectoryError: [WinError 267] Error direcotry name. : 'D:\\rttools\\web\\webscan\\dirsearch\\reports\\121.36.145.157:5557'

maybe the ":" can't in diractory name on windows OS.

**Comment by shelld3v** [comment]
@wudifengz Please update your direarch to the latest version from git (`git clone https://github.com/maurosoria/dirsearch`). Thanks!
