### ISSUE TITLE
error , I cann't use it 

### ISSUE THREAD

**Issue by Youknow2509** [maurosoria/dirsearch#969]
Traceback (most recent call last):
  File "C:\Tool\dirsearch.py", line 27, in <module>
    from lib.core.argument_parser import ArgumentParser
  File "C:\Tool\lib\core\argument_parser.py", line 24, in <module>
    from lib.parse.headers import HeadersParser
  File "C:\Tool\lib\parse\headers.py", line 23, in <module>
    from lib.utils.fmt import lowercase
  File "C:\Tool\lib\utils\fmt.py", line 19, in <module>
    from chardet import detect
ModuleNotFoundError: No module named 'chardet'

I can't run it
How could i fix it 
#bug

**Comment by shelld3v** [comment]
Try `pip3 install -r requirements.txt`

**Comment by Youknow2509** [comment]
I tried and it didn't work..........

**Comment by shelld3v** [comment]
How did you run dirsearch (Docker, ...)? What python version did you use? What was the pip version (`pip --version`)?

**Comment by Youknow2509** [comment]
Mình ũng người việt nha ...

**Comment by Youknow2509** [comment]
![image](https://user-images.githubusercontent.com/88392742/134447511-4c54eb09-8d3b-40be-95c2-1755b243ada3.png)

**Comment by shelld3v** [comment]
Đang chạy python 3 hay python 2? Chạy `pip install -r requirements.txt` thì nó hiển thị gì?

**Comment by Youknow2509** [comment]
Đang chạy python 3. Chạy " pip install -r requirements.txt"  lỗi 
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by shelld3v** [comment]
Sao lại ko có requirements.txt? Phải chạy command đấy ở trong folder dirsearch đó. Nhưng trước hết phải sửa lỗi `Defaulting to user installation because normal site-packages is not writeable`, có thể sửa tạm thời bằng cách chạy lệnh với đặc quyền cao nhất (`Administrator` trong Windows)

**Comment by Youknow2509** [comment]
chạy cái dirsearch.py xog lỗi như trên cùng mà .......

**Comment by shelld3v** [comment]
Đầu tiên truy cập vào folder dirsearch trong cmd/powershell, rồi mới chạy `pip install -r requirements.txt`

**Comment by CaijiOrz** [comment]
python -m pip install -r requirements.txt

**Comment by shelld3v** [comment]
Fixed!
