### ISSUE TITLE
Duplicate entries in default wordlist

### ISSUE THREAD

**Issue by bugbaba** [maurosoria/dirsearch#97]
Hi,

 ## Thanks for this great tool

The default wordlist [dicc.txt](https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt) is having `6041` entries in it 

But the are many that are repeat and is waste of time and resources 

Eg line no [2043-44](https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt#L2043)

> banneradmin
> banneradmin/

When a request is made to `/banneradmin` and if it is there it will redirect to `/banneradmin/` automatically
then sending a new request to `/banneradmin/` doesn't makes sense 

On removing all those and few others  the new total is : `5671` entries 

That is `370` less requests 

correct me if i am wrong, But i think the wordlist should be sorted to remove cases like these

**Comment by maurosoria** [comment]
> When a request is made to /banneradmin and if it is there it will redirect to /banneradmin/ automatically
> then sending a new request to /banneradmin/ doesn't makes sense

This is not entirely true. Maybe if in most sites, but with some technologies (api endpoints, ruby, python, some Java frameworks, etc) using the trailing slash gives different results.
