### ISSUE TITLE
what's the upstream and license of thirdparty/*.py

### ISSUE THREAD

**Issue by ClayStan** [maurosoria/dirsearch#974]
I'm packing dirsearch into debian,
so i want to know the upstream and license of 
https://github.com/maurosoria/dirsearch/blob/master/thirdparty/__init__.py
https://github.com/maurosoria/dirsearch/blob/master/thirdparty/socks.py
https://github.com/maurosoria/dirsearch/blob/master/thirdparty/sockshandler.py
https://github.com/maurosoria/dirsearch/tree/master/thirdparty/sqlmap

I guess thirdparty/__init__.py thirdparty/socks.py thirdparty/sockshandler.py maybe  wrote by youself? not thirdparty ？

but how about thirdparty/sqlmap ?
The only result I can find is here
https://python.hotexamples.com/es/examples/difflib/SequenceMatcher/quick_ratio/python-sequencematcher-quick_ratio-method-examples.html#0xf721d07b8ec7a432f9ef94bb42bb4c951ddccf25c28ddd108898289b6e39abde-6,,105,

This page shows that these codes are from https://github.com/a13409440944/dirsearch/blob/master/dirsearch-master/thirdparty/DynamicContentParser.py
but is not accessible now, and the project name is dirsearch too, this makes me very confused

**Comment by shelld3v** [comment]
https://github.com/sqlmapproject/sqlmap
https://github.com/Anorov/PySocks
