### ISSUE TITLE
When site use WAF  scan proc will stop at "first path"

### ISSUE THREAD

**Issue by firstC99** [maurosoria/dirsearch#985]
When site use WAF, first request url like .0zeGnr69eweI will stop, and prompt "Cannot connect to:" 

![image](https://user-images.githubusercontent.com/18412368/141065544-c6b39773-d607-4168-9ee7-f0d1e87fa50e.png)

Of course, I prefer it to continue to work, so i add this code it can continue to work

![image](https://user-images.githubusercontent.com/18412368/141066285-5f8e4c88-822b-4f5e-a679-c3b075ea346c.png)

**Comment by shelld3v** [comment]
It's a too special behaviour, I don't think I will do anything about this, the server interrupts the request when it has the dot in the path, which I don't see any possible solution here. I will think more to see if I can do something to avoid this, but probably we will need a new feature, like allowing the user to deploy the script by themself
