### ISSUE TITLE
Suppress InsecureRequestWarning

### ISSUE THREAD

**Issue by V35HR4J** [maurosoria/dirsearch#987]
HI!,
My target seems to have invalid certificate.
So i am facing this error.

/requests/packages/urllib3/connectionpool.py:834: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html

So, is there any tag as solution to this ? or any recomondations to fix this?

Thanks for Great Tool ✌️✌️

**Comment by shelld3v** [comment]
Hi, what version are you using?

**Comment by V35HR4J** [comment]
Hi!,
Just noticed that i was using older version.
Updated one seems fine.
Thanks again!
