### ISSUE TITLE
运行过程中出现这个报错是什么原因？

### ISSUE THREAD

**Issue by Scivous** [maurosoria/dirsearch#989]
![image](https://user-images.githubusercontent.com/66907785/142346286-54b97d71-fee8-4fc3-a395-7686a6415050.png)

requirement都安了。

**Comment by Scivous** [comment]
边扫边报错，
![image](https://user-images.githubusercontent.com/66907785/142346447-50788a4b-7d0f-48d7-a5bc-41472e968caa.png)

**Comment by Scivous** [comment]
运行的命令是：python dirsearch.py -u https://www.baidu.com/ -e * -r --recursion-depth 3 --recursion-status 200-399 -o report.html

**Comment by shelld3v** [comment]
您确定您使用的是最新版本吗? 尝试: 
```
python dirsearch.py -u https://www.baidu.com/ -e "*" -r --recursion-depth 3 --recursion-status 200-399 -o report.html --format html
```

**Comment by Scivous** [comment]
![image](https://user-images.githubusercontent.com/66907785/142349294-33e56d04-87cd-4b11-b9f0-0fd5600e2f5c.png)
还是不行
是最新版本。刚下的。

**Comment by shelld3v** [comment]
您能否将错误消息复制并粘贴到此处 (包括“FileNotFoundError...”部分) ？没有图像

**Comment by shelld3v** [comment]
现在问题解决了吗？ （使用最新版本）
