### ISSUE TITLE
Somethins wrong with this 

### ISSUE THREAD

**Issue by xxnbyy** [maurosoria/dirsearch#99]
Fatal error during site scanning: CONNECTION TIMEOUT: There was a problem in the request to: 59wGFRa0DjXL

What's the point of this fault?The domain i want to scan don't have thins one

**Comment by sanbotto** [comment]
I'm having the same issue, but now the parameter `--request-by-hostname` is no longer valid. Which option should I use? I'm trying to find valid paths for my home's router, so there's no HTTPS nor CDN involved.
