### ISSUE TITLE
AttributeError: 'Fuzzer' object has no attribute 'play_event'

### ISSUE THREAD

**Issue by hu185396** [maurosoria/dirsearch#991]
运行报错，运行命令：python dirsearch.py --url-list url.txt -i 200,300 --timeout 3 –random-agent --max-time=3 -F
![image](https://user-images.githubusercontent.com/50415778/143680992-5ae3475f-24f5-49c2-9127-bbf367ac6506.png)

**Comment by Vtanneru** [comment]
There is no play_event() func defined in the fuzzer.py

**Comment by shelld3v** [comment]
> There is no play_event() func defined in the fuzzer.py

We do set it in line 155. This issue only happens when you set the max runtime too short, so basically it doesn't impact the user experience
