### ISSUE TITLE
--max-time只对单个url生效

### ISSUE THREAD

**Issue by hu185396** [maurosoria/dirsearch#992]
--max-time参数，使用--url-list指定url列表时只能对第一个url有效，后续请求无法超时退出

**Comment by shelld3v** [comment]
这不是实际问题，问题是如果您将 --max-time 设置得太小（如上一期中为 3 秒），则 dirsearch 不会退出。我正在关闭这个并保持你以前的问题打开

**Comment by hu185396** [comment]
我将--max-time设置为30，重新测试后发现，url列表只有第一条会在30秒后退出，后续的url会持续到结束，超过设置时间也不会自动退出
测试命令为python dirsearch.py --url-list url.txt -i 200,300 --timeout 1 –random-agent --max-time=30 -F
第一个url30秒后自动退出
![image](https://user-images.githubusercontent.com/50415778/143685283-6aab1891-3e3c-40a7-a7f5-bae0e3cc58f8.png)

第二个url开始后续都将运行所有扫描后才会退出，无法达到预期的30秒退出
![image](https://user-images.githubusercontent.com/50415778/143685286-6e9614dc-4a9f-4579-8155-f43c25dd77f2.png)

**Comment by shelld3v** [comment]
It seems that I missed something

**Comment by shelld3v** [comment]
修复已完成，将尽快合并，抱歉耽搁了
