### ISSUE TITLE
The server does not support HTTP / 2.0 and dirsearch cannot connect to it

### ISSUE THREAD

**Issue by shuraros2334** [maurosoria/dirsearch#996]
https://prnt.sc/21fy7x7 - HTTP/1.1 request and response

https://prnt.sc/21fyajc - HTTP/2.0 request and response

dirsearch sends the first request from http / 2.0 and since the server does not support this protocol and does not respond to it, dirsearch thinks that the server is down, but it is not

**Comment by shelld3v** [comment]
Hi, I can't reproduce the issue, first I added `/21fy7x7` and `/21fyajc` to my wordlist, then I scanned https://prnt.sc and no error appeared:

```
Target: https://prnt.sc/

[10:28:56] Starting:
[10:28:59] 200 -   16KB - /21fyajc
[10:28:59] 403 -    4KB - /!.htaccess
[10:28:59] 403 -    4KB - /!.htpasswd
[10:28:59] 200 -   16KB - /21fy7x7
```

**Comment by shelld3v** [comment]
Closing as it has been inactive for more than 30 days

**Comment by mouftan** [comment]
Hi im facing the same problem here any tips?
