### ISSUE TITLE
Under single thread, some dictionary contents will still be skipped

### ISSUE THREAD

**Issue by decadecaomm** [maurosoria/dirsearch#999]
When I scan sensitive directories such as tomcat, Dirsearch will automatically skip dictionary traversal about it,How to solve this problem

？

**Comment by shelld3v** [comment]
I don't get it, can you provide a screenshot with your expected behavior?

**Comment by decadecaomm** [comment]
uhmm....The situation is a little special,I can't reveal too much,Can the tool traverse the directory by identifying middleware？

**Comment by shelld3v** [comment]
I don't really understand wdym by "identifying middleware"

**Comment by decadecaomm** [comment]
When I use tomcat, will dirsearch automatically identify the currently used framework？

**Comment by shelld3v** [comment]
Did you mean "can dirsearch identify the technologies that the target uses"?

**Comment by decadecaomm** [comment]
yes

**Comment by shelld3v** [comment]
Currently, no, but we have that feature in the TODO list

**Comment by decadecaomm** [comment]
Ok,let me see
